/**
 * Vayu API
 * The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@withvayu.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CustomerExternalIntegration {
    'type': CustomerExternalIntegrationTypeEnum;
    'id': string;
    'name': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "CustomerExternalIntegrationTypeEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CustomerExternalIntegration.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum CustomerExternalIntegrationTypeEnum {
    NetSuite = 'NetSuite',
    QuickBooks = 'QuickBooks',
    Morning = 'Morning',
    Hubspot = 'Hubspot',
    Anrok = 'Anrok',
    Snowflake = 'Snowflake',
    Connact = 'Connact',
    Xero = 'Xero',
    Salesforce = 'Salesforce',
    Paddle = 'Paddle'
}

