/**
 * Vayu API
 * The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@withvayu.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductExternalIntegration } from '../models/ProductExternalIntegration';
import { HttpFile } from '../http/http';

export class ExternalCreditGrant {
    /**
    * Name of the credit grant. Used as the invoice line-item label when the grant is charged.
    */
    'name': string;
    /**
    * ID of the credit product whose pool this grant funds. A usage product debits the same pool by listing this ID in consumesCreditProductIds. Discover IDs via GET /credit-products.
    */
    'creditProductId': string;
    /**
    * What grantAmount represents: a monetary value in the contract currency (MONETARY) or a quantity of units (UNIT).
    */
    'balanceKind': ExternalCreditGrantBalanceKindEnum;
    /**
    * Amount granted into the pool per grant period — a currency amount when balanceKind is MONETARY (e.g. 500 = $500), or a unit quantity when balanceKind is UNIT.
    */
    'grantAmount': number;
    /**
    * Amount charged to the customer for this grant, in the contract currency. Required when balanceKind is UNIT (a unit quantity has no currency value of its own) — e.g. grant 1000 units for a price of 20 ($20). Optional when balanceKind is MONETARY: if omitted, the grant is sold at face value (price equals grantAmount).
    */
    'price'?: number | null;
    /**
    * How often the grant is applied: ONE_TIME grants once at contract start; RECURRING_MONTHLY, RECURRING_QUARTERLY and RECURRING_YEARLY re-grant each corresponding period.
    */
    'schedule': ExternalCreditGrantScheduleEnum;
    /**
    * Explicit date after which unused granted credits expire. Only supported on ONE_TIME grants. For policy-based expiry on recurring grants, use expirationPolicy instead.
    */
    'expirationDate'?: Date | null;
    /**
    * Controls when unused credits from a grant period expire. AT_NEXT_GRANT: credits expire at the end of each billing period (default for recurring). NEVER: credits never expire (default for ONE_TIME). END_OF_INVOICE: credits expire at the end of the invoice period. END_OF_RENEWAL_PERIOD: credits expire at the end of the contract renewal period. END_OF_CONTRACT: credits expire when the contract ends. AT_NEXT_GRANT and END_OF_INVOICE are not available for ONE_TIME grants.
    */
    'expirationPolicy'?: ExternalCreditGrantExpirationPolicyEnum;
    /**
    * Whether granted credits are applied to usage automatically. Defaults to true.
    */
    'applyAutomatically'?: boolean;
    /**
    * Links the subscription created for a recurring credit grant to matching products in V3 integrations (e.g. Paddle). The grant\'s inferred product is linked to each external integration after the contract is created, so invoices for the grant are exported to it. At most one entry per provider. Applies only to credit grants on a contract — ignored on credit top-ups. Currently only Paddle is supported.
    */
    'externalIntegrations'?: Array<ProductExternalIntegration> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "creditProductId",
            "baseName": "creditProductId",
            "type": "string",
            "format": ""
        },
        {
            "name": "balanceKind",
            "baseName": "balanceKind",
            "type": "ExternalCreditGrantBalanceKindEnum",
            "format": ""
        },
        {
            "name": "grantAmount",
            "baseName": "grantAmount",
            "type": "number",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number",
            "format": ""
        },
        {
            "name": "schedule",
            "baseName": "schedule",
            "type": "ExternalCreditGrantScheduleEnum",
            "format": ""
        },
        {
            "name": "expirationDate",
            "baseName": "expirationDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "expirationPolicy",
            "baseName": "expirationPolicy",
            "type": "ExternalCreditGrantExpirationPolicyEnum",
            "format": ""
        },
        {
            "name": "applyAutomatically",
            "baseName": "applyAutomatically",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "externalIntegrations",
            "baseName": "externalIntegrations",
            "type": "Array<ProductExternalIntegration>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ExternalCreditGrant.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum ExternalCreditGrantBalanceKindEnum {
    Monetary = 'MONETARY',
    Unit = 'UNIT'
}
export enum ExternalCreditGrantScheduleEnum {
    OneTime = 'ONE_TIME',
    RecurringMonthly = 'RECURRING_MONTHLY',
    RecurringQuarterly = 'RECURRING_QUARTERLY',
    RecurringYearly = 'RECURRING_YEARLY'
}
export enum ExternalCreditGrantExpirationPolicyEnum {
    AtNextGrant = 'AT_NEXT_GRANT',
    Never = 'NEVER',
    EndOfInvoice = 'END_OF_INVOICE',
    EndOfRenewalPeriod = 'END_OF_RENEWAL_PERIOD',
    EndOfContract = 'END_OF_CONTRACT'
}

