/**
 * Vayu API
 * The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@withvayu.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductGroupProductsInnerPricingOneOf3SubscriptionCadence } from '../models/ProductGroupProductsInnerPricingOneOf3SubscriptionCadence';
import { ProductGroupProductsInnerPricingOneOf3TiersInner } from '../models/ProductGroupProductsInnerPricingOneOf3TiersInner';
import { HttpFile } from '../http/http';

export class ProductGroupProductsInnerPricingOneOf3 {
    'type': ProductGroupProductsInnerPricingOneOf3TypeEnum;
    'tiers': Array<ProductGroupProductsInnerPricingOneOf3TiersInner>;
    'subscriptionCadence'?: ProductGroupProductsInnerPricingOneOf3SubscriptionCadence | null;
    'autoUpgrade'?: boolean | null;
    'prorate'?: boolean | null;
    'isRevShare'?: boolean | null;
    'baseAmount'?: number | null;
    /**
    * Usage reset is represented in months and must be one of: 1, 2, 3, 6, 12
    */
    'usageReset'?: number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ProductGroupProductsInnerPricingOneOf3TypeEnum",
            "format": ""
        },
        {
            "name": "tiers",
            "baseName": "tiers",
            "type": "Array<ProductGroupProductsInnerPricingOneOf3TiersInner>",
            "format": ""
        },
        {
            "name": "subscriptionCadence",
            "baseName": "subscriptionCadence",
            "type": "ProductGroupProductsInnerPricingOneOf3SubscriptionCadence",
            "format": ""
        },
        {
            "name": "autoUpgrade",
            "baseName": "autoUpgrade",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "prorate",
            "baseName": "prorate",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isRevShare",
            "baseName": "isRevShare",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "baseAmount",
            "baseName": "baseAmount",
            "type": "number",
            "format": ""
        },
        {
            "name": "usageReset",
            "baseName": "usageReset",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductGroupProductsInnerPricingOneOf3.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum ProductGroupProductsInnerPricingOneOf3TypeEnum {
    Tiered = 'TIERED'
}

