/**
 * Vayu API
 * The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@withvayu.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PaymentTerm } from '../models/PaymentTerm';
import { ProductCloudProviderSettings } from '../models/ProductCloudProviderSettings';
import { ProductExternalIntegration } from '../models/ProductExternalIntegration';
import { ProductGroupProductsInnerCommitment } from '../models/ProductGroupProductsInnerCommitment';
import { ProductGroupProductsInnerPricing } from '../models/ProductGroupProductsInnerPricing';
import { ProductGroupProductsInnerScheduling } from '../models/ProductGroupProductsInnerScheduling';
import { HttpFile } from '../http/http';

export class ProductGroupProductsInner {
    /**
    * The display name of the product
    */
    'displayName': string;
    /**
    * The description of the product
    */
    'description'?: string | null;
    /**
    * Whether to disable the default description on generated line items
    */
    'disableDescription'?: boolean | null;
    'scheduling': ProductGroupProductsInnerScheduling;
    'pricing': ProductGroupProductsInnerPricing;
    /**
    * The id of the a product from the catalog to connect the contract product to
    */
    'catalogProductId'?: string | null;
    /**
    * The id of the product in NetSuite ERP
    */
    'productErpId'?: string | null;
    /**
    * The class of the product in NetSuite ERP
    */
    'nsClass'?: string | null;
    /**
    * The id of the class of the product in NetSuite ERP
    */
    'nsClassId'?: string | null;
    /**
    * Links the product to matching products in V3 integrations (e.g. Paddle). For each entry, the product is linked to that external integration after the contract is created, so invoices for this product are exported to it. At most one entry per provider. Currently only Paddle is supported.
    */
    'externalIntegrations'?: Array<ProductExternalIntegration> | null;
    'commitment'?: ProductGroupProductsInnerCommitment | null;
    'paymentTerm'?: PaymentTerm | null;
    /**
    * Whether the invoicing period should be calendar aligned. If not provided, it will default to false. ONE_TIME and COMMERCIAL_TERMS pricing models cannot be calendar aligned. This field is ignored if the product is part of a ProductGroup.
    */
    'isCalendarAligned'?: boolean;
    'cloudProviderSettings'?: ProductCloudProviderSettings | null;
    /**
    * IDs of credit products whose pools are drawn down when this usage product is invoiced. Each ID matches the creditProductId of a credit grant on the same contract that funds the pool. Pools are drawn in the order listed. If omitted, no credits are applied and the product is billed at full price. Not supported inside productGroups.
    */
    'consumesCreditProductIds'?: Array<string> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "displayName",
            "baseName": "displayName",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "disableDescription",
            "baseName": "disableDescription",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "scheduling",
            "baseName": "scheduling",
            "type": "ProductGroupProductsInnerScheduling",
            "format": ""
        },
        {
            "name": "pricing",
            "baseName": "pricing",
            "type": "ProductGroupProductsInnerPricing",
            "format": ""
        },
        {
            "name": "catalogProductId",
            "baseName": "catalogProductId",
            "type": "string",
            "format": ""
        },
        {
            "name": "productErpId",
            "baseName": "productErpId",
            "type": "string",
            "format": ""
        },
        {
            "name": "nsClass",
            "baseName": "nsClass",
            "type": "string",
            "format": ""
        },
        {
            "name": "nsClassId",
            "baseName": "nsClassId",
            "type": "string",
            "format": ""
        },
        {
            "name": "externalIntegrations",
            "baseName": "externalIntegrations",
            "type": "Array<ProductExternalIntegration>",
            "format": ""
        },
        {
            "name": "commitment",
            "baseName": "commitment",
            "type": "ProductGroupProductsInnerCommitment",
            "format": ""
        },
        {
            "name": "paymentTerm",
            "baseName": "paymentTerm",
            "type": "PaymentTerm",
            "format": ""
        },
        {
            "name": "isCalendarAligned",
            "baseName": "isCalendarAligned",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "cloudProviderSettings",
            "baseName": "cloudProviderSettings",
            "type": "ProductCloudProviderSettings",
            "format": ""
        },
        {
            "name": "consumesCreditProductIds",
            "baseName": "consumesCreditProductIds",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductGroupProductsInner.attributeTypeMap;
    }

    public constructor() {
    }
}


