/**
 * Vayu API
 * The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@withvayu.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ProductGroupProductsInnerPricingOneOf5 {
    'type': ProductGroupProductsInnerPricingOneOf5TypeEnum;
    /**
    * The fixed amount to deduct
    */
    'amountToDeduct': number;
    /**
    * The number of installments to spread the deduction over
    */
    'installments'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ProductGroupProductsInnerPricingOneOf5TypeEnum",
            "format": ""
        },
        {
            "name": "amountToDeduct",
            "baseName": "amountToDeduct",
            "type": "number",
            "format": ""
        },
        {
            "name": "installments",
            "baseName": "installments",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductGroupProductsInnerPricingOneOf5.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum ProductGroupProductsInnerPricingOneOf5TypeEnum {
    FixedDeduction = 'FIXED_DEDUCTION'
}

