/**
 * Vayu API
 * The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@withvayu.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductGroupProductsInnerPricingOneOf } from '../models/ProductGroupProductsInnerPricingOneOf';
import { ProductGroupProductsInnerPricingOneOf1 } from '../models/ProductGroupProductsInnerPricingOneOf1';
import { ProductGroupProductsInnerPricingOneOf2 } from '../models/ProductGroupProductsInnerPricingOneOf2';
import { ProductGroupProductsInnerPricingOneOf3 } from '../models/ProductGroupProductsInnerPricingOneOf3';
import { ProductGroupProductsInnerPricingOneOf4 } from '../models/ProductGroupProductsInnerPricingOneOf4';
import { HttpFile } from '../http/http';

/**
* The pricing of the product
*/
/**
 * @type ProductGroupProductsInnerPricing
 * Type
 * @export
 */
export type ProductGroupProductsInnerPricing = ProductGroupProductsInnerPricingOneOf | ProductGroupProductsInnerPricingOneOf1 | ProductGroupProductsInnerPricingOneOf2 | ProductGroupProductsInnerPricingOneOf3 | ProductGroupProductsInnerPricingOneOf4;

/**
* @type ProductGroupProductsInnerPricingClass
    * The pricing of the product
* @export
*/
export class ProductGroupProductsInnerPricingClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}




