/**
 * Vayu API
 * The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@withvayu.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductGroupProductsInnerPricingOneOfDiscount } from '../models/ProductGroupProductsInnerPricingOneOfDiscount';
import { HttpFile } from '../http/http';

export class ProductGroupProductsInnerPricingOneOf {
    'type': ProductGroupProductsInnerPricingOneOfTypeEnum;
    'price': number;
    'discount'?: ProductGroupProductsInnerPricingOneOfDiscount | null;
    /**
    * Whether this one-time fee is a credit purchase. When true, the product is treated as a prepaid credit that the customer can use later. Defaults to false.
    */
    'isCreditPurchase'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ProductGroupProductsInnerPricingOneOfTypeEnum",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number",
            "format": ""
        },
        {
            "name": "discount",
            "baseName": "discount",
            "type": "ProductGroupProductsInnerPricingOneOfDiscount",
            "format": ""
        },
        {
            "name": "isCreditPurchase",
            "baseName": "isCreditPurchase",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductGroupProductsInnerPricingOneOf.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum ProductGroupProductsInnerPricingOneOfTypeEnum {
    OneTime = 'ONE_TIME'
}

