/**
 * Vayu API
 * The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@withvayu.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ValidationErrorResponseParamsInner } from '../models/ValidationErrorResponseParamsInner';
import { HttpFile } from '../http/http';

export class ValidationErrorResponse {
    'type': ValidationErrorResponseTypeEnum;
    /**
    * Specific machine-readable error code
    */
    'code': string;
    /**
    * Human-readable error explanation
    */
    'message': string;
    /**
    * Single parameter that failed validation
    */
    'param'?: string;
    /**
    * Multiple parameters that failed validation
    */
    'params'?: Array<ValidationErrorResponseParamsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ValidationErrorResponseTypeEnum",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "param",
            "baseName": "param",
            "type": "string",
            "format": ""
        },
        {
            "name": "params",
            "baseName": "params",
            "type": "Array<ValidationErrorResponseParamsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ValidationErrorResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum ValidationErrorResponseTypeEnum {
    InvalidRequestError = 'invalid_request_error'
}

