# coding: utf-8

"""
    Vayu API

    The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

    The version of the OpenAPI document: 1.0.0
    Contact: dev@withvayu.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi.api.customers_api import CustomersApi


class TestCustomersApi(unittest.TestCase):
    """CustomersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CustomersApi()

    def tearDown(self) -> None:
        pass

    def test_create_customer(self) -> None:
        """Test case for create_customer

        Create Customer
        """
        pass

    def test_create_customer_relation(self) -> None:
        """Test case for create_customer_relation

        Create Customer relation
        """
        pass

    def test_delete_customer(self) -> None:
        """Test case for delete_customer

        Delete Customer
        """
        pass

    def test_get_customer(self) -> None:
        """Test case for get_customer

        Get Customer
        """
        pass

    def test_get_customer_by_external_id(self) -> None:
        """Test case for get_customer_by_external_id

        Get customer by externalId
        """
        pass

    def test_get_customer_by_integration_id(self) -> None:
        """Test case for get_customer_by_integration_id

        Get customer by integration id
        """
        pass

    def test_get_customer_by_name(self) -> None:
        """Test case for get_customer_by_name

        Get customer by name
        """
        pass

    def test_get_customer_products_consumptions(self) -> None:
        """Test case for get_customer_products_consumptions

        Get products consumptions by customer id
        """
        pass

    def test_get_customer_products_consumptions_by_alias(self) -> None:
        """Test case for get_customer_products_consumptions_by_alias

        Get products consumptions by customer alias
        """
        pass

    def test_get_customer_relation(self) -> None:
        """Test case for get_customer_relation

        Get Customer relation
        """
        pass

    def test_list_customers(self) -> None:
        """Test case for list_customers

        List Customers
        """
        pass

    def test_update_customer(self) -> None:
        """Test case for update_customer

        Update Customer
        """
        pass


if __name__ == '__main__':
    unittest.main()
