# coding: utf-8

"""
    Vayu API

    The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

    The version of the OpenAPI document: 1.0.0
    Contact: dev@withvayu.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi.api.meters_api import MetersApi


class TestMetersApi(unittest.TestCase):
    """MetersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MetersApi()

    def tearDown(self) -> None:
        pass

    def test_delete_meter(self) -> None:
        """Test case for delete_meter

        Delete Meter
        """
        pass

    def test_get_meter(self) -> None:
        """Test case for get_meter

        Get Meter
        """
        pass

    def test_list_meters(self) -> None:
        """Test case for list_meters

        List Meters
        """
        pass

    def test_update_meter(self) -> None:
        """Test case for update_meter

        Update Meter
        """
        pass


if __name__ == '__main__':
    unittest.main()
