# coding: utf-8

"""
    Vayu API

    The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

    The version of the OpenAPI document: 1.0.0
    Contact: dev@withvayu.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi.api.invoices_api import InvoicesApi


class TestInvoicesApi(unittest.TestCase):
    """InvoicesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InvoicesApi()

    def tearDown(self) -> None:
        pass

    def test_get_invoice(self) -> None:
        """Test case for get_invoice

        Get Invoice
        """
        pass

    def test_get_invoice_payment_status(self) -> None:
        """Test case for get_invoice_payment_status

        Get invoice payment status
        """
        pass

    def test_list_invoices(self) -> None:
        """Test case for list_invoices

        List invoices
        """
        pass


if __name__ == '__main__':
    unittest.main()
