# coding: utf-8

"""
    Vayu API

    The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

    The version of the OpenAPI document: 1.0.0
    Contact: dev@withvayu.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi.models.rate_limit_error_response import RateLimitErrorResponse

class TestRateLimitErrorResponse(unittest.TestCase):
    """RateLimitErrorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RateLimitErrorResponse:
        """Test RateLimitErrorResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RateLimitErrorResponse`
        """
        model = RateLimitErrorResponse()
        if include_optional:
            return RateLimitErrorResponse(
                type = 'rate_limit_error',
                code = 'rate_limit_exceeded',
                message = ''
            )
        else:
            return RateLimitErrorResponse(
                type = 'rate_limit_error',
                code = 'rate_limit_exceeded',
                message = '',
        )
        """

    def testRateLimitErrorResponse(self):
        """Test RateLimitErrorResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
