# coding: utf-8

"""
    Vayu API

    The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

    The version of the OpenAPI document: 1.0.0
    Contact: dev@withvayu.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi.models.unauthorized_error_response import UnauthorizedErrorResponse

class TestUnauthorizedErrorResponse(unittest.TestCase):
    """UnauthorizedErrorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UnauthorizedErrorResponse:
        """Test UnauthorizedErrorResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UnauthorizedErrorResponse`
        """
        model = UnauthorizedErrorResponse()
        if include_optional:
            return UnauthorizedErrorResponse(
                type = 'authentication_error',
                code = 'authentication_failed',
                message = ''
            )
        else:
            return UnauthorizedErrorResponse(
                type = 'authentication_error',
                code = 'authentication_failed',
                message = '',
        )
        """

    def testUnauthorizedErrorResponse(self):
        """Test UnauthorizedErrorResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
