# coding: utf-8

"""
    Vayu API

    The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

    The version of the OpenAPI document: 1.0.0
    Contact: dev@withvayu.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi.models.product_group_products_inner_pricing_one_of4 import ProductGroupProductsInnerPricingOneOf4

class TestProductGroupProductsInnerPricingOneOf4(unittest.TestCase):
    """ProductGroupProductsInnerPricingOneOf4 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductGroupProductsInnerPricingOneOf4:
        """Test ProductGroupProductsInnerPricingOneOf4
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductGroupProductsInnerPricingOneOf4`
        """
        model = ProductGroupProductsInnerPricingOneOf4()
        if include_optional:
            return ProductGroupProductsInnerPricingOneOf4(
                type = 'PER_UNIT',
                price = 0,
                chunk_size = 0,
                usage_reset = 56,
                base_amount = 0
            )
        else:
            return ProductGroupProductsInnerPricingOneOf4(
                type = 'PER_UNIT',
                price = 0,
        )
        """

    def testProductGroupProductsInnerPricingOneOf4(self):
        """Test ProductGroupProductsInnerPricingOneOf4"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
