# coding: utf-8

"""
    Vayu API

    The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

    The version of the OpenAPI document: 1.0.0
    Contact: dev@withvayu.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi.models.delete_catalog_product_response import DeleteCatalogProductResponse

class TestDeleteCatalogProductResponse(unittest.TestCase):
    """DeleteCatalogProductResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeleteCatalogProductResponse:
        """Test DeleteCatalogProductResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeleteCatalogProductResponse`
        """
        model = DeleteCatalogProductResponse()
        if include_optional:
            return DeleteCatalogProductResponse(
                catalog_product = openapi.models.delete_catalog_product_response_catalog_product.DeleteCatalogProductResponse_catalogProduct(
                    name = '0', 
                    description = '', 
                    external_id = '', 
                    id = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deleted_at = '', )
            )
        else:
            return DeleteCatalogProductResponse(
                catalog_product = openapi.models.delete_catalog_product_response_catalog_product.DeleteCatalogProductResponse_catalogProduct(
                    name = '0', 
                    description = '', 
                    external_id = '', 
                    id = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deleted_at = '', ),
        )
        """

    def testDeleteCatalogProductResponse(self):
        """Test DeleteCatalogProductResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
