# coding: utf-8

"""
    Vayu API

    The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

    The version of the OpenAPI document: 1.0.0
    Contact: dev@withvayu.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi.models.send_events_request import SendEventsRequest

class TestSendEventsRequest(unittest.TestCase):
    """SendEventsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SendEventsRequest:
        """Test SendEventsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SendEventsRequest`
        """
        model = SendEventsRequest()
        if include_optional:
            return SendEventsRequest(
                events = [
                    openapi.models.event.Event(
                        name = 'api_call', 
                        timestamp = '2023-09-13T18:25:43.511Z', 
                        customer_alias = 'customer_12345', 
                        ref = '4f6cf35x-2c4y-483z-a0a9-158621f77a21', 
                        data = {"key1":"processing_duration","key2":"api_url"}, )
                    ]
            )
        else:
            return SendEventsRequest(
                events = [
                    openapi.models.event.Event(
                        name = 'api_call', 
                        timestamp = '2023-09-13T18:25:43.511Z', 
                        customer_alias = 'customer_12345', 
                        ref = '4f6cf35x-2c4y-483z-a0a9-158621f77a21', 
                        data = {"key1":"processing_duration","key2":"api_url"}, )
                    ],
        )
        """

    def testSendEventsRequest(self):
        """Test SendEventsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
