# coding: utf-8

"""
    Vayu API

    The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

    The version of the OpenAPI document: 1.0.0
    Contact: dev@withvayu.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi.api.credit_products_api import CreditProductsApi


class TestCreditProductsApi(unittest.TestCase):
    """CreditProductsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CreditProductsApi()

    def tearDown(self) -> None:
        pass

    def test_list_credit_products(self) -> None:
        """Test case for list_credit_products

        List credit products
        """
        pass


if __name__ == '__main__':
    unittest.main()
