# coding: utf-8

"""
    Vayu API

    The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

    The version of the OpenAPI document: 1.0.0
    Contact: dev@withvayu.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi.models.events_dry_run_response_object_meter_with_values_inner import EventsDryRunResponseObjectMeterWithValuesInner

class TestEventsDryRunResponseObjectMeterWithValuesInner(unittest.TestCase):
    """EventsDryRunResponseObjectMeterWithValuesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EventsDryRunResponseObjectMeterWithValuesInner:
        """Test EventsDryRunResponseObjectMeterWithValuesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EventsDryRunResponseObjectMeterWithValuesInner`
        """
        model = EventsDryRunResponseObjectMeterWithValuesInner()
        if include_optional:
            return EventsDryRunResponseObjectMeterWithValuesInner(
                name = '0',
                event_name = '0',
                aggregation_method = openapi.models.aggregation_method.AggregationMethod(
                    operator = 'Count', 
                    field = '', 
                    instance_key = '', ),
                filter = openapi.models.filter.Filter(
                    conditions = [
                        openapi.models.condition.Condition(
                            criterions = [
                                openapi.models.criterion.Criterion(
                                    field = '0', 
                                    operator = 'Equals', 
                                    value = '0', )
                                ], )
                        ], ),
                value = 1.337,
                instance_value = None
            )
        else:
            return EventsDryRunResponseObjectMeterWithValuesInner(
                name = '0',
                event_name = '0',
                aggregation_method = openapi.models.aggregation_method.AggregationMethod(
                    operator = 'Count', 
                    field = '', 
                    instance_key = '', ),
                value = 1.337,
        )
        """

    def testEventsDryRunResponseObjectMeterWithValuesInner(self):
        """Test EventsDryRunResponseObjectMeterWithValuesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
