# coding: utf-8

"""
    Vayu API

    The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

    The version of the OpenAPI document: 1.0.0
    Contact: dev@withvayu.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi.models.list_credit_ledger_entries_response import ListCreditLedgerEntriesResponse

class TestListCreditLedgerEntriesResponse(unittest.TestCase):
    """ListCreditLedgerEntriesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListCreditLedgerEntriesResponse:
        """Test ListCreditLedgerEntriesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListCreditLedgerEntriesResponse`
        """
        model = ListCreditLedgerEntriesResponse()
        if include_optional:
            return ListCreditLedgerEntriesResponse(
                entries = [
                    openapi.models.credit_ledger_entry.CreditLedgerEntry(
                        id = '62ECB020842930cc01FFCCfe', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        type = 'Grant', 
                        amount = 1.337, 
                        balance_after_entry = 1.337, 
                        invoice_id = '', 
                        erp_id = '', 
                        contract_id = '', 
                        integration_entities = [
                            openapi.models.integration_entity.IntegrationEntity(
                                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                integration_provider = 'Hubspot', 
                                integration_external_id = '', 
                                sync_status = 'None', 
                                metadata = {
                                    'key' : null
                                    }, 
                                raw_synced_data = {
                                    'key' : null
                                    }, )
                            ], )
                    ]
            )
        else:
            return ListCreditLedgerEntriesResponse(
                entries = [
                    openapi.models.credit_ledger_entry.CreditLedgerEntry(
                        id = '62ECB020842930cc01FFCCfe', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        type = 'Grant', 
                        amount = 1.337, 
                        balance_after_entry = 1.337, 
                        invoice_id = '', 
                        erp_id = '', 
                        contract_id = '', 
                        integration_entities = [
                            openapi.models.integration_entity.IntegrationEntity(
                                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                integration_provider = 'Hubspot', 
                                integration_external_id = '', 
                                sync_status = 'None', 
                                metadata = {
                                    'key' : null
                                    }, 
                                raw_synced_data = {
                                    'key' : null
                                    }, )
                            ], )
                    ],
        )
        """

    def testListCreditLedgerEntriesResponse(self):
        """Test ListCreditLedgerEntriesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
