# coding: utf-8

"""
    Vayu API

    The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

    The version of the OpenAPI document: 1.0.0
    Contact: dev@withvayu.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from openapi.models.product_external_integration import ProductExternalIntegration
from typing import Optional, Set
from typing_extensions import Self

class CreditTopUpRequestCreditGrant(BaseModel):
    """
    CreditTopUpRequestCreditGrant
    """ # noqa: E501
    name: StrictStr = Field(description="Name of the credit grant. Used as the invoice line-item label when the grant is charged.")
    credit_product_id: Annotated[str, Field(strict=True)] = Field(description="ID of the credit product whose pool this grant funds. A usage product debits the same pool by listing this ID in consumesCreditProductIds. Discover IDs via GET /credit-products.", alias="creditProductId")
    balance_kind: StrictStr = Field(description="What grantAmount represents: a monetary value in the contract currency (MONETARY) or a quantity of units (UNIT).", alias="balanceKind")
    grant_amount: Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]] = Field(description="Amount granted into the pool per grant period — a currency amount when balanceKind is MONETARY (e.g. 500 = $500), or a unit quantity when balanceKind is UNIT.", alias="grantAmount")
    price: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, description="Amount charged to the customer for this grant, in the contract currency. Required when balanceKind is UNIT (a unit quantity has no currency value of its own) — e.g. grant 1000 units for a price of 20 ($20). Optional when balanceKind is MONETARY: if omitted, the grant is sold at face value (price equals grantAmount).")
    schedule: StrictStr = Field(description="How often the grant is applied: ONE_TIME grants once at contract start; RECURRING_MONTHLY, RECURRING_QUARTERLY and RECURRING_YEARLY re-grant each corresponding period.")
    expiration_date: Optional[datetime] = Field(default=None, description="Explicit date after which unused granted credits expire. Only supported on ONE_TIME grants. For policy-based expiry on recurring grants, use expirationPolicy instead.", alias="expirationDate")
    expiration_policy: Optional[StrictStr] = Field(default=None, description="Controls when unused credits from a grant period expire. AT_NEXT_GRANT: credits expire at the end of each billing period (default for recurring). NEVER: credits never expire (default for ONE_TIME). END_OF_INVOICE: credits expire at the end of the invoice period. END_OF_RENEWAL_PERIOD: credits expire at the end of the contract renewal period. END_OF_CONTRACT: credits expire when the contract ends. AT_NEXT_GRANT and END_OF_INVOICE are not available for ONE_TIME grants.", alias="expirationPolicy")
    apply_automatically: Optional[StrictBool] = Field(default=None, description="Whether granted credits are applied to usage automatically. Defaults to true.", alias="applyAutomatically")
    external_integrations: Optional[List[ProductExternalIntegration]] = Field(default=None, description="Links the subscription created for a recurring credit grant to matching products in V3 integrations (e.g. Paddle). The grant's inferred product is linked to each external integration after the contract is created, so invoices for the grant are exported to it. At most one entry per provider. Applies only to credit grants on a contract — ignored on credit top-ups. Currently only Paddle is supported.", alias="externalIntegrations")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["name", "creditProductId", "balanceKind", "grantAmount", "price", "schedule", "expirationDate", "expirationPolicy", "applyAutomatically", "externalIntegrations"]

    @field_validator('credit_product_id')
    def credit_product_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[0-9a-fA-F]{24}$", value):
            raise ValueError(r"must validate the regular expression /^[0-9a-fA-F]{24}$/")
        return value

    @field_validator('balance_kind')
    def balance_kind_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['MONETARY', 'UNIT']):
            raise ValueError("must be one of enum values ('MONETARY', 'UNIT')")
        return value

    @field_validator('schedule')
    def schedule_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['ONE_TIME', 'RECURRING_MONTHLY', 'RECURRING_QUARTERLY', 'RECURRING_YEARLY']):
            raise ValueError("must be one of enum values ('ONE_TIME', 'RECURRING_MONTHLY', 'RECURRING_QUARTERLY', 'RECURRING_YEARLY')")
        return value

    @field_validator('expiration_policy')
    def expiration_policy_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['AT_NEXT_GRANT', 'NEVER', 'END_OF_INVOICE', 'END_OF_RENEWAL_PERIOD', 'END_OF_CONTRACT']):
            raise ValueError("must be one of enum values ('AT_NEXT_GRANT', 'NEVER', 'END_OF_INVOICE', 'END_OF_RENEWAL_PERIOD', 'END_OF_CONTRACT')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreditTopUpRequestCreditGrant from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in external_integrations (list)
        _items = []
        if self.external_integrations:
            for _item_external_integrations in self.external_integrations:
                if _item_external_integrations:
                    _items.append(_item_external_integrations.to_dict())
            _dict['externalIntegrations'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if price (nullable) is None
        # and model_fields_set contains the field
        if self.price is None and "price" in self.model_fields_set:
            _dict['price'] = None

        # set to None if expiration_date (nullable) is None
        # and model_fields_set contains the field
        if self.expiration_date is None and "expiration_date" in self.model_fields_set:
            _dict['expirationDate'] = None

        # set to None if external_integrations (nullable) is None
        # and model_fields_set contains the field
        if self.external_integrations is None and "external_integrations" in self.model_fields_set:
            _dict['externalIntegrations'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreditTopUpRequestCreditGrant from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "creditProductId": obj.get("creditProductId"),
            "balanceKind": obj.get("balanceKind"),
            "grantAmount": obj.get("grantAmount"),
            "price": obj.get("price"),
            "schedule": obj.get("schedule"),
            "expirationDate": obj.get("expirationDate"),
            "expirationPolicy": obj.get("expirationPolicy"),
            "applyAutomatically": obj.get("applyAutomatically"),
            "externalIntegrations": [ProductExternalIntegration.from_dict(_item) for _item in obj["externalIntegrations"]] if obj.get("externalIntegrations") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


