# coding: utf-8

"""
    Vayu API

    The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

    The version of the OpenAPI document: 1.0.0
    Contact: dev@withvayu.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ExternalOverageStrategy(str, Enum):
    """
    The strategy to apply when the overage occurs
    """

    """
    allowed enum values
    """
    IGNORE = 'IGNORE'
    BLOCK = 'BLOCK'
    UPGRADE_PLAN = 'UPGRADE_PLAN'
    TOP_UP = 'TOP_UP'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ExternalOverageStrategy from a JSON string"""
        return cls(json.loads(json_str))


