/*
Vayu API

Testing CustomFieldsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/vayucode/vayu-sdks/go/openapi"
)

func Test_openapi_CustomFieldsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CustomFieldsAPIService CreateCustomField", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CustomFieldsAPI.CreateCustomField(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CustomFieldsAPIService DeleteCustomField", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var customFieldId string

		resp, httpRes, err := apiClient.CustomFieldsAPI.DeleteCustomField(context.Background(), customFieldId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CustomFieldsAPIService GetCustomField", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var customFieldId string

		resp, httpRes, err := apiClient.CustomFieldsAPI.GetCustomField(context.Background(), customFieldId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CustomFieldsAPIService ListCustomFields", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CustomFieldsAPI.ListCustomFields(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CustomFieldsAPIService UpdateCustomField", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var customFieldId string

		resp, httpRes, err := apiClient.CustomFieldsAPI.UpdateCustomField(context.Background(), customFieldId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
