/*
Vayu API

Testing MeasurementsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/vayucode/vayu-sdks/go/openapi"
)

func Test_openapi_MeasurementsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test MeasurementsAPIService CreateMeasurement", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.MeasurementsAPI.CreateMeasurement(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MeasurementsAPIService DeleteMeasurement", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var measurementId string

		resp, httpRes, err := apiClient.MeasurementsAPI.DeleteMeasurement(context.Background(), measurementId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MeasurementsAPIService GetMeasurement", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var measurementId string

		resp, httpRes, err := apiClient.MeasurementsAPI.GetMeasurement(context.Background(), measurementId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MeasurementsAPIService ListMeasurements", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.MeasurementsAPI.ListMeasurements(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
