/*
Vayu API

Testing CatalogProductsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID/openapi"
)

func Test_openapi_CatalogProductsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CatalogProductsAPIService CreateCatalogProduct", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CatalogProductsAPI.CreateCatalogProduct(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CatalogProductsAPIService DeleteCatalogProduct", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var catalogProductId string

		resp, httpRes, err := apiClient.CatalogProductsAPI.DeleteCatalogProduct(context.Background(), catalogProductId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CatalogProductsAPIService GetCatalogProduct", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var catalogProductId string

		resp, httpRes, err := apiClient.CatalogProductsAPI.GetCatalogProduct(context.Background(), catalogProductId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CatalogProductsAPIService ListCatalogProducts", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CatalogProductsAPI.ListCatalogProducts(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CatalogProductsAPIService UpdateCatalogProduct", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var catalogProductId string

		resp, httpRes, err := apiClient.CatalogProductsAPI.UpdateCatalogProduct(context.Background(), catalogProductId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
