/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the V2QueryEventsAggregationRequestMetersInnerFiltersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2QueryEventsAggregationRequestMetersInnerFiltersInner{}

// V2QueryEventsAggregationRequestMetersInnerFiltersInner struct for V2QueryEventsAggregationRequestMetersInnerFiltersInner
type V2QueryEventsAggregationRequestMetersInnerFiltersInner struct {
	Field string `json:"field"`
	Operator string `json:"operator"`
	Value V2QueryEventsAggregationRequestMetersInnerFiltersInnerValue `json:"value"`
	AdditionalProperties map[string]interface{}
}

type _V2QueryEventsAggregationRequestMetersInnerFiltersInner V2QueryEventsAggregationRequestMetersInnerFiltersInner

// NewV2QueryEventsAggregationRequestMetersInnerFiltersInner instantiates a new V2QueryEventsAggregationRequestMetersInnerFiltersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2QueryEventsAggregationRequestMetersInnerFiltersInner(field string, operator string, value V2QueryEventsAggregationRequestMetersInnerFiltersInnerValue) *V2QueryEventsAggregationRequestMetersInnerFiltersInner {
	this := V2QueryEventsAggregationRequestMetersInnerFiltersInner{}
	this.Field = field
	this.Operator = operator
	this.Value = value
	return &this
}

// NewV2QueryEventsAggregationRequestMetersInnerFiltersInnerWithDefaults instantiates a new V2QueryEventsAggregationRequestMetersInnerFiltersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2QueryEventsAggregationRequestMetersInnerFiltersInnerWithDefaults() *V2QueryEventsAggregationRequestMetersInnerFiltersInner {
	this := V2QueryEventsAggregationRequestMetersInnerFiltersInner{}
	return &this
}

// GetField returns the Field field value
func (o *V2QueryEventsAggregationRequestMetersInnerFiltersInner) GetField() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Field
}

// GetFieldOk returns a tuple with the Field field value
// and a boolean to check if the value has been set.
func (o *V2QueryEventsAggregationRequestMetersInnerFiltersInner) GetFieldOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Field, true
}

// SetField sets field value
func (o *V2QueryEventsAggregationRequestMetersInnerFiltersInner) SetField(v string) {
	o.Field = v
}

// GetOperator returns the Operator field value
func (o *V2QueryEventsAggregationRequestMetersInnerFiltersInner) GetOperator() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Operator
}

// GetOperatorOk returns a tuple with the Operator field value
// and a boolean to check if the value has been set.
func (o *V2QueryEventsAggregationRequestMetersInnerFiltersInner) GetOperatorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Operator, true
}

// SetOperator sets field value
func (o *V2QueryEventsAggregationRequestMetersInnerFiltersInner) SetOperator(v string) {
	o.Operator = v
}

// GetValue returns the Value field value
func (o *V2QueryEventsAggregationRequestMetersInnerFiltersInner) GetValue() V2QueryEventsAggregationRequestMetersInnerFiltersInnerValue {
	if o == nil {
		var ret V2QueryEventsAggregationRequestMetersInnerFiltersInnerValue
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *V2QueryEventsAggregationRequestMetersInnerFiltersInner) GetValueOk() (*V2QueryEventsAggregationRequestMetersInnerFiltersInnerValue, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *V2QueryEventsAggregationRequestMetersInnerFiltersInner) SetValue(v V2QueryEventsAggregationRequestMetersInnerFiltersInnerValue) {
	o.Value = v
}

func (o V2QueryEventsAggregationRequestMetersInnerFiltersInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2QueryEventsAggregationRequestMetersInnerFiltersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["field"] = o.Field
	toSerialize["operator"] = o.Operator
	toSerialize["value"] = o.Value

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *V2QueryEventsAggregationRequestMetersInnerFiltersInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"field",
		"operator",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV2QueryEventsAggregationRequestMetersInnerFiltersInner := _V2QueryEventsAggregationRequestMetersInnerFiltersInner{}

	err = json.Unmarshal(data, &varV2QueryEventsAggregationRequestMetersInnerFiltersInner)

	if err != nil {
		return err
	}

	*o = V2QueryEventsAggregationRequestMetersInnerFiltersInner(varV2QueryEventsAggregationRequestMetersInnerFiltersInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "field")
		delete(additionalProperties, "operator")
		delete(additionalProperties, "value")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableV2QueryEventsAggregationRequestMetersInnerFiltersInner struct {
	value *V2QueryEventsAggregationRequestMetersInnerFiltersInner
	isSet bool
}

func (v NullableV2QueryEventsAggregationRequestMetersInnerFiltersInner) Get() *V2QueryEventsAggregationRequestMetersInnerFiltersInner {
	return v.value
}

func (v *NullableV2QueryEventsAggregationRequestMetersInnerFiltersInner) Set(val *V2QueryEventsAggregationRequestMetersInnerFiltersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableV2QueryEventsAggregationRequestMetersInnerFiltersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableV2QueryEventsAggregationRequestMetersInnerFiltersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2QueryEventsAggregationRequestMetersInnerFiltersInner(val *V2QueryEventsAggregationRequestMetersInnerFiltersInner) *NullableV2QueryEventsAggregationRequestMetersInnerFiltersInner {
	return &NullableV2QueryEventsAggregationRequestMetersInnerFiltersInner{value: val, isSet: true}
}

func (v NullableV2QueryEventsAggregationRequestMetersInnerFiltersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2QueryEventsAggregationRequestMetersInnerFiltersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


