/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the GetCustomerProductsConsumptionsByAliasResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCustomerProductsConsumptionsByAliasResponse{}

// GetCustomerProductsConsumptionsByAliasResponse struct for GetCustomerProductsConsumptionsByAliasResponse
type GetCustomerProductsConsumptionsByAliasResponse struct {
	ProductsConsumptions []ProductConsumption `json:"productsConsumptions"`
	AdditionalProperties map[string]interface{}
}

type _GetCustomerProductsConsumptionsByAliasResponse GetCustomerProductsConsumptionsByAliasResponse

// NewGetCustomerProductsConsumptionsByAliasResponse instantiates a new GetCustomerProductsConsumptionsByAliasResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCustomerProductsConsumptionsByAliasResponse(productsConsumptions []ProductConsumption) *GetCustomerProductsConsumptionsByAliasResponse {
	this := GetCustomerProductsConsumptionsByAliasResponse{}
	this.ProductsConsumptions = productsConsumptions
	return &this
}

// NewGetCustomerProductsConsumptionsByAliasResponseWithDefaults instantiates a new GetCustomerProductsConsumptionsByAliasResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCustomerProductsConsumptionsByAliasResponseWithDefaults() *GetCustomerProductsConsumptionsByAliasResponse {
	this := GetCustomerProductsConsumptionsByAliasResponse{}
	return &this
}

// GetProductsConsumptions returns the ProductsConsumptions field value
func (o *GetCustomerProductsConsumptionsByAliasResponse) GetProductsConsumptions() []ProductConsumption {
	if o == nil {
		var ret []ProductConsumption
		return ret
	}

	return o.ProductsConsumptions
}

// GetProductsConsumptionsOk returns a tuple with the ProductsConsumptions field value
// and a boolean to check if the value has been set.
func (o *GetCustomerProductsConsumptionsByAliasResponse) GetProductsConsumptionsOk() ([]ProductConsumption, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProductsConsumptions, true
}

// SetProductsConsumptions sets field value
func (o *GetCustomerProductsConsumptionsByAliasResponse) SetProductsConsumptions(v []ProductConsumption) {
	o.ProductsConsumptions = v
}

func (o GetCustomerProductsConsumptionsByAliasResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCustomerProductsConsumptionsByAliasResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["productsConsumptions"] = o.ProductsConsumptions

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetCustomerProductsConsumptionsByAliasResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"productsConsumptions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetCustomerProductsConsumptionsByAliasResponse := _GetCustomerProductsConsumptionsByAliasResponse{}

	err = json.Unmarshal(data, &varGetCustomerProductsConsumptionsByAliasResponse)

	if err != nil {
		return err
	}

	*o = GetCustomerProductsConsumptionsByAliasResponse(varGetCustomerProductsConsumptionsByAliasResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "productsConsumptions")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetCustomerProductsConsumptionsByAliasResponse struct {
	value *GetCustomerProductsConsumptionsByAliasResponse
	isSet bool
}

func (v NullableGetCustomerProductsConsumptionsByAliasResponse) Get() *GetCustomerProductsConsumptionsByAliasResponse {
	return v.value
}

func (v *NullableGetCustomerProductsConsumptionsByAliasResponse) Set(val *GetCustomerProductsConsumptionsByAliasResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCustomerProductsConsumptionsByAliasResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCustomerProductsConsumptionsByAliasResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCustomerProductsConsumptionsByAliasResponse(val *GetCustomerProductsConsumptionsByAliasResponse) *NullableGetCustomerProductsConsumptionsByAliasResponse {
	return &NullableGetCustomerProductsConsumptionsByAliasResponse{value: val, isSet: true}
}

func (v NullableGetCustomerProductsConsumptionsByAliasResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCustomerProductsConsumptionsByAliasResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


