/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ProductGroupProductsInnerPricingOneOfDiscount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductGroupProductsInnerPricingOneOfDiscount{}

// ProductGroupProductsInnerPricingOneOfDiscount An optional discount to apply to this product
type ProductGroupProductsInnerPricingOneOfDiscount struct {
	// The name of the discount. Will appear on the invoice.
	Name string `json:"name"`
	// The type of discount — FIXED for a fixed amount, PERCENTAGE for a percentage-based discount.
	Type string `json:"type"`
	// The discount amount. Interpreted as a currency amount for FIXED or a percentage for PERCENTAGE.
	Amount float32 `json:"amount"`
	// The number of billing periods the discount applies for. If not provided, the discount recurs indefinitely.
	Recurring *int32 `json:"recurring,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ProductGroupProductsInnerPricingOneOfDiscount ProductGroupProductsInnerPricingOneOfDiscount

// NewProductGroupProductsInnerPricingOneOfDiscount instantiates a new ProductGroupProductsInnerPricingOneOfDiscount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductGroupProductsInnerPricingOneOfDiscount(name string, type_ string, amount float32) *ProductGroupProductsInnerPricingOneOfDiscount {
	this := ProductGroupProductsInnerPricingOneOfDiscount{}
	this.Name = name
	this.Type = type_
	this.Amount = amount
	return &this
}

// NewProductGroupProductsInnerPricingOneOfDiscountWithDefaults instantiates a new ProductGroupProductsInnerPricingOneOfDiscount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductGroupProductsInnerPricingOneOfDiscountWithDefaults() *ProductGroupProductsInnerPricingOneOfDiscount {
	this := ProductGroupProductsInnerPricingOneOfDiscount{}
	return &this
}

// GetName returns the Name field value
func (o *ProductGroupProductsInnerPricingOneOfDiscount) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ProductGroupProductsInnerPricingOneOfDiscount) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ProductGroupProductsInnerPricingOneOfDiscount) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value
func (o *ProductGroupProductsInnerPricingOneOfDiscount) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ProductGroupProductsInnerPricingOneOfDiscount) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ProductGroupProductsInnerPricingOneOfDiscount) SetType(v string) {
	o.Type = v
}

// GetAmount returns the Amount field value
func (o *ProductGroupProductsInnerPricingOneOfDiscount) GetAmount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *ProductGroupProductsInnerPricingOneOfDiscount) GetAmountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *ProductGroupProductsInnerPricingOneOfDiscount) SetAmount(v float32) {
	o.Amount = v
}

// GetRecurring returns the Recurring field value if set, zero value otherwise.
func (o *ProductGroupProductsInnerPricingOneOfDiscount) GetRecurring() int32 {
	if o == nil || IsNil(o.Recurring) {
		var ret int32
		return ret
	}
	return *o.Recurring
}

// GetRecurringOk returns a tuple with the Recurring field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductGroupProductsInnerPricingOneOfDiscount) GetRecurringOk() (*int32, bool) {
	if o == nil || IsNil(o.Recurring) {
		return nil, false
	}
	return o.Recurring, true
}

// HasRecurring returns a boolean if a field has been set.
func (o *ProductGroupProductsInnerPricingOneOfDiscount) HasRecurring() bool {
	if o != nil && !IsNil(o.Recurring) {
		return true
	}

	return false
}

// SetRecurring gets a reference to the given int32 and assigns it to the Recurring field.
func (o *ProductGroupProductsInnerPricingOneOfDiscount) SetRecurring(v int32) {
	o.Recurring = &v
}

func (o ProductGroupProductsInnerPricingOneOfDiscount) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductGroupProductsInnerPricingOneOfDiscount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["type"] = o.Type
	toSerialize["amount"] = o.Amount
	if !IsNil(o.Recurring) {
		toSerialize["recurring"] = o.Recurring
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProductGroupProductsInnerPricingOneOfDiscount) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"type",
		"amount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProductGroupProductsInnerPricingOneOfDiscount := _ProductGroupProductsInnerPricingOneOfDiscount{}

	err = json.Unmarshal(data, &varProductGroupProductsInnerPricingOneOfDiscount)

	if err != nil {
		return err
	}

	*o = ProductGroupProductsInnerPricingOneOfDiscount(varProductGroupProductsInnerPricingOneOfDiscount)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "type")
		delete(additionalProperties, "amount")
		delete(additionalProperties, "recurring")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableProductGroupProductsInnerPricingOneOfDiscount struct {
	value *ProductGroupProductsInnerPricingOneOfDiscount
	isSet bool
}

func (v NullableProductGroupProductsInnerPricingOneOfDiscount) Get() *ProductGroupProductsInnerPricingOneOfDiscount {
	return v.value
}

func (v *NullableProductGroupProductsInnerPricingOneOfDiscount) Set(val *ProductGroupProductsInnerPricingOneOfDiscount) {
	v.value = val
	v.isSet = true
}

func (v NullableProductGroupProductsInnerPricingOneOfDiscount) IsSet() bool {
	return v.isSet
}

func (v *NullableProductGroupProductsInnerPricingOneOfDiscount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductGroupProductsInnerPricingOneOfDiscount(val *ProductGroupProductsInnerPricingOneOfDiscount) *NullableProductGroupProductsInnerPricingOneOfDiscount {
	return &NullableProductGroupProductsInnerPricingOneOfDiscount{value: val, isSet: true}
}

func (v NullableProductGroupProductsInnerPricingOneOfDiscount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductGroupProductsInnerPricingOneOfDiscount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


