/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UpdateCustomerRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateCustomerRequest{}

// UpdateCustomerRequest struct for UpdateCustomerRequest
type UpdateCustomerRequest struct {
	// The name of the customer
	Name *string `json:"name,omitempty"`
	// The aliases of the customer used to match events to the customer.
	Aliases []string `json:"aliases,omitempty"`
	// The contacts of the customer. Contact marked as primary is the target for invoice sharing.
	Contacts []Contact `json:"contacts,omitempty"`
	Source NullableCustomerSource `json:"source,omitempty"`
	// The legal name of the customer
	LegalName NullableString `json:"legalName,omitempty"`
	// The tax IDs of the customer
	TaxIds []string `json:"taxIds,omitempty"`
	// The tax ID of the customer (deprecated, use taxIds instead)
	// Deprecated
	TaxId NullableString `json:"taxId,omitempty"`
	CloudProviderSettings NullableCustomerCloudProviderSettings `json:"cloudProviderSettings,omitempty"`
	// The external ID of the customer
	ExternalId *string `json:"externalId,omitempty"`
	// The ID of the customer in the ERP system
	CustomerErpId NullableString `json:"customerErpId,omitempty"`
	Address NullableAddress `json:"address,omitempty"`
	// The ID of the customer in the Salesforce system
	SalesForceAccountId NullableString `json:"salesForceAccountId,omitempty"`
	// The due days of the customer
	DueDays NullableString `json:"dueDays,omitempty"`
	Currency NullableCurrency `json:"currency,omitempty"`
	// Custom fields from CRM systems (Salesforce, HubSpot, etc.)
	CustomFields []CustomField `json:"customFields,omitempty"`
	// The name of the subsidiary of the customer
	Subsidiary NullableString `json:"subsidiary,omitempty"`
}

// NewUpdateCustomerRequest instantiates a new UpdateCustomerRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateCustomerRequest() *UpdateCustomerRequest {
	this := UpdateCustomerRequest{}
	return &this
}

// NewUpdateCustomerRequestWithDefaults instantiates a new UpdateCustomerRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateCustomerRequestWithDefaults() *UpdateCustomerRequest {
	this := UpdateCustomerRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateCustomerRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCustomerRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateCustomerRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateCustomerRequest) SetName(v string) {
	o.Name = &v
}

// GetAliases returns the Aliases field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateCustomerRequest) GetAliases() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Aliases
}

// GetAliasesOk returns a tuple with the Aliases field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateCustomerRequest) GetAliasesOk() ([]string, bool) {
	if o == nil || IsNil(o.Aliases) {
		return nil, false
	}
	return o.Aliases, true
}

// HasAliases returns a boolean if a field has been set.
func (o *UpdateCustomerRequest) HasAliases() bool {
	if o != nil && !IsNil(o.Aliases) {
		return true
	}

	return false
}

// SetAliases gets a reference to the given []string and assigns it to the Aliases field.
func (o *UpdateCustomerRequest) SetAliases(v []string) {
	o.Aliases = v
}

// GetContacts returns the Contacts field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateCustomerRequest) GetContacts() []Contact {
	if o == nil {
		var ret []Contact
		return ret
	}
	return o.Contacts
}

// GetContactsOk returns a tuple with the Contacts field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateCustomerRequest) GetContactsOk() ([]Contact, bool) {
	if o == nil || IsNil(o.Contacts) {
		return nil, false
	}
	return o.Contacts, true
}

// HasContacts returns a boolean if a field has been set.
func (o *UpdateCustomerRequest) HasContacts() bool {
	if o != nil && !IsNil(o.Contacts) {
		return true
	}

	return false
}

// SetContacts gets a reference to the given []Contact and assigns it to the Contacts field.
func (o *UpdateCustomerRequest) SetContacts(v []Contact) {
	o.Contacts = v
}

// GetSource returns the Source field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateCustomerRequest) GetSource() CustomerSource {
	if o == nil || IsNil(o.Source.Get()) {
		var ret CustomerSource
		return ret
	}
	return *o.Source.Get()
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateCustomerRequest) GetSourceOk() (*CustomerSource, bool) {
	if o == nil {
		return nil, false
	}
	return o.Source.Get(), o.Source.IsSet()
}

// HasSource returns a boolean if a field has been set.
func (o *UpdateCustomerRequest) HasSource() bool {
	if o != nil && o.Source.IsSet() {
		return true
	}

	return false
}

// SetSource gets a reference to the given NullableCustomerSource and assigns it to the Source field.
func (o *UpdateCustomerRequest) SetSource(v CustomerSource) {
	o.Source.Set(&v)
}
// SetSourceNil sets the value for Source to be an explicit nil
func (o *UpdateCustomerRequest) SetSourceNil() {
	o.Source.Set(nil)
}

// UnsetSource ensures that no value is present for Source, not even an explicit nil
func (o *UpdateCustomerRequest) UnsetSource() {
	o.Source.Unset()
}

// GetLegalName returns the LegalName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateCustomerRequest) GetLegalName() string {
	if o == nil || IsNil(o.LegalName.Get()) {
		var ret string
		return ret
	}
	return *o.LegalName.Get()
}

// GetLegalNameOk returns a tuple with the LegalName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateCustomerRequest) GetLegalNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LegalName.Get(), o.LegalName.IsSet()
}

// HasLegalName returns a boolean if a field has been set.
func (o *UpdateCustomerRequest) HasLegalName() bool {
	if o != nil && o.LegalName.IsSet() {
		return true
	}

	return false
}

// SetLegalName gets a reference to the given NullableString and assigns it to the LegalName field.
func (o *UpdateCustomerRequest) SetLegalName(v string) {
	o.LegalName.Set(&v)
}
// SetLegalNameNil sets the value for LegalName to be an explicit nil
func (o *UpdateCustomerRequest) SetLegalNameNil() {
	o.LegalName.Set(nil)
}

// UnsetLegalName ensures that no value is present for LegalName, not even an explicit nil
func (o *UpdateCustomerRequest) UnsetLegalName() {
	o.LegalName.Unset()
}

// GetTaxIds returns the TaxIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateCustomerRequest) GetTaxIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.TaxIds
}

// GetTaxIdsOk returns a tuple with the TaxIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateCustomerRequest) GetTaxIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.TaxIds) {
		return nil, false
	}
	return o.TaxIds, true
}

// HasTaxIds returns a boolean if a field has been set.
func (o *UpdateCustomerRequest) HasTaxIds() bool {
	if o != nil && !IsNil(o.TaxIds) {
		return true
	}

	return false
}

// SetTaxIds gets a reference to the given []string and assigns it to the TaxIds field.
func (o *UpdateCustomerRequest) SetTaxIds(v []string) {
	o.TaxIds = v
}

// GetTaxId returns the TaxId field value if set, zero value otherwise (both if not set or set to explicit null).
// Deprecated
func (o *UpdateCustomerRequest) GetTaxId() string {
	if o == nil || IsNil(o.TaxId.Get()) {
		var ret string
		return ret
	}
	return *o.TaxId.Get()
}

// GetTaxIdOk returns a tuple with the TaxId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
// Deprecated
func (o *UpdateCustomerRequest) GetTaxIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TaxId.Get(), o.TaxId.IsSet()
}

// HasTaxId returns a boolean if a field has been set.
func (o *UpdateCustomerRequest) HasTaxId() bool {
	if o != nil && o.TaxId.IsSet() {
		return true
	}

	return false
}

// SetTaxId gets a reference to the given NullableString and assigns it to the TaxId field.
// Deprecated
func (o *UpdateCustomerRequest) SetTaxId(v string) {
	o.TaxId.Set(&v)
}
// SetTaxIdNil sets the value for TaxId to be an explicit nil
func (o *UpdateCustomerRequest) SetTaxIdNil() {
	o.TaxId.Set(nil)
}

// UnsetTaxId ensures that no value is present for TaxId, not even an explicit nil
func (o *UpdateCustomerRequest) UnsetTaxId() {
	o.TaxId.Unset()
}

// GetCloudProviderSettings returns the CloudProviderSettings field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateCustomerRequest) GetCloudProviderSettings() CustomerCloudProviderSettings {
	if o == nil || IsNil(o.CloudProviderSettings.Get()) {
		var ret CustomerCloudProviderSettings
		return ret
	}
	return *o.CloudProviderSettings.Get()
}

// GetCloudProviderSettingsOk returns a tuple with the CloudProviderSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateCustomerRequest) GetCloudProviderSettingsOk() (*CustomerCloudProviderSettings, bool) {
	if o == nil {
		return nil, false
	}
	return o.CloudProviderSettings.Get(), o.CloudProviderSettings.IsSet()
}

// HasCloudProviderSettings returns a boolean if a field has been set.
func (o *UpdateCustomerRequest) HasCloudProviderSettings() bool {
	if o != nil && o.CloudProviderSettings.IsSet() {
		return true
	}

	return false
}

// SetCloudProviderSettings gets a reference to the given NullableCustomerCloudProviderSettings and assigns it to the CloudProviderSettings field.
func (o *UpdateCustomerRequest) SetCloudProviderSettings(v CustomerCloudProviderSettings) {
	o.CloudProviderSettings.Set(&v)
}
// SetCloudProviderSettingsNil sets the value for CloudProviderSettings to be an explicit nil
func (o *UpdateCustomerRequest) SetCloudProviderSettingsNil() {
	o.CloudProviderSettings.Set(nil)
}

// UnsetCloudProviderSettings ensures that no value is present for CloudProviderSettings, not even an explicit nil
func (o *UpdateCustomerRequest) UnsetCloudProviderSettings() {
	o.CloudProviderSettings.Unset()
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise.
func (o *UpdateCustomerRequest) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId) {
		var ret string
		return ret
	}
	return *o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCustomerRequest) GetExternalIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalId) {
		return nil, false
	}
	return o.ExternalId, true
}

// HasExternalId returns a boolean if a field has been set.
func (o *UpdateCustomerRequest) HasExternalId() bool {
	if o != nil && !IsNil(o.ExternalId) {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given string and assigns it to the ExternalId field.
func (o *UpdateCustomerRequest) SetExternalId(v string) {
	o.ExternalId = &v
}

// GetCustomerErpId returns the CustomerErpId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateCustomerRequest) GetCustomerErpId() string {
	if o == nil || IsNil(o.CustomerErpId.Get()) {
		var ret string
		return ret
	}
	return *o.CustomerErpId.Get()
}

// GetCustomerErpIdOk returns a tuple with the CustomerErpId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateCustomerRequest) GetCustomerErpIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CustomerErpId.Get(), o.CustomerErpId.IsSet()
}

// HasCustomerErpId returns a boolean if a field has been set.
func (o *UpdateCustomerRequest) HasCustomerErpId() bool {
	if o != nil && o.CustomerErpId.IsSet() {
		return true
	}

	return false
}

// SetCustomerErpId gets a reference to the given NullableString and assigns it to the CustomerErpId field.
func (o *UpdateCustomerRequest) SetCustomerErpId(v string) {
	o.CustomerErpId.Set(&v)
}
// SetCustomerErpIdNil sets the value for CustomerErpId to be an explicit nil
func (o *UpdateCustomerRequest) SetCustomerErpIdNil() {
	o.CustomerErpId.Set(nil)
}

// UnsetCustomerErpId ensures that no value is present for CustomerErpId, not even an explicit nil
func (o *UpdateCustomerRequest) UnsetCustomerErpId() {
	o.CustomerErpId.Unset()
}

// GetAddress returns the Address field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateCustomerRequest) GetAddress() Address {
	if o == nil || IsNil(o.Address.Get()) {
		var ret Address
		return ret
	}
	return *o.Address.Get()
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateCustomerRequest) GetAddressOk() (*Address, bool) {
	if o == nil {
		return nil, false
	}
	return o.Address.Get(), o.Address.IsSet()
}

// HasAddress returns a boolean if a field has been set.
func (o *UpdateCustomerRequest) HasAddress() bool {
	if o != nil && o.Address.IsSet() {
		return true
	}

	return false
}

// SetAddress gets a reference to the given NullableAddress and assigns it to the Address field.
func (o *UpdateCustomerRequest) SetAddress(v Address) {
	o.Address.Set(&v)
}
// SetAddressNil sets the value for Address to be an explicit nil
func (o *UpdateCustomerRequest) SetAddressNil() {
	o.Address.Set(nil)
}

// UnsetAddress ensures that no value is present for Address, not even an explicit nil
func (o *UpdateCustomerRequest) UnsetAddress() {
	o.Address.Unset()
}

// GetSalesForceAccountId returns the SalesForceAccountId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateCustomerRequest) GetSalesForceAccountId() string {
	if o == nil || IsNil(o.SalesForceAccountId.Get()) {
		var ret string
		return ret
	}
	return *o.SalesForceAccountId.Get()
}

// GetSalesForceAccountIdOk returns a tuple with the SalesForceAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateCustomerRequest) GetSalesForceAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SalesForceAccountId.Get(), o.SalesForceAccountId.IsSet()
}

// HasSalesForceAccountId returns a boolean if a field has been set.
func (o *UpdateCustomerRequest) HasSalesForceAccountId() bool {
	if o != nil && o.SalesForceAccountId.IsSet() {
		return true
	}

	return false
}

// SetSalesForceAccountId gets a reference to the given NullableString and assigns it to the SalesForceAccountId field.
func (o *UpdateCustomerRequest) SetSalesForceAccountId(v string) {
	o.SalesForceAccountId.Set(&v)
}
// SetSalesForceAccountIdNil sets the value for SalesForceAccountId to be an explicit nil
func (o *UpdateCustomerRequest) SetSalesForceAccountIdNil() {
	o.SalesForceAccountId.Set(nil)
}

// UnsetSalesForceAccountId ensures that no value is present for SalesForceAccountId, not even an explicit nil
func (o *UpdateCustomerRequest) UnsetSalesForceAccountId() {
	o.SalesForceAccountId.Unset()
}

// GetDueDays returns the DueDays field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateCustomerRequest) GetDueDays() string {
	if o == nil || IsNil(o.DueDays.Get()) {
		var ret string
		return ret
	}
	return *o.DueDays.Get()
}

// GetDueDaysOk returns a tuple with the DueDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateCustomerRequest) GetDueDaysOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DueDays.Get(), o.DueDays.IsSet()
}

// HasDueDays returns a boolean if a field has been set.
func (o *UpdateCustomerRequest) HasDueDays() bool {
	if o != nil && o.DueDays.IsSet() {
		return true
	}

	return false
}

// SetDueDays gets a reference to the given NullableString and assigns it to the DueDays field.
func (o *UpdateCustomerRequest) SetDueDays(v string) {
	o.DueDays.Set(&v)
}
// SetDueDaysNil sets the value for DueDays to be an explicit nil
func (o *UpdateCustomerRequest) SetDueDaysNil() {
	o.DueDays.Set(nil)
}

// UnsetDueDays ensures that no value is present for DueDays, not even an explicit nil
func (o *UpdateCustomerRequest) UnsetDueDays() {
	o.DueDays.Unset()
}

// GetCurrency returns the Currency field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateCustomerRequest) GetCurrency() Currency {
	if o == nil || IsNil(o.Currency.Get()) {
		var ret Currency
		return ret
	}
	return *o.Currency.Get()
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateCustomerRequest) GetCurrencyOk() (*Currency, bool) {
	if o == nil {
		return nil, false
	}
	return o.Currency.Get(), o.Currency.IsSet()
}

// HasCurrency returns a boolean if a field has been set.
func (o *UpdateCustomerRequest) HasCurrency() bool {
	if o != nil && o.Currency.IsSet() {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given NullableCurrency and assigns it to the Currency field.
func (o *UpdateCustomerRequest) SetCurrency(v Currency) {
	o.Currency.Set(&v)
}
// SetCurrencyNil sets the value for Currency to be an explicit nil
func (o *UpdateCustomerRequest) SetCurrencyNil() {
	o.Currency.Set(nil)
}

// UnsetCurrency ensures that no value is present for Currency, not even an explicit nil
func (o *UpdateCustomerRequest) UnsetCurrency() {
	o.Currency.Unset()
}

// GetCustomFields returns the CustomFields field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateCustomerRequest) GetCustomFields() []CustomField {
	if o == nil {
		var ret []CustomField
		return ret
	}
	return o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateCustomerRequest) GetCustomFieldsOk() ([]CustomField, bool) {
	if o == nil || IsNil(o.CustomFields) {
		return nil, false
	}
	return o.CustomFields, true
}

// HasCustomFields returns a boolean if a field has been set.
func (o *UpdateCustomerRequest) HasCustomFields() bool {
	if o != nil && !IsNil(o.CustomFields) {
		return true
	}

	return false
}

// SetCustomFields gets a reference to the given []CustomField and assigns it to the CustomFields field.
func (o *UpdateCustomerRequest) SetCustomFields(v []CustomField) {
	o.CustomFields = v
}

// GetSubsidiary returns the Subsidiary field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateCustomerRequest) GetSubsidiary() string {
	if o == nil || IsNil(o.Subsidiary.Get()) {
		var ret string
		return ret
	}
	return *o.Subsidiary.Get()
}

// GetSubsidiaryOk returns a tuple with the Subsidiary field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateCustomerRequest) GetSubsidiaryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Subsidiary.Get(), o.Subsidiary.IsSet()
}

// HasSubsidiary returns a boolean if a field has been set.
func (o *UpdateCustomerRequest) HasSubsidiary() bool {
	if o != nil && o.Subsidiary.IsSet() {
		return true
	}

	return false
}

// SetSubsidiary gets a reference to the given NullableString and assigns it to the Subsidiary field.
func (o *UpdateCustomerRequest) SetSubsidiary(v string) {
	o.Subsidiary.Set(&v)
}
// SetSubsidiaryNil sets the value for Subsidiary to be an explicit nil
func (o *UpdateCustomerRequest) SetSubsidiaryNil() {
	o.Subsidiary.Set(nil)
}

// UnsetSubsidiary ensures that no value is present for Subsidiary, not even an explicit nil
func (o *UpdateCustomerRequest) UnsetSubsidiary() {
	o.Subsidiary.Unset()
}

func (o UpdateCustomerRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateCustomerRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if o.Aliases != nil {
		toSerialize["aliases"] = o.Aliases
	}
	if o.Contacts != nil {
		toSerialize["contacts"] = o.Contacts
	}
	if o.Source.IsSet() {
		toSerialize["source"] = o.Source.Get()
	}
	if o.LegalName.IsSet() {
		toSerialize["legalName"] = o.LegalName.Get()
	}
	if o.TaxIds != nil {
		toSerialize["taxIds"] = o.TaxIds
	}
	if o.TaxId.IsSet() {
		toSerialize["taxId"] = o.TaxId.Get()
	}
	if o.CloudProviderSettings.IsSet() {
		toSerialize["cloudProviderSettings"] = o.CloudProviderSettings.Get()
	}
	if !IsNil(o.ExternalId) {
		toSerialize["externalId"] = o.ExternalId
	}
	if o.CustomerErpId.IsSet() {
		toSerialize["customerErpId"] = o.CustomerErpId.Get()
	}
	if o.Address.IsSet() {
		toSerialize["address"] = o.Address.Get()
	}
	if o.SalesForceAccountId.IsSet() {
		toSerialize["salesForceAccountId"] = o.SalesForceAccountId.Get()
	}
	if o.DueDays.IsSet() {
		toSerialize["dueDays"] = o.DueDays.Get()
	}
	if o.Currency.IsSet() {
		toSerialize["currency"] = o.Currency.Get()
	}
	if o.CustomFields != nil {
		toSerialize["customFields"] = o.CustomFields
	}
	if o.Subsidiary.IsSet() {
		toSerialize["subsidiary"] = o.Subsidiary.Get()
	}
	return toSerialize, nil
}

type NullableUpdateCustomerRequest struct {
	value *UpdateCustomerRequest
	isSet bool
}

func (v NullableUpdateCustomerRequest) Get() *UpdateCustomerRequest {
	return v.value
}

func (v *NullableUpdateCustomerRequest) Set(val *UpdateCustomerRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateCustomerRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateCustomerRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateCustomerRequest(val *UpdateCustomerRequest) *NullableUpdateCustomerRequest {
	return &NullableUpdateCustomerRequest{value: val, isSet: true}
}

func (v NullableUpdateCustomerRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateCustomerRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


