/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the DeleteContractResponseContract type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteContractResponseContract{}

// DeleteContractResponseContract struct for DeleteContractResponseContract
type DeleteContractResponseContract struct {
	// The start date of the contract
	StartDate time.Time `json:"startDate"`
	// The id of the customer that the contract is associated with
	CustomerId string `json:"customerId" validate:"regexp=^[0-9a-fA-F]{24}$"`
	// The name of the contract
	Name string `json:"name"`
	// The id of the sales force opportunity that the contract is associated with
	SalesForceOpportunityId NullableString `json:"salesForceOpportunityId,omitempty"`
	// The end date of the contract
	EndDate NullableTime `json:"endDate,omitempty"`
	// The signature date of the contract
	SignatureDate NullableTime `json:"signatureDate,omitempty"`
	// The products that the contract is associated with
	Products []ProductGroupProductsInner `json:"products,omitempty"`
	// Product groups are list of products that can be grouped as a single line item with shared settings like ERP settings, commitment settings, etc.
	ProductGroups []ProductGroup `json:"productGroups,omitempty"`
	// The name of the account manager of the contract
	AccountManager NullableString `json:"accountManager,omitempty"`
	// Whether to pro rate the invoices for the contract. If not provided, it will default to false
	// Deprecated
	ShouldProRateInvoices *bool `json:"shouldProRateInvoices,omitempty"`
	// Whether the contract is set to auto renew. If not provided, it will be treated as true
	AutoRenewContract *bool `json:"autoRenewContract,omitempty"`
	// Custom fields from CRM systems (Salesforce, HubSpot, etc.)
	CustomFields []CustomField `json:"customFields,omitempty"`
	// The stored custom field values associated with the contract
	CustomFieldValues []CustomFieldValue `json:"customFieldValues,omitempty"`
	Status *ContractStatus `json:"status,omitempty"`
	Id string `json:"id"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	DeletedAt string `json:"deletedAt"`
	AdditionalProperties map[string]interface{}
}

type _DeleteContractResponseContract DeleteContractResponseContract

// NewDeleteContractResponseContract instantiates a new DeleteContractResponseContract object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteContractResponseContract(startDate time.Time, customerId string, name string, id string, createdAt time.Time, updatedAt time.Time, deletedAt string) *DeleteContractResponseContract {
	this := DeleteContractResponseContract{}
	this.StartDate = startDate
	this.CustomerId = customerId
	this.Name = name
	this.Id = id
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.DeletedAt = deletedAt
	return &this
}

// NewDeleteContractResponseContractWithDefaults instantiates a new DeleteContractResponseContract object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteContractResponseContractWithDefaults() *DeleteContractResponseContract {
	this := DeleteContractResponseContract{}
	return &this
}

// GetStartDate returns the StartDate field value
func (o *DeleteContractResponseContract) GetStartDate() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value
// and a boolean to check if the value has been set.
func (o *DeleteContractResponseContract) GetStartDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartDate, true
}

// SetStartDate sets field value
func (o *DeleteContractResponseContract) SetStartDate(v time.Time) {
	o.StartDate = v
}

// GetCustomerId returns the CustomerId field value
func (o *DeleteContractResponseContract) GetCustomerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value
// and a boolean to check if the value has been set.
func (o *DeleteContractResponseContract) GetCustomerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomerId, true
}

// SetCustomerId sets field value
func (o *DeleteContractResponseContract) SetCustomerId(v string) {
	o.CustomerId = v
}

// GetName returns the Name field value
func (o *DeleteContractResponseContract) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DeleteContractResponseContract) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DeleteContractResponseContract) SetName(v string) {
	o.Name = v
}

// GetSalesForceOpportunityId returns the SalesForceOpportunityId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeleteContractResponseContract) GetSalesForceOpportunityId() string {
	if o == nil || IsNil(o.SalesForceOpportunityId.Get()) {
		var ret string
		return ret
	}
	return *o.SalesForceOpportunityId.Get()
}

// GetSalesForceOpportunityIdOk returns a tuple with the SalesForceOpportunityId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeleteContractResponseContract) GetSalesForceOpportunityIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SalesForceOpportunityId.Get(), o.SalesForceOpportunityId.IsSet()
}

// HasSalesForceOpportunityId returns a boolean if a field has been set.
func (o *DeleteContractResponseContract) HasSalesForceOpportunityId() bool {
	if o != nil && o.SalesForceOpportunityId.IsSet() {
		return true
	}

	return false
}

// SetSalesForceOpportunityId gets a reference to the given NullableString and assigns it to the SalesForceOpportunityId field.
func (o *DeleteContractResponseContract) SetSalesForceOpportunityId(v string) {
	o.SalesForceOpportunityId.Set(&v)
}
// SetSalesForceOpportunityIdNil sets the value for SalesForceOpportunityId to be an explicit nil
func (o *DeleteContractResponseContract) SetSalesForceOpportunityIdNil() {
	o.SalesForceOpportunityId.Set(nil)
}

// UnsetSalesForceOpportunityId ensures that no value is present for SalesForceOpportunityId, not even an explicit nil
func (o *DeleteContractResponseContract) UnsetSalesForceOpportunityId() {
	o.SalesForceOpportunityId.Unset()
}

// GetEndDate returns the EndDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeleteContractResponseContract) GetEndDate() time.Time {
	if o == nil || IsNil(o.EndDate.Get()) {
		var ret time.Time
		return ret
	}
	return *o.EndDate.Get()
}

// GetEndDateOk returns a tuple with the EndDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeleteContractResponseContract) GetEndDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.EndDate.Get(), o.EndDate.IsSet()
}

// HasEndDate returns a boolean if a field has been set.
func (o *DeleteContractResponseContract) HasEndDate() bool {
	if o != nil && o.EndDate.IsSet() {
		return true
	}

	return false
}

// SetEndDate gets a reference to the given NullableTime and assigns it to the EndDate field.
func (o *DeleteContractResponseContract) SetEndDate(v time.Time) {
	o.EndDate.Set(&v)
}
// SetEndDateNil sets the value for EndDate to be an explicit nil
func (o *DeleteContractResponseContract) SetEndDateNil() {
	o.EndDate.Set(nil)
}

// UnsetEndDate ensures that no value is present for EndDate, not even an explicit nil
func (o *DeleteContractResponseContract) UnsetEndDate() {
	o.EndDate.Unset()
}

// GetSignatureDate returns the SignatureDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeleteContractResponseContract) GetSignatureDate() time.Time {
	if o == nil || IsNil(o.SignatureDate.Get()) {
		var ret time.Time
		return ret
	}
	return *o.SignatureDate.Get()
}

// GetSignatureDateOk returns a tuple with the SignatureDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeleteContractResponseContract) GetSignatureDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.SignatureDate.Get(), o.SignatureDate.IsSet()
}

// HasSignatureDate returns a boolean if a field has been set.
func (o *DeleteContractResponseContract) HasSignatureDate() bool {
	if o != nil && o.SignatureDate.IsSet() {
		return true
	}

	return false
}

// SetSignatureDate gets a reference to the given NullableTime and assigns it to the SignatureDate field.
func (o *DeleteContractResponseContract) SetSignatureDate(v time.Time) {
	o.SignatureDate.Set(&v)
}
// SetSignatureDateNil sets the value for SignatureDate to be an explicit nil
func (o *DeleteContractResponseContract) SetSignatureDateNil() {
	o.SignatureDate.Set(nil)
}

// UnsetSignatureDate ensures that no value is present for SignatureDate, not even an explicit nil
func (o *DeleteContractResponseContract) UnsetSignatureDate() {
	o.SignatureDate.Unset()
}

// GetProducts returns the Products field value if set, zero value otherwise.
func (o *DeleteContractResponseContract) GetProducts() []ProductGroupProductsInner {
	if o == nil || IsNil(o.Products) {
		var ret []ProductGroupProductsInner
		return ret
	}
	return o.Products
}

// GetProductsOk returns a tuple with the Products field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteContractResponseContract) GetProductsOk() ([]ProductGroupProductsInner, bool) {
	if o == nil || IsNil(o.Products) {
		return nil, false
	}
	return o.Products, true
}

// HasProducts returns a boolean if a field has been set.
func (o *DeleteContractResponseContract) HasProducts() bool {
	if o != nil && !IsNil(o.Products) {
		return true
	}

	return false
}

// SetProducts gets a reference to the given []ProductGroupProductsInner and assigns it to the Products field.
func (o *DeleteContractResponseContract) SetProducts(v []ProductGroupProductsInner) {
	o.Products = v
}

// GetProductGroups returns the ProductGroups field value if set, zero value otherwise.
func (o *DeleteContractResponseContract) GetProductGroups() []ProductGroup {
	if o == nil || IsNil(o.ProductGroups) {
		var ret []ProductGroup
		return ret
	}
	return o.ProductGroups
}

// GetProductGroupsOk returns a tuple with the ProductGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteContractResponseContract) GetProductGroupsOk() ([]ProductGroup, bool) {
	if o == nil || IsNil(o.ProductGroups) {
		return nil, false
	}
	return o.ProductGroups, true
}

// HasProductGroups returns a boolean if a field has been set.
func (o *DeleteContractResponseContract) HasProductGroups() bool {
	if o != nil && !IsNil(o.ProductGroups) {
		return true
	}

	return false
}

// SetProductGroups gets a reference to the given []ProductGroup and assigns it to the ProductGroups field.
func (o *DeleteContractResponseContract) SetProductGroups(v []ProductGroup) {
	o.ProductGroups = v
}

// GetAccountManager returns the AccountManager field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeleteContractResponseContract) GetAccountManager() string {
	if o == nil || IsNil(o.AccountManager.Get()) {
		var ret string
		return ret
	}
	return *o.AccountManager.Get()
}

// GetAccountManagerOk returns a tuple with the AccountManager field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeleteContractResponseContract) GetAccountManagerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AccountManager.Get(), o.AccountManager.IsSet()
}

// HasAccountManager returns a boolean if a field has been set.
func (o *DeleteContractResponseContract) HasAccountManager() bool {
	if o != nil && o.AccountManager.IsSet() {
		return true
	}

	return false
}

// SetAccountManager gets a reference to the given NullableString and assigns it to the AccountManager field.
func (o *DeleteContractResponseContract) SetAccountManager(v string) {
	o.AccountManager.Set(&v)
}
// SetAccountManagerNil sets the value for AccountManager to be an explicit nil
func (o *DeleteContractResponseContract) SetAccountManagerNil() {
	o.AccountManager.Set(nil)
}

// UnsetAccountManager ensures that no value is present for AccountManager, not even an explicit nil
func (o *DeleteContractResponseContract) UnsetAccountManager() {
	o.AccountManager.Unset()
}

// GetShouldProRateInvoices returns the ShouldProRateInvoices field value if set, zero value otherwise.
// Deprecated
func (o *DeleteContractResponseContract) GetShouldProRateInvoices() bool {
	if o == nil || IsNil(o.ShouldProRateInvoices) {
		var ret bool
		return ret
	}
	return *o.ShouldProRateInvoices
}

// GetShouldProRateInvoicesOk returns a tuple with the ShouldProRateInvoices field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *DeleteContractResponseContract) GetShouldProRateInvoicesOk() (*bool, bool) {
	if o == nil || IsNil(o.ShouldProRateInvoices) {
		return nil, false
	}
	return o.ShouldProRateInvoices, true
}

// HasShouldProRateInvoices returns a boolean if a field has been set.
func (o *DeleteContractResponseContract) HasShouldProRateInvoices() bool {
	if o != nil && !IsNil(o.ShouldProRateInvoices) {
		return true
	}

	return false
}

// SetShouldProRateInvoices gets a reference to the given bool and assigns it to the ShouldProRateInvoices field.
// Deprecated
func (o *DeleteContractResponseContract) SetShouldProRateInvoices(v bool) {
	o.ShouldProRateInvoices = &v
}

// GetAutoRenewContract returns the AutoRenewContract field value if set, zero value otherwise.
func (o *DeleteContractResponseContract) GetAutoRenewContract() bool {
	if o == nil || IsNil(o.AutoRenewContract) {
		var ret bool
		return ret
	}
	return *o.AutoRenewContract
}

// GetAutoRenewContractOk returns a tuple with the AutoRenewContract field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteContractResponseContract) GetAutoRenewContractOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoRenewContract) {
		return nil, false
	}
	return o.AutoRenewContract, true
}

// HasAutoRenewContract returns a boolean if a field has been set.
func (o *DeleteContractResponseContract) HasAutoRenewContract() bool {
	if o != nil && !IsNil(o.AutoRenewContract) {
		return true
	}

	return false
}

// SetAutoRenewContract gets a reference to the given bool and assigns it to the AutoRenewContract field.
func (o *DeleteContractResponseContract) SetAutoRenewContract(v bool) {
	o.AutoRenewContract = &v
}

// GetCustomFields returns the CustomFields field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeleteContractResponseContract) GetCustomFields() []CustomField {
	if o == nil {
		var ret []CustomField
		return ret
	}
	return o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeleteContractResponseContract) GetCustomFieldsOk() ([]CustomField, bool) {
	if o == nil || IsNil(o.CustomFields) {
		return nil, false
	}
	return o.CustomFields, true
}

// HasCustomFields returns a boolean if a field has been set.
func (o *DeleteContractResponseContract) HasCustomFields() bool {
	if o != nil && !IsNil(o.CustomFields) {
		return true
	}

	return false
}

// SetCustomFields gets a reference to the given []CustomField and assigns it to the CustomFields field.
func (o *DeleteContractResponseContract) SetCustomFields(v []CustomField) {
	o.CustomFields = v
}

// GetCustomFieldValues returns the CustomFieldValues field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeleteContractResponseContract) GetCustomFieldValues() []CustomFieldValue {
	if o == nil {
		var ret []CustomFieldValue
		return ret
	}
	return o.CustomFieldValues
}

// GetCustomFieldValuesOk returns a tuple with the CustomFieldValues field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeleteContractResponseContract) GetCustomFieldValuesOk() ([]CustomFieldValue, bool) {
	if o == nil || IsNil(o.CustomFieldValues) {
		return nil, false
	}
	return o.CustomFieldValues, true
}

// HasCustomFieldValues returns a boolean if a field has been set.
func (o *DeleteContractResponseContract) HasCustomFieldValues() bool {
	if o != nil && !IsNil(o.CustomFieldValues) {
		return true
	}

	return false
}

// SetCustomFieldValues gets a reference to the given []CustomFieldValue and assigns it to the CustomFieldValues field.
func (o *DeleteContractResponseContract) SetCustomFieldValues(v []CustomFieldValue) {
	o.CustomFieldValues = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *DeleteContractResponseContract) GetStatus() ContractStatus {
	if o == nil || IsNil(o.Status) {
		var ret ContractStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteContractResponseContract) GetStatusOk() (*ContractStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *DeleteContractResponseContract) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given ContractStatus and assigns it to the Status field.
func (o *DeleteContractResponseContract) SetStatus(v ContractStatus) {
	o.Status = &v
}

// GetId returns the Id field value
func (o *DeleteContractResponseContract) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DeleteContractResponseContract) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DeleteContractResponseContract) SetId(v string) {
	o.Id = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *DeleteContractResponseContract) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *DeleteContractResponseContract) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *DeleteContractResponseContract) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *DeleteContractResponseContract) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *DeleteContractResponseContract) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *DeleteContractResponseContract) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetDeletedAt returns the DeletedAt field value
func (o *DeleteContractResponseContract) GetDeletedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeletedAt
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value
// and a boolean to check if the value has been set.
func (o *DeleteContractResponseContract) GetDeletedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeletedAt, true
}

// SetDeletedAt sets field value
func (o *DeleteContractResponseContract) SetDeletedAt(v string) {
	o.DeletedAt = v
}

func (o DeleteContractResponseContract) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteContractResponseContract) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["startDate"] = o.StartDate
	toSerialize["customerId"] = o.CustomerId
	toSerialize["name"] = o.Name
	if o.SalesForceOpportunityId.IsSet() {
		toSerialize["salesForceOpportunityId"] = o.SalesForceOpportunityId.Get()
	}
	if o.EndDate.IsSet() {
		toSerialize["endDate"] = o.EndDate.Get()
	}
	if o.SignatureDate.IsSet() {
		toSerialize["signatureDate"] = o.SignatureDate.Get()
	}
	if !IsNil(o.Products) {
		toSerialize["products"] = o.Products
	}
	if !IsNil(o.ProductGroups) {
		toSerialize["productGroups"] = o.ProductGroups
	}
	if o.AccountManager.IsSet() {
		toSerialize["accountManager"] = o.AccountManager.Get()
	}
	if !IsNil(o.ShouldProRateInvoices) {
		toSerialize["shouldProRateInvoices"] = o.ShouldProRateInvoices
	}
	if !IsNil(o.AutoRenewContract) {
		toSerialize["autoRenewContract"] = o.AutoRenewContract
	}
	if o.CustomFields != nil {
		toSerialize["customFields"] = o.CustomFields
	}
	if o.CustomFieldValues != nil {
		toSerialize["customFieldValues"] = o.CustomFieldValues
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	toSerialize["id"] = o.Id
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	toSerialize["deletedAt"] = o.DeletedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DeleteContractResponseContract) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"startDate",
		"customerId",
		"name",
		"id",
		"createdAt",
		"updatedAt",
		"deletedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteContractResponseContract := _DeleteContractResponseContract{}

	err = json.Unmarshal(data, &varDeleteContractResponseContract)

	if err != nil {
		return err
	}

	*o = DeleteContractResponseContract(varDeleteContractResponseContract)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "startDate")
		delete(additionalProperties, "customerId")
		delete(additionalProperties, "name")
		delete(additionalProperties, "salesForceOpportunityId")
		delete(additionalProperties, "endDate")
		delete(additionalProperties, "signatureDate")
		delete(additionalProperties, "products")
		delete(additionalProperties, "productGroups")
		delete(additionalProperties, "accountManager")
		delete(additionalProperties, "shouldProRateInvoices")
		delete(additionalProperties, "autoRenewContract")
		delete(additionalProperties, "customFields")
		delete(additionalProperties, "customFieldValues")
		delete(additionalProperties, "status")
		delete(additionalProperties, "id")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "updatedAt")
		delete(additionalProperties, "deletedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDeleteContractResponseContract struct {
	value *DeleteContractResponseContract
	isSet bool
}

func (v NullableDeleteContractResponseContract) Get() *DeleteContractResponseContract {
	return v.value
}

func (v *NullableDeleteContractResponseContract) Set(val *DeleteContractResponseContract) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteContractResponseContract) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteContractResponseContract) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteContractResponseContract(val *DeleteContractResponseContract) *NullableDeleteContractResponseContract {
	return &NullableDeleteContractResponseContract{value: val, isSet: true}
}

func (v NullableDeleteContractResponseContract) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteContractResponseContract) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


