/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the CreateCustomerRelationResponseCustomerRelation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCustomerRelationResponseCustomerRelation{}

// CreateCustomerRelationResponseCustomerRelation struct for CreateCustomerRelationResponseCustomerRelation
type CreateCustomerRelationResponseCustomerRelation struct {
	// Identifier of the parent customer in Vayu.
	VayuParentCustomerId string `json:"vayuParentCustomerId" validate:"regexp=^[0-9a-fA-F]{24}$"`
	// Identifier of the child customer in Vayu.
	VayuChildCustomerId string `json:"vayuChildCustomerId" validate:"regexp=^[0-9a-fA-F]{24}$"`
	Id string `json:"id"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	AdditionalProperties map[string]interface{}
}

type _CreateCustomerRelationResponseCustomerRelation CreateCustomerRelationResponseCustomerRelation

// NewCreateCustomerRelationResponseCustomerRelation instantiates a new CreateCustomerRelationResponseCustomerRelation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCustomerRelationResponseCustomerRelation(vayuParentCustomerId string, vayuChildCustomerId string, id string, createdAt time.Time, updatedAt time.Time) *CreateCustomerRelationResponseCustomerRelation {
	this := CreateCustomerRelationResponseCustomerRelation{}
	this.VayuParentCustomerId = vayuParentCustomerId
	this.VayuChildCustomerId = vayuChildCustomerId
	this.Id = id
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewCreateCustomerRelationResponseCustomerRelationWithDefaults instantiates a new CreateCustomerRelationResponseCustomerRelation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCustomerRelationResponseCustomerRelationWithDefaults() *CreateCustomerRelationResponseCustomerRelation {
	this := CreateCustomerRelationResponseCustomerRelation{}
	return &this
}

// GetVayuParentCustomerId returns the VayuParentCustomerId field value
func (o *CreateCustomerRelationResponseCustomerRelation) GetVayuParentCustomerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VayuParentCustomerId
}

// GetVayuParentCustomerIdOk returns a tuple with the VayuParentCustomerId field value
// and a boolean to check if the value has been set.
func (o *CreateCustomerRelationResponseCustomerRelation) GetVayuParentCustomerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VayuParentCustomerId, true
}

// SetVayuParentCustomerId sets field value
func (o *CreateCustomerRelationResponseCustomerRelation) SetVayuParentCustomerId(v string) {
	o.VayuParentCustomerId = v
}

// GetVayuChildCustomerId returns the VayuChildCustomerId field value
func (o *CreateCustomerRelationResponseCustomerRelation) GetVayuChildCustomerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VayuChildCustomerId
}

// GetVayuChildCustomerIdOk returns a tuple with the VayuChildCustomerId field value
// and a boolean to check if the value has been set.
func (o *CreateCustomerRelationResponseCustomerRelation) GetVayuChildCustomerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VayuChildCustomerId, true
}

// SetVayuChildCustomerId sets field value
func (o *CreateCustomerRelationResponseCustomerRelation) SetVayuChildCustomerId(v string) {
	o.VayuChildCustomerId = v
}

// GetId returns the Id field value
func (o *CreateCustomerRelationResponseCustomerRelation) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CreateCustomerRelationResponseCustomerRelation) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CreateCustomerRelationResponseCustomerRelation) SetId(v string) {
	o.Id = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *CreateCustomerRelationResponseCustomerRelation) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *CreateCustomerRelationResponseCustomerRelation) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *CreateCustomerRelationResponseCustomerRelation) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *CreateCustomerRelationResponseCustomerRelation) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *CreateCustomerRelationResponseCustomerRelation) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *CreateCustomerRelationResponseCustomerRelation) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o CreateCustomerRelationResponseCustomerRelation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCustomerRelationResponseCustomerRelation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["vayuParentCustomerId"] = o.VayuParentCustomerId
	toSerialize["vayuChildCustomerId"] = o.VayuChildCustomerId
	toSerialize["id"] = o.Id
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateCustomerRelationResponseCustomerRelation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"vayuParentCustomerId",
		"vayuChildCustomerId",
		"id",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateCustomerRelationResponseCustomerRelation := _CreateCustomerRelationResponseCustomerRelation{}

	err = json.Unmarshal(data, &varCreateCustomerRelationResponseCustomerRelation)

	if err != nil {
		return err
	}

	*o = CreateCustomerRelationResponseCustomerRelation(varCreateCustomerRelationResponseCustomerRelation)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "vayuParentCustomerId")
		delete(additionalProperties, "vayuChildCustomerId")
		delete(additionalProperties, "id")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "updatedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateCustomerRelationResponseCustomerRelation struct {
	value *CreateCustomerRelationResponseCustomerRelation
	isSet bool
}

func (v NullableCreateCustomerRelationResponseCustomerRelation) Get() *CreateCustomerRelationResponseCustomerRelation {
	return v.value
}

func (v *NullableCreateCustomerRelationResponseCustomerRelation) Set(val *CreateCustomerRelationResponseCustomerRelation) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCustomerRelationResponseCustomerRelation) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCustomerRelationResponseCustomerRelation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCustomerRelationResponseCustomerRelation(val *CreateCustomerRelationResponseCustomerRelation) *NullableCreateCustomerRelationResponseCustomerRelation {
	return &NullableCreateCustomerRelationResponseCustomerRelation{value: val, isSet: true}
}

func (v NullableCreateCustomerRelationResponseCustomerRelation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCustomerRelationResponseCustomerRelation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


