/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ProductGroupProductsInnerPricingOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductGroupProductsInnerPricingOneOf{}

// ProductGroupProductsInnerPricingOneOf struct for ProductGroupProductsInnerPricingOneOf
type ProductGroupProductsInnerPricingOneOf struct {
	Type string `json:"type"`
	Price float32 `json:"price"`
	AdditionalProperties map[string]interface{}
}

type _ProductGroupProductsInnerPricingOneOf ProductGroupProductsInnerPricingOneOf

// NewProductGroupProductsInnerPricingOneOf instantiates a new ProductGroupProductsInnerPricingOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductGroupProductsInnerPricingOneOf(type_ string, price float32) *ProductGroupProductsInnerPricingOneOf {
	this := ProductGroupProductsInnerPricingOneOf{}
	this.Type = type_
	this.Price = price
	return &this
}

// NewProductGroupProductsInnerPricingOneOfWithDefaults instantiates a new ProductGroupProductsInnerPricingOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductGroupProductsInnerPricingOneOfWithDefaults() *ProductGroupProductsInnerPricingOneOf {
	this := ProductGroupProductsInnerPricingOneOf{}
	return &this
}

// GetType returns the Type field value
func (o *ProductGroupProductsInnerPricingOneOf) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ProductGroupProductsInnerPricingOneOf) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ProductGroupProductsInnerPricingOneOf) SetType(v string) {
	o.Type = v
}

// GetPrice returns the Price field value
func (o *ProductGroupProductsInnerPricingOneOf) GetPrice() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Price
}

// GetPriceOk returns a tuple with the Price field value
// and a boolean to check if the value has been set.
func (o *ProductGroupProductsInnerPricingOneOf) GetPriceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Price, true
}

// SetPrice sets field value
func (o *ProductGroupProductsInnerPricingOneOf) SetPrice(v float32) {
	o.Price = v
}

func (o ProductGroupProductsInnerPricingOneOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductGroupProductsInnerPricingOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["price"] = o.Price

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProductGroupProductsInnerPricingOneOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"price",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProductGroupProductsInnerPricingOneOf := _ProductGroupProductsInnerPricingOneOf{}

	err = json.Unmarshal(data, &varProductGroupProductsInnerPricingOneOf)

	if err != nil {
		return err
	}

	*o = ProductGroupProductsInnerPricingOneOf(varProductGroupProductsInnerPricingOneOf)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "price")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableProductGroupProductsInnerPricingOneOf struct {
	value *ProductGroupProductsInnerPricingOneOf
	isSet bool
}

func (v NullableProductGroupProductsInnerPricingOneOf) Get() *ProductGroupProductsInnerPricingOneOf {
	return v.value
}

func (v *NullableProductGroupProductsInnerPricingOneOf) Set(val *ProductGroupProductsInnerPricingOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableProductGroupProductsInnerPricingOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableProductGroupProductsInnerPricingOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductGroupProductsInnerPricingOneOf(val *ProductGroupProductsInnerPricingOneOf) *NullableProductGroupProductsInnerPricingOneOf {
	return &NullableProductGroupProductsInnerPricingOneOf{value: val, isSet: true}
}

func (v NullableProductGroupProductsInnerPricingOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductGroupProductsInnerPricingOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


