/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the InvoicePaymentStatusResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InvoicePaymentStatusResponse{}

// InvoicePaymentStatusResponse struct for InvoicePaymentStatusResponse
type InvoicePaymentStatusResponse struct {
	InvoiceId string `json:"invoiceId" validate:"regexp=^[0-9a-fA-F]{24}$"`
	BillingStatus InvoiceBillingStatus `json:"billingStatus"`
	AmountDue float32 `json:"amountDue"`
	AmountPaid float32 `json:"amountPaid"`
	Total float32 `json:"total"`
	DueDate *time.Time `json:"dueDate,omitempty"`
	PaidAt *time.Time `json:"paidAt,omitempty"`
	InvoicePdfUrl *string `json:"invoicePdfUrl,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _InvoicePaymentStatusResponse InvoicePaymentStatusResponse

// NewInvoicePaymentStatusResponse instantiates a new InvoicePaymentStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvoicePaymentStatusResponse(invoiceId string, billingStatus InvoiceBillingStatus, amountDue float32, amountPaid float32, total float32) *InvoicePaymentStatusResponse {
	this := InvoicePaymentStatusResponse{}
	this.InvoiceId = invoiceId
	this.BillingStatus = billingStatus
	this.AmountDue = amountDue
	this.AmountPaid = amountPaid
	this.Total = total
	return &this
}

// NewInvoicePaymentStatusResponseWithDefaults instantiates a new InvoicePaymentStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvoicePaymentStatusResponseWithDefaults() *InvoicePaymentStatusResponse {
	this := InvoicePaymentStatusResponse{}
	return &this
}

// GetInvoiceId returns the InvoiceId field value
func (o *InvoicePaymentStatusResponse) GetInvoiceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InvoiceId
}

// GetInvoiceIdOk returns a tuple with the InvoiceId field value
// and a boolean to check if the value has been set.
func (o *InvoicePaymentStatusResponse) GetInvoiceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InvoiceId, true
}

// SetInvoiceId sets field value
func (o *InvoicePaymentStatusResponse) SetInvoiceId(v string) {
	o.InvoiceId = v
}

// GetBillingStatus returns the BillingStatus field value
func (o *InvoicePaymentStatusResponse) GetBillingStatus() InvoiceBillingStatus {
	if o == nil {
		var ret InvoiceBillingStatus
		return ret
	}

	return o.BillingStatus
}

// GetBillingStatusOk returns a tuple with the BillingStatus field value
// and a boolean to check if the value has been set.
func (o *InvoicePaymentStatusResponse) GetBillingStatusOk() (*InvoiceBillingStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BillingStatus, true
}

// SetBillingStatus sets field value
func (o *InvoicePaymentStatusResponse) SetBillingStatus(v InvoiceBillingStatus) {
	o.BillingStatus = v
}

// GetAmountDue returns the AmountDue field value
func (o *InvoicePaymentStatusResponse) GetAmountDue() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.AmountDue
}

// GetAmountDueOk returns a tuple with the AmountDue field value
// and a boolean to check if the value has been set.
func (o *InvoicePaymentStatusResponse) GetAmountDueOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AmountDue, true
}

// SetAmountDue sets field value
func (o *InvoicePaymentStatusResponse) SetAmountDue(v float32) {
	o.AmountDue = v
}

// GetAmountPaid returns the AmountPaid field value
func (o *InvoicePaymentStatusResponse) GetAmountPaid() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.AmountPaid
}

// GetAmountPaidOk returns a tuple with the AmountPaid field value
// and a boolean to check if the value has been set.
func (o *InvoicePaymentStatusResponse) GetAmountPaidOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AmountPaid, true
}

// SetAmountPaid sets field value
func (o *InvoicePaymentStatusResponse) SetAmountPaid(v float32) {
	o.AmountPaid = v
}

// GetTotal returns the Total field value
func (o *InvoicePaymentStatusResponse) GetTotal() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *InvoicePaymentStatusResponse) GetTotalOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *InvoicePaymentStatusResponse) SetTotal(v float32) {
	o.Total = v
}

// GetDueDate returns the DueDate field value if set, zero value otherwise.
func (o *InvoicePaymentStatusResponse) GetDueDate() time.Time {
	if o == nil || IsNil(o.DueDate) {
		var ret time.Time
		return ret
	}
	return *o.DueDate
}

// GetDueDateOk returns a tuple with the DueDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoicePaymentStatusResponse) GetDueDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DueDate) {
		return nil, false
	}
	return o.DueDate, true
}

// HasDueDate returns a boolean if a field has been set.
func (o *InvoicePaymentStatusResponse) HasDueDate() bool {
	if o != nil && !IsNil(o.DueDate) {
		return true
	}

	return false
}

// SetDueDate gets a reference to the given time.Time and assigns it to the DueDate field.
func (o *InvoicePaymentStatusResponse) SetDueDate(v time.Time) {
	o.DueDate = &v
}

// GetPaidAt returns the PaidAt field value if set, zero value otherwise.
func (o *InvoicePaymentStatusResponse) GetPaidAt() time.Time {
	if o == nil || IsNil(o.PaidAt) {
		var ret time.Time
		return ret
	}
	return *o.PaidAt
}

// GetPaidAtOk returns a tuple with the PaidAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoicePaymentStatusResponse) GetPaidAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.PaidAt) {
		return nil, false
	}
	return o.PaidAt, true
}

// HasPaidAt returns a boolean if a field has been set.
func (o *InvoicePaymentStatusResponse) HasPaidAt() bool {
	if o != nil && !IsNil(o.PaidAt) {
		return true
	}

	return false
}

// SetPaidAt gets a reference to the given time.Time and assigns it to the PaidAt field.
func (o *InvoicePaymentStatusResponse) SetPaidAt(v time.Time) {
	o.PaidAt = &v
}

// GetInvoicePdfUrl returns the InvoicePdfUrl field value if set, zero value otherwise.
func (o *InvoicePaymentStatusResponse) GetInvoicePdfUrl() string {
	if o == nil || IsNil(o.InvoicePdfUrl) {
		var ret string
		return ret
	}
	return *o.InvoicePdfUrl
}

// GetInvoicePdfUrlOk returns a tuple with the InvoicePdfUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoicePaymentStatusResponse) GetInvoicePdfUrlOk() (*string, bool) {
	if o == nil || IsNil(o.InvoicePdfUrl) {
		return nil, false
	}
	return o.InvoicePdfUrl, true
}

// HasInvoicePdfUrl returns a boolean if a field has been set.
func (o *InvoicePaymentStatusResponse) HasInvoicePdfUrl() bool {
	if o != nil && !IsNil(o.InvoicePdfUrl) {
		return true
	}

	return false
}

// SetInvoicePdfUrl gets a reference to the given string and assigns it to the InvoicePdfUrl field.
func (o *InvoicePaymentStatusResponse) SetInvoicePdfUrl(v string) {
	o.InvoicePdfUrl = &v
}

func (o InvoicePaymentStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InvoicePaymentStatusResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["invoiceId"] = o.InvoiceId
	toSerialize["billingStatus"] = o.BillingStatus
	toSerialize["amountDue"] = o.AmountDue
	toSerialize["amountPaid"] = o.AmountPaid
	toSerialize["total"] = o.Total
	if !IsNil(o.DueDate) {
		toSerialize["dueDate"] = o.DueDate
	}
	if !IsNil(o.PaidAt) {
		toSerialize["paidAt"] = o.PaidAt
	}
	if !IsNil(o.InvoicePdfUrl) {
		toSerialize["invoicePdfUrl"] = o.InvoicePdfUrl
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InvoicePaymentStatusResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"invoiceId",
		"billingStatus",
		"amountDue",
		"amountPaid",
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInvoicePaymentStatusResponse := _InvoicePaymentStatusResponse{}

	err = json.Unmarshal(data, &varInvoicePaymentStatusResponse)

	if err != nil {
		return err
	}

	*o = InvoicePaymentStatusResponse(varInvoicePaymentStatusResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "invoiceId")
		delete(additionalProperties, "billingStatus")
		delete(additionalProperties, "amountDue")
		delete(additionalProperties, "amountPaid")
		delete(additionalProperties, "total")
		delete(additionalProperties, "dueDate")
		delete(additionalProperties, "paidAt")
		delete(additionalProperties, "invoicePdfUrl")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInvoicePaymentStatusResponse struct {
	value *InvoicePaymentStatusResponse
	isSet bool
}

func (v NullableInvoicePaymentStatusResponse) Get() *InvoicePaymentStatusResponse {
	return v.value
}

func (v *NullableInvoicePaymentStatusResponse) Set(val *InvoicePaymentStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableInvoicePaymentStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableInvoicePaymentStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvoicePaymentStatusResponse(val *InvoicePaymentStatusResponse) *NullableInvoicePaymentStatusResponse {
	return &NullableInvoicePaymentStatusResponse{value: val, isSet: true}
}

func (v NullableInvoicePaymentStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvoicePaymentStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


