/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateCatalogProductResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCatalogProductResponse{}

// CreateCatalogProductResponse struct for CreateCatalogProductResponse
type CreateCatalogProductResponse struct {
	CatalogProduct CreateCatalogProductResponseCatalogProduct `json:"catalogProduct"`
	AdditionalProperties map[string]interface{}
}

type _CreateCatalogProductResponse CreateCatalogProductResponse

// NewCreateCatalogProductResponse instantiates a new CreateCatalogProductResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCatalogProductResponse(catalogProduct CreateCatalogProductResponseCatalogProduct) *CreateCatalogProductResponse {
	this := CreateCatalogProductResponse{}
	this.CatalogProduct = catalogProduct
	return &this
}

// NewCreateCatalogProductResponseWithDefaults instantiates a new CreateCatalogProductResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCatalogProductResponseWithDefaults() *CreateCatalogProductResponse {
	this := CreateCatalogProductResponse{}
	return &this
}

// GetCatalogProduct returns the CatalogProduct field value
func (o *CreateCatalogProductResponse) GetCatalogProduct() CreateCatalogProductResponseCatalogProduct {
	if o == nil {
		var ret CreateCatalogProductResponseCatalogProduct
		return ret
	}

	return o.CatalogProduct
}

// GetCatalogProductOk returns a tuple with the CatalogProduct field value
// and a boolean to check if the value has been set.
func (o *CreateCatalogProductResponse) GetCatalogProductOk() (*CreateCatalogProductResponseCatalogProduct, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CatalogProduct, true
}

// SetCatalogProduct sets field value
func (o *CreateCatalogProductResponse) SetCatalogProduct(v CreateCatalogProductResponseCatalogProduct) {
	o.CatalogProduct = v
}

func (o CreateCatalogProductResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCatalogProductResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["catalogProduct"] = o.CatalogProduct

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateCatalogProductResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"catalogProduct",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateCatalogProductResponse := _CreateCatalogProductResponse{}

	err = json.Unmarshal(data, &varCreateCatalogProductResponse)

	if err != nil {
		return err
	}

	*o = CreateCatalogProductResponse(varCreateCatalogProductResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "catalogProduct")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateCatalogProductResponse struct {
	value *CreateCatalogProductResponse
	isSet bool
}

func (v NullableCreateCatalogProductResponse) Get() *CreateCatalogProductResponse {
	return v.value
}

func (v *NullableCreateCatalogProductResponse) Set(val *CreateCatalogProductResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCatalogProductResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCatalogProductResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCatalogProductResponse(val *CreateCatalogProductResponse) *NullableCreateCatalogProductResponse {
	return &NullableCreateCatalogProductResponse{value: val, isSet: true}
}

func (v NullableCreateCatalogProductResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCatalogProductResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


