/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the DeleteMeasurementResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteMeasurementResponse{}

// DeleteMeasurementResponse struct for DeleteMeasurementResponse
type DeleteMeasurementResponse struct {
	Measurement DeleteMeasurementResponseMeasurement `json:"measurement"`
	AdditionalProperties map[string]interface{}
}

type _DeleteMeasurementResponse DeleteMeasurementResponse

// NewDeleteMeasurementResponse instantiates a new DeleteMeasurementResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteMeasurementResponse(measurement DeleteMeasurementResponseMeasurement) *DeleteMeasurementResponse {
	this := DeleteMeasurementResponse{}
	this.Measurement = measurement
	return &this
}

// NewDeleteMeasurementResponseWithDefaults instantiates a new DeleteMeasurementResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteMeasurementResponseWithDefaults() *DeleteMeasurementResponse {
	this := DeleteMeasurementResponse{}
	return &this
}

// GetMeasurement returns the Measurement field value
func (o *DeleteMeasurementResponse) GetMeasurement() DeleteMeasurementResponseMeasurement {
	if o == nil {
		var ret DeleteMeasurementResponseMeasurement
		return ret
	}

	return o.Measurement
}

// GetMeasurementOk returns a tuple with the Measurement field value
// and a boolean to check if the value has been set.
func (o *DeleteMeasurementResponse) GetMeasurementOk() (*DeleteMeasurementResponseMeasurement, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Measurement, true
}

// SetMeasurement sets field value
func (o *DeleteMeasurementResponse) SetMeasurement(v DeleteMeasurementResponseMeasurement) {
	o.Measurement = v
}

func (o DeleteMeasurementResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteMeasurementResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["measurement"] = o.Measurement

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DeleteMeasurementResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"measurement",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteMeasurementResponse := _DeleteMeasurementResponse{}

	err = json.Unmarshal(data, &varDeleteMeasurementResponse)

	if err != nil {
		return err
	}

	*o = DeleteMeasurementResponse(varDeleteMeasurementResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "measurement")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDeleteMeasurementResponse struct {
	value *DeleteMeasurementResponse
	isSet bool
}

func (v NullableDeleteMeasurementResponse) Get() *DeleteMeasurementResponse {
	return v.value
}

func (v *NullableDeleteMeasurementResponse) Set(val *DeleteMeasurementResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteMeasurementResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteMeasurementResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteMeasurementResponse(val *DeleteMeasurementResponse) *NullableDeleteMeasurementResponse {
	return &NullableDeleteMeasurementResponse{value: val, isSet: true}
}

func (v NullableDeleteMeasurementResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteMeasurementResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


