/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ValidationErrorResponseParamsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValidationErrorResponseParamsInner{}

// ValidationErrorResponseParamsInner struct for ValidationErrorResponseParamsInner
type ValidationErrorResponseParamsInner struct {
	// The parameter that failed validation
	Param string `json:"param"`
	// Why validation failed for this parameter
	Message string `json:"message"`
	AdditionalProperties map[string]interface{}
}

type _ValidationErrorResponseParamsInner ValidationErrorResponseParamsInner

// NewValidationErrorResponseParamsInner instantiates a new ValidationErrorResponseParamsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValidationErrorResponseParamsInner(param string, message string) *ValidationErrorResponseParamsInner {
	this := ValidationErrorResponseParamsInner{}
	this.Param = param
	this.Message = message
	return &this
}

// NewValidationErrorResponseParamsInnerWithDefaults instantiates a new ValidationErrorResponseParamsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValidationErrorResponseParamsInnerWithDefaults() *ValidationErrorResponseParamsInner {
	this := ValidationErrorResponseParamsInner{}
	return &this
}

// GetParam returns the Param field value
func (o *ValidationErrorResponseParamsInner) GetParam() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Param
}

// GetParamOk returns a tuple with the Param field value
// and a boolean to check if the value has been set.
func (o *ValidationErrorResponseParamsInner) GetParamOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Param, true
}

// SetParam sets field value
func (o *ValidationErrorResponseParamsInner) SetParam(v string) {
	o.Param = v
}

// GetMessage returns the Message field value
func (o *ValidationErrorResponseParamsInner) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ValidationErrorResponseParamsInner) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ValidationErrorResponseParamsInner) SetMessage(v string) {
	o.Message = v
}

func (o ValidationErrorResponseParamsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValidationErrorResponseParamsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["param"] = o.Param
	toSerialize["message"] = o.Message

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ValidationErrorResponseParamsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"param",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varValidationErrorResponseParamsInner := _ValidationErrorResponseParamsInner{}

	err = json.Unmarshal(data, &varValidationErrorResponseParamsInner)

	if err != nil {
		return err
	}

	*o = ValidationErrorResponseParamsInner(varValidationErrorResponseParamsInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "param")
		delete(additionalProperties, "message")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableValidationErrorResponseParamsInner struct {
	value *ValidationErrorResponseParamsInner
	isSet bool
}

func (v NullableValidationErrorResponseParamsInner) Get() *ValidationErrorResponseParamsInner {
	return v.value
}

func (v *NullableValidationErrorResponseParamsInner) Set(val *ValidationErrorResponseParamsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableValidationErrorResponseParamsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableValidationErrorResponseParamsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValidationErrorResponseParamsInner(val *ValidationErrorResponseParamsInner) *NullableValidationErrorResponseParamsInner {
	return &NullableValidationErrorResponseParamsInner{value: val, isSet: true}
}

func (v NullableValidationErrorResponseParamsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValidationErrorResponseParamsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


