/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the RefreshContractCreditsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RefreshContractCreditsResponse{}

// RefreshContractCreditsResponse struct for RefreshContractCreditsResponse
type RefreshContractCreditsResponse struct {
	// The identifier of the contract whose credit grants were refreshed
	ContractId string `json:"contractId" validate:"regexp=^[0-9a-fA-F]{24}$"`
	AdditionalProperties map[string]interface{}
}

type _RefreshContractCreditsResponse RefreshContractCreditsResponse

// NewRefreshContractCreditsResponse instantiates a new RefreshContractCreditsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRefreshContractCreditsResponse(contractId string) *RefreshContractCreditsResponse {
	this := RefreshContractCreditsResponse{}
	this.ContractId = contractId
	return &this
}

// NewRefreshContractCreditsResponseWithDefaults instantiates a new RefreshContractCreditsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRefreshContractCreditsResponseWithDefaults() *RefreshContractCreditsResponse {
	this := RefreshContractCreditsResponse{}
	return &this
}

// GetContractId returns the ContractId field value
func (o *RefreshContractCreditsResponse) GetContractId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContractId
}

// GetContractIdOk returns a tuple with the ContractId field value
// and a boolean to check if the value has been set.
func (o *RefreshContractCreditsResponse) GetContractIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContractId, true
}

// SetContractId sets field value
func (o *RefreshContractCreditsResponse) SetContractId(v string) {
	o.ContractId = v
}

func (o RefreshContractCreditsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RefreshContractCreditsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["contractId"] = o.ContractId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RefreshContractCreditsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"contractId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRefreshContractCreditsResponse := _RefreshContractCreditsResponse{}

	err = json.Unmarshal(data, &varRefreshContractCreditsResponse)

	if err != nil {
		return err
	}

	*o = RefreshContractCreditsResponse(varRefreshContractCreditsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "contractId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRefreshContractCreditsResponse struct {
	value *RefreshContractCreditsResponse
	isSet bool
}

func (v NullableRefreshContractCreditsResponse) Get() *RefreshContractCreditsResponse {
	return v.value
}

func (v *NullableRefreshContractCreditsResponse) Set(val *RefreshContractCreditsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRefreshContractCreditsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRefreshContractCreditsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRefreshContractCreditsResponse(val *RefreshContractCreditsResponse) *NullableRefreshContractCreditsResponse {
	return &NullableRefreshContractCreditsResponse{value: val, isSet: true}
}

func (v NullableRefreshContractCreditsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRefreshContractCreditsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


