/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)


// V2QueryEventsAggregationRequestMetersInnerFiltersInnerValue struct for V2QueryEventsAggregationRequestMetersInnerFiltersInnerValue
type V2QueryEventsAggregationRequestMetersInnerFiltersInnerValue struct {
	ArrayOfFloat32 *[]float32
	ArrayOfString *[]string
	Float32 *float32
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *V2QueryEventsAggregationRequestMetersInnerFiltersInnerValue) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into ArrayOfFloat32
	err = json.Unmarshal(data, &dst.ArrayOfFloat32);
	if err == nil {
		jsonArrayOfFloat32, _ := json.Marshal(dst.ArrayOfFloat32)
		if string(jsonArrayOfFloat32) == "{}" { // empty struct
			dst.ArrayOfFloat32 = nil
		} else {
			return nil // data stored in dst.ArrayOfFloat32, return on the first match
		}
	} else {
		dst.ArrayOfFloat32 = nil
	}

	// try to unmarshal JSON data into ArrayOfString
	err = json.Unmarshal(data, &dst.ArrayOfString);
	if err == nil {
		jsonArrayOfString, _ := json.Marshal(dst.ArrayOfString)
		if string(jsonArrayOfString) == "{}" { // empty struct
			dst.ArrayOfString = nil
		} else {
			return nil // data stored in dst.ArrayOfString, return on the first match
		}
	} else {
		dst.ArrayOfString = nil
	}

	// try to unmarshal JSON data into Float32
	err = json.Unmarshal(data, &dst.Float32);
	if err == nil {
		jsonFloat32, _ := json.Marshal(dst.Float32)
		if string(jsonFloat32) == "{}" { // empty struct
			dst.Float32 = nil
		} else {
			return nil // data stored in dst.Float32, return on the first match
		}
	} else {
		dst.Float32 = nil
	}

	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String);
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(V2QueryEventsAggregationRequestMetersInnerFiltersInnerValue)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src V2QueryEventsAggregationRequestMetersInnerFiltersInnerValue) MarshalJSON() ([]byte, error) {
	if src.ArrayOfFloat32 != nil {
		return json.Marshal(&src.ArrayOfFloat32)
	}

	if src.ArrayOfString != nil {
		return json.Marshal(&src.ArrayOfString)
	}

	if src.Float32 != nil {
		return json.Marshal(&src.Float32)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableV2QueryEventsAggregationRequestMetersInnerFiltersInnerValue struct {
	value *V2QueryEventsAggregationRequestMetersInnerFiltersInnerValue
	isSet bool
}

func (v NullableV2QueryEventsAggregationRequestMetersInnerFiltersInnerValue) Get() *V2QueryEventsAggregationRequestMetersInnerFiltersInnerValue {
	return v.value
}

func (v *NullableV2QueryEventsAggregationRequestMetersInnerFiltersInnerValue) Set(val *V2QueryEventsAggregationRequestMetersInnerFiltersInnerValue) {
	v.value = val
	v.isSet = true
}

func (v NullableV2QueryEventsAggregationRequestMetersInnerFiltersInnerValue) IsSet() bool {
	return v.isSet
}

func (v *NullableV2QueryEventsAggregationRequestMetersInnerFiltersInnerValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2QueryEventsAggregationRequestMetersInnerFiltersInnerValue(val *V2QueryEventsAggregationRequestMetersInnerFiltersInnerValue) *NullableV2QueryEventsAggregationRequestMetersInnerFiltersInnerValue {
	return &NullableV2QueryEventsAggregationRequestMetersInnerFiltersInnerValue{value: val, isSet: true}
}

func (v NullableV2QueryEventsAggregationRequestMetersInnerFiltersInnerValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2QueryEventsAggregationRequestMetersInnerFiltersInnerValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


