/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the V2QueryEventsAggregationRequestMetersInnerAggregation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2QueryEventsAggregationRequestMetersInnerAggregation{}

// V2QueryEventsAggregationRequestMetersInnerAggregation struct for V2QueryEventsAggregationRequestMetersInnerAggregation
type V2QueryEventsAggregationRequestMetersInnerAggregation struct {
	Operator AggregationOperator `json:"operator"`
	Field *string `json:"field,omitempty"`
	FieldArithmetic *V2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic `json:"fieldArithmetic,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _V2QueryEventsAggregationRequestMetersInnerAggregation V2QueryEventsAggregationRequestMetersInnerAggregation

// NewV2QueryEventsAggregationRequestMetersInnerAggregation instantiates a new V2QueryEventsAggregationRequestMetersInnerAggregation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2QueryEventsAggregationRequestMetersInnerAggregation(operator AggregationOperator) *V2QueryEventsAggregationRequestMetersInnerAggregation {
	this := V2QueryEventsAggregationRequestMetersInnerAggregation{}
	this.Operator = operator
	return &this
}

// NewV2QueryEventsAggregationRequestMetersInnerAggregationWithDefaults instantiates a new V2QueryEventsAggregationRequestMetersInnerAggregation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2QueryEventsAggregationRequestMetersInnerAggregationWithDefaults() *V2QueryEventsAggregationRequestMetersInnerAggregation {
	this := V2QueryEventsAggregationRequestMetersInnerAggregation{}
	return &this
}

// GetOperator returns the Operator field value
func (o *V2QueryEventsAggregationRequestMetersInnerAggregation) GetOperator() AggregationOperator {
	if o == nil {
		var ret AggregationOperator
		return ret
	}

	return o.Operator
}

// GetOperatorOk returns a tuple with the Operator field value
// and a boolean to check if the value has been set.
func (o *V2QueryEventsAggregationRequestMetersInnerAggregation) GetOperatorOk() (*AggregationOperator, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Operator, true
}

// SetOperator sets field value
func (o *V2QueryEventsAggregationRequestMetersInnerAggregation) SetOperator(v AggregationOperator) {
	o.Operator = v
}

// GetField returns the Field field value if set, zero value otherwise.
func (o *V2QueryEventsAggregationRequestMetersInnerAggregation) GetField() string {
	if o == nil || IsNil(o.Field) {
		var ret string
		return ret
	}
	return *o.Field
}

// GetFieldOk returns a tuple with the Field field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2QueryEventsAggregationRequestMetersInnerAggregation) GetFieldOk() (*string, bool) {
	if o == nil || IsNil(o.Field) {
		return nil, false
	}
	return o.Field, true
}

// HasField returns a boolean if a field has been set.
func (o *V2QueryEventsAggregationRequestMetersInnerAggregation) HasField() bool {
	if o != nil && !IsNil(o.Field) {
		return true
	}

	return false
}

// SetField gets a reference to the given string and assigns it to the Field field.
func (o *V2QueryEventsAggregationRequestMetersInnerAggregation) SetField(v string) {
	o.Field = &v
}

// GetFieldArithmetic returns the FieldArithmetic field value if set, zero value otherwise.
func (o *V2QueryEventsAggregationRequestMetersInnerAggregation) GetFieldArithmetic() V2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic {
	if o == nil || IsNil(o.FieldArithmetic) {
		var ret V2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic
		return ret
	}
	return *o.FieldArithmetic
}

// GetFieldArithmeticOk returns a tuple with the FieldArithmetic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2QueryEventsAggregationRequestMetersInnerAggregation) GetFieldArithmeticOk() (*V2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic, bool) {
	if o == nil || IsNil(o.FieldArithmetic) {
		return nil, false
	}
	return o.FieldArithmetic, true
}

// HasFieldArithmetic returns a boolean if a field has been set.
func (o *V2QueryEventsAggregationRequestMetersInnerAggregation) HasFieldArithmetic() bool {
	if o != nil && !IsNil(o.FieldArithmetic) {
		return true
	}

	return false
}

// SetFieldArithmetic gets a reference to the given V2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic and assigns it to the FieldArithmetic field.
func (o *V2QueryEventsAggregationRequestMetersInnerAggregation) SetFieldArithmetic(v V2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic) {
	o.FieldArithmetic = &v
}

func (o V2QueryEventsAggregationRequestMetersInnerAggregation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2QueryEventsAggregationRequestMetersInnerAggregation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["operator"] = o.Operator
	if !IsNil(o.Field) {
		toSerialize["field"] = o.Field
	}
	if !IsNil(o.FieldArithmetic) {
		toSerialize["fieldArithmetic"] = o.FieldArithmetic
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *V2QueryEventsAggregationRequestMetersInnerAggregation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"operator",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV2QueryEventsAggregationRequestMetersInnerAggregation := _V2QueryEventsAggregationRequestMetersInnerAggregation{}

	err = json.Unmarshal(data, &varV2QueryEventsAggregationRequestMetersInnerAggregation)

	if err != nil {
		return err
	}

	*o = V2QueryEventsAggregationRequestMetersInnerAggregation(varV2QueryEventsAggregationRequestMetersInnerAggregation)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "operator")
		delete(additionalProperties, "field")
		delete(additionalProperties, "fieldArithmetic")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableV2QueryEventsAggregationRequestMetersInnerAggregation struct {
	value *V2QueryEventsAggregationRequestMetersInnerAggregation
	isSet bool
}

func (v NullableV2QueryEventsAggregationRequestMetersInnerAggregation) Get() *V2QueryEventsAggregationRequestMetersInnerAggregation {
	return v.value
}

func (v *NullableV2QueryEventsAggregationRequestMetersInnerAggregation) Set(val *V2QueryEventsAggregationRequestMetersInnerAggregation) {
	v.value = val
	v.isSet = true
}

func (v NullableV2QueryEventsAggregationRequestMetersInnerAggregation) IsSet() bool {
	return v.isSet
}

func (v *NullableV2QueryEventsAggregationRequestMetersInnerAggregation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2QueryEventsAggregationRequestMetersInnerAggregation(val *V2QueryEventsAggregationRequestMetersInnerAggregation) *NullableV2QueryEventsAggregationRequestMetersInnerAggregation {
	return &NullableV2QueryEventsAggregationRequestMetersInnerAggregation{value: val, isSet: true}
}

func (v NullableV2QueryEventsAggregationRequestMetersInnerAggregation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2QueryEventsAggregationRequestMetersInnerAggregation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


