/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the V2DeleteEventResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2DeleteEventResponse{}

// V2DeleteEventResponse struct for V2DeleteEventResponse
type V2DeleteEventResponse struct {
	Event DeleteEventResponseEvent `json:"event"`
	AdditionalProperties map[string]interface{}
}

type _V2DeleteEventResponse V2DeleteEventResponse

// NewV2DeleteEventResponse instantiates a new V2DeleteEventResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2DeleteEventResponse(event DeleteEventResponseEvent) *V2DeleteEventResponse {
	this := V2DeleteEventResponse{}
	this.Event = event
	return &this
}

// NewV2DeleteEventResponseWithDefaults instantiates a new V2DeleteEventResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2DeleteEventResponseWithDefaults() *V2DeleteEventResponse {
	this := V2DeleteEventResponse{}
	return &this
}

// GetEvent returns the Event field value
func (o *V2DeleteEventResponse) GetEvent() DeleteEventResponseEvent {
	if o == nil {
		var ret DeleteEventResponseEvent
		return ret
	}

	return o.Event
}

// GetEventOk returns a tuple with the Event field value
// and a boolean to check if the value has been set.
func (o *V2DeleteEventResponse) GetEventOk() (*DeleteEventResponseEvent, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Event, true
}

// SetEvent sets field value
func (o *V2DeleteEventResponse) SetEvent(v DeleteEventResponseEvent) {
	o.Event = v
}

func (o V2DeleteEventResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2DeleteEventResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["event"] = o.Event

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *V2DeleteEventResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"event",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV2DeleteEventResponse := _V2DeleteEventResponse{}

	err = json.Unmarshal(data, &varV2DeleteEventResponse)

	if err != nil {
		return err
	}

	*o = V2DeleteEventResponse(varV2DeleteEventResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "event")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableV2DeleteEventResponse struct {
	value *V2DeleteEventResponse
	isSet bool
}

func (v NullableV2DeleteEventResponse) Get() *V2DeleteEventResponse {
	return v.value
}

func (v *NullableV2DeleteEventResponse) Set(val *V2DeleteEventResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV2DeleteEventResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV2DeleteEventResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2DeleteEventResponse(val *V2DeleteEventResponse) *NullableV2DeleteEventResponse {
	return &NullableV2DeleteEventResponse{value: val, isSet: true}
}

func (v NullableV2DeleteEventResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2DeleteEventResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


