/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the UpdateCustomFieldResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateCustomFieldResponse{}

// UpdateCustomFieldResponse struct for UpdateCustomFieldResponse
type UpdateCustomFieldResponse struct {
	CustomField CreateCustomFieldResponseCustomField `json:"customField"`
	AdditionalProperties map[string]interface{}
}

type _UpdateCustomFieldResponse UpdateCustomFieldResponse

// NewUpdateCustomFieldResponse instantiates a new UpdateCustomFieldResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateCustomFieldResponse(customField CreateCustomFieldResponseCustomField) *UpdateCustomFieldResponse {
	this := UpdateCustomFieldResponse{}
	this.CustomField = customField
	return &this
}

// NewUpdateCustomFieldResponseWithDefaults instantiates a new UpdateCustomFieldResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateCustomFieldResponseWithDefaults() *UpdateCustomFieldResponse {
	this := UpdateCustomFieldResponse{}
	return &this
}

// GetCustomField returns the CustomField field value
func (o *UpdateCustomFieldResponse) GetCustomField() CreateCustomFieldResponseCustomField {
	if o == nil {
		var ret CreateCustomFieldResponseCustomField
		return ret
	}

	return o.CustomField
}

// GetCustomFieldOk returns a tuple with the CustomField field value
// and a boolean to check if the value has been set.
func (o *UpdateCustomFieldResponse) GetCustomFieldOk() (*CreateCustomFieldResponseCustomField, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomField, true
}

// SetCustomField sets field value
func (o *UpdateCustomFieldResponse) SetCustomField(v CreateCustomFieldResponseCustomField) {
	o.CustomField = v
}

func (o UpdateCustomFieldResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateCustomFieldResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["customField"] = o.CustomField

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateCustomFieldResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"customField",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateCustomFieldResponse := _UpdateCustomFieldResponse{}

	err = json.Unmarshal(data, &varUpdateCustomFieldResponse)

	if err != nil {
		return err
	}

	*o = UpdateCustomFieldResponse(varUpdateCustomFieldResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "customField")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateCustomFieldResponse struct {
	value *UpdateCustomFieldResponse
	isSet bool
}

func (v NullableUpdateCustomFieldResponse) Get() *UpdateCustomFieldResponse {
	return v.value
}

func (v *NullableUpdateCustomFieldResponse) Set(val *UpdateCustomFieldResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateCustomFieldResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateCustomFieldResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateCustomFieldResponse(val *UpdateCustomFieldResponse) *NullableUpdateCustomFieldResponse {
	return &NullableUpdateCustomFieldResponse{value: val, isSet: true}
}

func (v NullableUpdateCustomFieldResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateCustomFieldResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


