/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// IntegrationEntityTypes The entity type in the integration (e.g., \"Opportunity\", \"Deal\")
type IntegrationEntityTypes string

// List of IntegrationEntityTypes
const (
	INTEGRATIONENTITYTYPES_ACCOUNT IntegrationEntityTypes = "Account"
	INTEGRATIONENTITYTYPES_INVOICE IntegrationEntityTypes = "Invoice"
	INTEGRATIONENTITYTYPES_SALES_ORDER IntegrationEntityTypes = "SalesOrder"
	INTEGRATIONENTITYTYPES_ITEM IntegrationEntityTypes = "Item"
	INTEGRATIONENTITYTYPES_DEAL IntegrationEntityTypes = "Deal"
	INTEGRATIONENTITYTYPES_COMPANY IntegrationEntityTypes = "Company"
	INTEGRATIONENTITYTYPES_OPPORTUNITY IntegrationEntityTypes = "Opportunity"
)

// All allowed values of IntegrationEntityTypes enum
var AllowedIntegrationEntityTypesEnumValues = []IntegrationEntityTypes{
	"Account",
	"Invoice",
	"SalesOrder",
	"Item",
	"Deal",
	"Company",
	"Opportunity",
}

func (v *IntegrationEntityTypes) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := IntegrationEntityTypes(value)
	for _, existing := range AllowedIntegrationEntityTypesEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid IntegrationEntityTypes", value)
}

// NewIntegrationEntityTypesFromValue returns a pointer to a valid IntegrationEntityTypes
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewIntegrationEntityTypesFromValue(v string) (*IntegrationEntityTypes, error) {
	ev := IntegrationEntityTypes(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for IntegrationEntityTypes: valid values are %v", v, AllowedIntegrationEntityTypesEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v IntegrationEntityTypes) IsValid() bool {
	for _, existing := range AllowedIntegrationEntityTypesEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to IntegrationEntityTypes value
func (v IntegrationEntityTypes) Ptr() *IntegrationEntityTypes {
	return &v
}

type NullableIntegrationEntityTypes struct {
	value *IntegrationEntityTypes
	isSet bool
}

func (v NullableIntegrationEntityTypes) Get() *IntegrationEntityTypes {
	return v.value
}

func (v *NullableIntegrationEntityTypes) Set(val *IntegrationEntityTypes) {
	v.value = val
	v.isSet = true
}

func (v NullableIntegrationEntityTypes) IsSet() bool {
	return v.isSet
}

func (v *NullableIntegrationEntityTypes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntegrationEntityTypes(val *IntegrationEntityTypes) *NullableIntegrationEntityTypes {
	return &NullableIntegrationEntityTypes{value: val, isSet: true}
}

func (v NullableIntegrationEntityTypes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntegrationEntityTypes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

