/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// CustomFieldEntities The Vayu entity this field applies to
type CustomFieldEntities string

// List of CustomFieldEntities
const (
	CUSTOMFIELDENTITIES_CUSTOMER CustomFieldEntities = "Customer"
	CUSTOMFIELDENTITIES_CONTRACT CustomFieldEntities = "Contract"
	CUSTOMFIELDENTITIES_INVOICE CustomFieldEntities = "Invoice"
	CUSTOMFIELDENTITIES_LINE_ITEM CustomFieldEntities = "LineItem"
)

// All allowed values of CustomFieldEntities enum
var AllowedCustomFieldEntitiesEnumValues = []CustomFieldEntities{
	"Customer",
	"Contract",
	"Invoice",
	"LineItem",
}

func (v *CustomFieldEntities) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CustomFieldEntities(value)
	for _, existing := range AllowedCustomFieldEntitiesEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CustomFieldEntities", value)
}

// NewCustomFieldEntitiesFromValue returns a pointer to a valid CustomFieldEntities
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCustomFieldEntitiesFromValue(v string) (*CustomFieldEntities, error) {
	ev := CustomFieldEntities(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CustomFieldEntities: valid values are %v", v, AllowedCustomFieldEntitiesEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CustomFieldEntities) IsValid() bool {
	for _, existing := range AllowedCustomFieldEntitiesEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CustomFieldEntities value
func (v CustomFieldEntities) Ptr() *CustomFieldEntities {
	return &v
}

type NullableCustomFieldEntities struct {
	value *CustomFieldEntities
	isSet bool
}

func (v NullableCustomFieldEntities) Get() *CustomFieldEntities {
	return v.value
}

func (v *NullableCustomFieldEntities) Set(val *CustomFieldEntities) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomFieldEntities) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomFieldEntities) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomFieldEntities(val *CustomFieldEntities) *NullableCustomFieldEntities {
	return &NullableCustomFieldEntities{value: val, isSet: true}
}

func (v NullableCustomFieldEntities) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomFieldEntities) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

