/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ProductGroupProductsInnerPricingOneOf3 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductGroupProductsInnerPricingOneOf3{}

// ProductGroupProductsInnerPricingOneOf3 struct for ProductGroupProductsInnerPricingOneOf3
type ProductGroupProductsInnerPricingOneOf3 struct {
	Type string `json:"type"`
	Tiers []ProductGroupProductsInnerPricingOneOf3TiersInner `json:"tiers"`
	SubscriptionCadence NullableProductGroupProductsInnerPricingOneOf3SubscriptionCadence `json:"subscriptionCadence,omitempty"`
	AutoUpgrade NullableBool `json:"autoUpgrade,omitempty"`
	Prorate NullableBool `json:"prorate,omitempty"`
	IsRevShare NullableBool `json:"isRevShare,omitempty"`
	BaseAmount NullableFloat32 `json:"baseAmount,omitempty"`
	// Usage reset is represented in months and must be one of: 1, 2, 3, 6, 12
	UsageReset NullableInt32 `json:"usageReset,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ProductGroupProductsInnerPricingOneOf3 ProductGroupProductsInnerPricingOneOf3

// NewProductGroupProductsInnerPricingOneOf3 instantiates a new ProductGroupProductsInnerPricingOneOf3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductGroupProductsInnerPricingOneOf3(type_ string, tiers []ProductGroupProductsInnerPricingOneOf3TiersInner) *ProductGroupProductsInnerPricingOneOf3 {
	this := ProductGroupProductsInnerPricingOneOf3{}
	this.Type = type_
	this.Tiers = tiers
	return &this
}

// NewProductGroupProductsInnerPricingOneOf3WithDefaults instantiates a new ProductGroupProductsInnerPricingOneOf3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductGroupProductsInnerPricingOneOf3WithDefaults() *ProductGroupProductsInnerPricingOneOf3 {
	this := ProductGroupProductsInnerPricingOneOf3{}
	return &this
}

// GetType returns the Type field value
func (o *ProductGroupProductsInnerPricingOneOf3) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ProductGroupProductsInnerPricingOneOf3) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ProductGroupProductsInnerPricingOneOf3) SetType(v string) {
	o.Type = v
}

// GetTiers returns the Tiers field value
func (o *ProductGroupProductsInnerPricingOneOf3) GetTiers() []ProductGroupProductsInnerPricingOneOf3TiersInner {
	if o == nil {
		var ret []ProductGroupProductsInnerPricingOneOf3TiersInner
		return ret
	}

	return o.Tiers
}

// GetTiersOk returns a tuple with the Tiers field value
// and a boolean to check if the value has been set.
func (o *ProductGroupProductsInnerPricingOneOf3) GetTiersOk() ([]ProductGroupProductsInnerPricingOneOf3TiersInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tiers, true
}

// SetTiers sets field value
func (o *ProductGroupProductsInnerPricingOneOf3) SetTiers(v []ProductGroupProductsInnerPricingOneOf3TiersInner) {
	o.Tiers = v
}

// GetSubscriptionCadence returns the SubscriptionCadence field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProductGroupProductsInnerPricingOneOf3) GetSubscriptionCadence() ProductGroupProductsInnerPricingOneOf3SubscriptionCadence {
	if o == nil || IsNil(o.SubscriptionCadence.Get()) {
		var ret ProductGroupProductsInnerPricingOneOf3SubscriptionCadence
		return ret
	}
	return *o.SubscriptionCadence.Get()
}

// GetSubscriptionCadenceOk returns a tuple with the SubscriptionCadence field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductGroupProductsInnerPricingOneOf3) GetSubscriptionCadenceOk() (*ProductGroupProductsInnerPricingOneOf3SubscriptionCadence, bool) {
	if o == nil {
		return nil, false
	}
	return o.SubscriptionCadence.Get(), o.SubscriptionCadence.IsSet()
}

// HasSubscriptionCadence returns a boolean if a field has been set.
func (o *ProductGroupProductsInnerPricingOneOf3) HasSubscriptionCadence() bool {
	if o != nil && o.SubscriptionCadence.IsSet() {
		return true
	}

	return false
}

// SetSubscriptionCadence gets a reference to the given NullableProductGroupProductsInnerPricingOneOf3SubscriptionCadence and assigns it to the SubscriptionCadence field.
func (o *ProductGroupProductsInnerPricingOneOf3) SetSubscriptionCadence(v ProductGroupProductsInnerPricingOneOf3SubscriptionCadence) {
	o.SubscriptionCadence.Set(&v)
}
// SetSubscriptionCadenceNil sets the value for SubscriptionCadence to be an explicit nil
func (o *ProductGroupProductsInnerPricingOneOf3) SetSubscriptionCadenceNil() {
	o.SubscriptionCadence.Set(nil)
}

// UnsetSubscriptionCadence ensures that no value is present for SubscriptionCadence, not even an explicit nil
func (o *ProductGroupProductsInnerPricingOneOf3) UnsetSubscriptionCadence() {
	o.SubscriptionCadence.Unset()
}

// GetAutoUpgrade returns the AutoUpgrade field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProductGroupProductsInnerPricingOneOf3) GetAutoUpgrade() bool {
	if o == nil || IsNil(o.AutoUpgrade.Get()) {
		var ret bool
		return ret
	}
	return *o.AutoUpgrade.Get()
}

// GetAutoUpgradeOk returns a tuple with the AutoUpgrade field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductGroupProductsInnerPricingOneOf3) GetAutoUpgradeOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.AutoUpgrade.Get(), o.AutoUpgrade.IsSet()
}

// HasAutoUpgrade returns a boolean if a field has been set.
func (o *ProductGroupProductsInnerPricingOneOf3) HasAutoUpgrade() bool {
	if o != nil && o.AutoUpgrade.IsSet() {
		return true
	}

	return false
}

// SetAutoUpgrade gets a reference to the given NullableBool and assigns it to the AutoUpgrade field.
func (o *ProductGroupProductsInnerPricingOneOf3) SetAutoUpgrade(v bool) {
	o.AutoUpgrade.Set(&v)
}
// SetAutoUpgradeNil sets the value for AutoUpgrade to be an explicit nil
func (o *ProductGroupProductsInnerPricingOneOf3) SetAutoUpgradeNil() {
	o.AutoUpgrade.Set(nil)
}

// UnsetAutoUpgrade ensures that no value is present for AutoUpgrade, not even an explicit nil
func (o *ProductGroupProductsInnerPricingOneOf3) UnsetAutoUpgrade() {
	o.AutoUpgrade.Unset()
}

// GetProrate returns the Prorate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProductGroupProductsInnerPricingOneOf3) GetProrate() bool {
	if o == nil || IsNil(o.Prorate.Get()) {
		var ret bool
		return ret
	}
	return *o.Prorate.Get()
}

// GetProrateOk returns a tuple with the Prorate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductGroupProductsInnerPricingOneOf3) GetProrateOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Prorate.Get(), o.Prorate.IsSet()
}

// HasProrate returns a boolean if a field has been set.
func (o *ProductGroupProductsInnerPricingOneOf3) HasProrate() bool {
	if o != nil && o.Prorate.IsSet() {
		return true
	}

	return false
}

// SetProrate gets a reference to the given NullableBool and assigns it to the Prorate field.
func (o *ProductGroupProductsInnerPricingOneOf3) SetProrate(v bool) {
	o.Prorate.Set(&v)
}
// SetProrateNil sets the value for Prorate to be an explicit nil
func (o *ProductGroupProductsInnerPricingOneOf3) SetProrateNil() {
	o.Prorate.Set(nil)
}

// UnsetProrate ensures that no value is present for Prorate, not even an explicit nil
func (o *ProductGroupProductsInnerPricingOneOf3) UnsetProrate() {
	o.Prorate.Unset()
}

// GetIsRevShare returns the IsRevShare field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProductGroupProductsInnerPricingOneOf3) GetIsRevShare() bool {
	if o == nil || IsNil(o.IsRevShare.Get()) {
		var ret bool
		return ret
	}
	return *o.IsRevShare.Get()
}

// GetIsRevShareOk returns a tuple with the IsRevShare field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductGroupProductsInnerPricingOneOf3) GetIsRevShareOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsRevShare.Get(), o.IsRevShare.IsSet()
}

// HasIsRevShare returns a boolean if a field has been set.
func (o *ProductGroupProductsInnerPricingOneOf3) HasIsRevShare() bool {
	if o != nil && o.IsRevShare.IsSet() {
		return true
	}

	return false
}

// SetIsRevShare gets a reference to the given NullableBool and assigns it to the IsRevShare field.
func (o *ProductGroupProductsInnerPricingOneOf3) SetIsRevShare(v bool) {
	o.IsRevShare.Set(&v)
}
// SetIsRevShareNil sets the value for IsRevShare to be an explicit nil
func (o *ProductGroupProductsInnerPricingOneOf3) SetIsRevShareNil() {
	o.IsRevShare.Set(nil)
}

// UnsetIsRevShare ensures that no value is present for IsRevShare, not even an explicit nil
func (o *ProductGroupProductsInnerPricingOneOf3) UnsetIsRevShare() {
	o.IsRevShare.Unset()
}

// GetBaseAmount returns the BaseAmount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProductGroupProductsInnerPricingOneOf3) GetBaseAmount() float32 {
	if o == nil || IsNil(o.BaseAmount.Get()) {
		var ret float32
		return ret
	}
	return *o.BaseAmount.Get()
}

// GetBaseAmountOk returns a tuple with the BaseAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductGroupProductsInnerPricingOneOf3) GetBaseAmountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.BaseAmount.Get(), o.BaseAmount.IsSet()
}

// HasBaseAmount returns a boolean if a field has been set.
func (o *ProductGroupProductsInnerPricingOneOf3) HasBaseAmount() bool {
	if o != nil && o.BaseAmount.IsSet() {
		return true
	}

	return false
}

// SetBaseAmount gets a reference to the given NullableFloat32 and assigns it to the BaseAmount field.
func (o *ProductGroupProductsInnerPricingOneOf3) SetBaseAmount(v float32) {
	o.BaseAmount.Set(&v)
}
// SetBaseAmountNil sets the value for BaseAmount to be an explicit nil
func (o *ProductGroupProductsInnerPricingOneOf3) SetBaseAmountNil() {
	o.BaseAmount.Set(nil)
}

// UnsetBaseAmount ensures that no value is present for BaseAmount, not even an explicit nil
func (o *ProductGroupProductsInnerPricingOneOf3) UnsetBaseAmount() {
	o.BaseAmount.Unset()
}

// GetUsageReset returns the UsageReset field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProductGroupProductsInnerPricingOneOf3) GetUsageReset() int32 {
	if o == nil || IsNil(o.UsageReset.Get()) {
		var ret int32
		return ret
	}
	return *o.UsageReset.Get()
}

// GetUsageResetOk returns a tuple with the UsageReset field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductGroupProductsInnerPricingOneOf3) GetUsageResetOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.UsageReset.Get(), o.UsageReset.IsSet()
}

// HasUsageReset returns a boolean if a field has been set.
func (o *ProductGroupProductsInnerPricingOneOf3) HasUsageReset() bool {
	if o != nil && o.UsageReset.IsSet() {
		return true
	}

	return false
}

// SetUsageReset gets a reference to the given NullableInt32 and assigns it to the UsageReset field.
func (o *ProductGroupProductsInnerPricingOneOf3) SetUsageReset(v int32) {
	o.UsageReset.Set(&v)
}
// SetUsageResetNil sets the value for UsageReset to be an explicit nil
func (o *ProductGroupProductsInnerPricingOneOf3) SetUsageResetNil() {
	o.UsageReset.Set(nil)
}

// UnsetUsageReset ensures that no value is present for UsageReset, not even an explicit nil
func (o *ProductGroupProductsInnerPricingOneOf3) UnsetUsageReset() {
	o.UsageReset.Unset()
}

func (o ProductGroupProductsInnerPricingOneOf3) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductGroupProductsInnerPricingOneOf3) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["tiers"] = o.Tiers
	if o.SubscriptionCadence.IsSet() {
		toSerialize["subscriptionCadence"] = o.SubscriptionCadence.Get()
	}
	if o.AutoUpgrade.IsSet() {
		toSerialize["autoUpgrade"] = o.AutoUpgrade.Get()
	}
	if o.Prorate.IsSet() {
		toSerialize["prorate"] = o.Prorate.Get()
	}
	if o.IsRevShare.IsSet() {
		toSerialize["isRevShare"] = o.IsRevShare.Get()
	}
	if o.BaseAmount.IsSet() {
		toSerialize["baseAmount"] = o.BaseAmount.Get()
	}
	if o.UsageReset.IsSet() {
		toSerialize["usageReset"] = o.UsageReset.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProductGroupProductsInnerPricingOneOf3) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"tiers",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProductGroupProductsInnerPricingOneOf3 := _ProductGroupProductsInnerPricingOneOf3{}

	err = json.Unmarshal(data, &varProductGroupProductsInnerPricingOneOf3)

	if err != nil {
		return err
	}

	*o = ProductGroupProductsInnerPricingOneOf3(varProductGroupProductsInnerPricingOneOf3)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "tiers")
		delete(additionalProperties, "subscriptionCadence")
		delete(additionalProperties, "autoUpgrade")
		delete(additionalProperties, "prorate")
		delete(additionalProperties, "isRevShare")
		delete(additionalProperties, "baseAmount")
		delete(additionalProperties, "usageReset")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableProductGroupProductsInnerPricingOneOf3 struct {
	value *ProductGroupProductsInnerPricingOneOf3
	isSet bool
}

func (v NullableProductGroupProductsInnerPricingOneOf3) Get() *ProductGroupProductsInnerPricingOneOf3 {
	return v.value
}

func (v *NullableProductGroupProductsInnerPricingOneOf3) Set(val *ProductGroupProductsInnerPricingOneOf3) {
	v.value = val
	v.isSet = true
}

func (v NullableProductGroupProductsInnerPricingOneOf3) IsSet() bool {
	return v.isSet
}

func (v *NullableProductGroupProductsInnerPricingOneOf3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductGroupProductsInnerPricingOneOf3(val *ProductGroupProductsInnerPricingOneOf3) *NullableProductGroupProductsInnerPricingOneOf3 {
	return &NullableProductGroupProductsInnerPricingOneOf3{value: val, isSet: true}
}

func (v NullableProductGroupProductsInnerPricingOneOf3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductGroupProductsInnerPricingOneOf3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


