/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the DeleteCustomFieldResponseCustomField type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteCustomFieldResponseCustomField{}

// DeleteCustomFieldResponseCustomField struct for DeleteCustomFieldResponseCustomField
type DeleteCustomFieldResponseCustomField struct {
	VayuEntity CustomFieldEntities `json:"vayuEntity"`
	// The name of the custom field in Vayu
	VayuCustomFieldName string `json:"vayuCustomFieldName"`
	ValueType CustomFieldValueTypes `json:"valueType"`
	// The integration provider (e.g., \"Salesforce\", \"HubSpot\")
	IntegrationSource *string `json:"integrationSource,omitempty"`
	IntegrationEntityType *IntegrationEntityTypes `json:"integrationEntityType,omitempty"`
	// The path to the field in the integration
	FieldPath *string `json:"fieldPath,omitempty"`
	// Allowed values for Enum type fields
	AllowedValues []string `json:"allowedValues,omitempty"`
	// Default value for Enum type fields. Must be one of allowedValues.
	DefaultValue *string `json:"defaultValue,omitempty"`
	Id string `json:"id"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	DeletedAt string `json:"deletedAt"`
	AdditionalProperties map[string]interface{}
}

type _DeleteCustomFieldResponseCustomField DeleteCustomFieldResponseCustomField

// NewDeleteCustomFieldResponseCustomField instantiates a new DeleteCustomFieldResponseCustomField object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteCustomFieldResponseCustomField(vayuEntity CustomFieldEntities, vayuCustomFieldName string, valueType CustomFieldValueTypes, id string, createdAt time.Time, updatedAt time.Time, deletedAt string) *DeleteCustomFieldResponseCustomField {
	this := DeleteCustomFieldResponseCustomField{}
	this.VayuEntity = vayuEntity
	this.VayuCustomFieldName = vayuCustomFieldName
	this.ValueType = valueType
	this.Id = id
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.DeletedAt = deletedAt
	return &this
}

// NewDeleteCustomFieldResponseCustomFieldWithDefaults instantiates a new DeleteCustomFieldResponseCustomField object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteCustomFieldResponseCustomFieldWithDefaults() *DeleteCustomFieldResponseCustomField {
	this := DeleteCustomFieldResponseCustomField{}
	return &this
}

// GetVayuEntity returns the VayuEntity field value
func (o *DeleteCustomFieldResponseCustomField) GetVayuEntity() CustomFieldEntities {
	if o == nil {
		var ret CustomFieldEntities
		return ret
	}

	return o.VayuEntity
}

// GetVayuEntityOk returns a tuple with the VayuEntity field value
// and a boolean to check if the value has been set.
func (o *DeleteCustomFieldResponseCustomField) GetVayuEntityOk() (*CustomFieldEntities, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VayuEntity, true
}

// SetVayuEntity sets field value
func (o *DeleteCustomFieldResponseCustomField) SetVayuEntity(v CustomFieldEntities) {
	o.VayuEntity = v
}

// GetVayuCustomFieldName returns the VayuCustomFieldName field value
func (o *DeleteCustomFieldResponseCustomField) GetVayuCustomFieldName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VayuCustomFieldName
}

// GetVayuCustomFieldNameOk returns a tuple with the VayuCustomFieldName field value
// and a boolean to check if the value has been set.
func (o *DeleteCustomFieldResponseCustomField) GetVayuCustomFieldNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VayuCustomFieldName, true
}

// SetVayuCustomFieldName sets field value
func (o *DeleteCustomFieldResponseCustomField) SetVayuCustomFieldName(v string) {
	o.VayuCustomFieldName = v
}

// GetValueType returns the ValueType field value
func (o *DeleteCustomFieldResponseCustomField) GetValueType() CustomFieldValueTypes {
	if o == nil {
		var ret CustomFieldValueTypes
		return ret
	}

	return o.ValueType
}

// GetValueTypeOk returns a tuple with the ValueType field value
// and a boolean to check if the value has been set.
func (o *DeleteCustomFieldResponseCustomField) GetValueTypeOk() (*CustomFieldValueTypes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ValueType, true
}

// SetValueType sets field value
func (o *DeleteCustomFieldResponseCustomField) SetValueType(v CustomFieldValueTypes) {
	o.ValueType = v
}

// GetIntegrationSource returns the IntegrationSource field value if set, zero value otherwise.
func (o *DeleteCustomFieldResponseCustomField) GetIntegrationSource() string {
	if o == nil || IsNil(o.IntegrationSource) {
		var ret string
		return ret
	}
	return *o.IntegrationSource
}

// GetIntegrationSourceOk returns a tuple with the IntegrationSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteCustomFieldResponseCustomField) GetIntegrationSourceOk() (*string, bool) {
	if o == nil || IsNil(o.IntegrationSource) {
		return nil, false
	}
	return o.IntegrationSource, true
}

// HasIntegrationSource returns a boolean if a field has been set.
func (o *DeleteCustomFieldResponseCustomField) HasIntegrationSource() bool {
	if o != nil && !IsNil(o.IntegrationSource) {
		return true
	}

	return false
}

// SetIntegrationSource gets a reference to the given string and assigns it to the IntegrationSource field.
func (o *DeleteCustomFieldResponseCustomField) SetIntegrationSource(v string) {
	o.IntegrationSource = &v
}

// GetIntegrationEntityType returns the IntegrationEntityType field value if set, zero value otherwise.
func (o *DeleteCustomFieldResponseCustomField) GetIntegrationEntityType() IntegrationEntityTypes {
	if o == nil || IsNil(o.IntegrationEntityType) {
		var ret IntegrationEntityTypes
		return ret
	}
	return *o.IntegrationEntityType
}

// GetIntegrationEntityTypeOk returns a tuple with the IntegrationEntityType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteCustomFieldResponseCustomField) GetIntegrationEntityTypeOk() (*IntegrationEntityTypes, bool) {
	if o == nil || IsNil(o.IntegrationEntityType) {
		return nil, false
	}
	return o.IntegrationEntityType, true
}

// HasIntegrationEntityType returns a boolean if a field has been set.
func (o *DeleteCustomFieldResponseCustomField) HasIntegrationEntityType() bool {
	if o != nil && !IsNil(o.IntegrationEntityType) {
		return true
	}

	return false
}

// SetIntegrationEntityType gets a reference to the given IntegrationEntityTypes and assigns it to the IntegrationEntityType field.
func (o *DeleteCustomFieldResponseCustomField) SetIntegrationEntityType(v IntegrationEntityTypes) {
	o.IntegrationEntityType = &v
}

// GetFieldPath returns the FieldPath field value if set, zero value otherwise.
func (o *DeleteCustomFieldResponseCustomField) GetFieldPath() string {
	if o == nil || IsNil(o.FieldPath) {
		var ret string
		return ret
	}
	return *o.FieldPath
}

// GetFieldPathOk returns a tuple with the FieldPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteCustomFieldResponseCustomField) GetFieldPathOk() (*string, bool) {
	if o == nil || IsNil(o.FieldPath) {
		return nil, false
	}
	return o.FieldPath, true
}

// HasFieldPath returns a boolean if a field has been set.
func (o *DeleteCustomFieldResponseCustomField) HasFieldPath() bool {
	if o != nil && !IsNil(o.FieldPath) {
		return true
	}

	return false
}

// SetFieldPath gets a reference to the given string and assigns it to the FieldPath field.
func (o *DeleteCustomFieldResponseCustomField) SetFieldPath(v string) {
	o.FieldPath = &v
}

// GetAllowedValues returns the AllowedValues field value if set, zero value otherwise.
func (o *DeleteCustomFieldResponseCustomField) GetAllowedValues() []string {
	if o == nil || IsNil(o.AllowedValues) {
		var ret []string
		return ret
	}
	return o.AllowedValues
}

// GetAllowedValuesOk returns a tuple with the AllowedValues field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteCustomFieldResponseCustomField) GetAllowedValuesOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedValues) {
		return nil, false
	}
	return o.AllowedValues, true
}

// HasAllowedValues returns a boolean if a field has been set.
func (o *DeleteCustomFieldResponseCustomField) HasAllowedValues() bool {
	if o != nil && !IsNil(o.AllowedValues) {
		return true
	}

	return false
}

// SetAllowedValues gets a reference to the given []string and assigns it to the AllowedValues field.
func (o *DeleteCustomFieldResponseCustomField) SetAllowedValues(v []string) {
	o.AllowedValues = v
}

// GetDefaultValue returns the DefaultValue field value if set, zero value otherwise.
func (o *DeleteCustomFieldResponseCustomField) GetDefaultValue() string {
	if o == nil || IsNil(o.DefaultValue) {
		var ret string
		return ret
	}
	return *o.DefaultValue
}

// GetDefaultValueOk returns a tuple with the DefaultValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteCustomFieldResponseCustomField) GetDefaultValueOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultValue) {
		return nil, false
	}
	return o.DefaultValue, true
}

// HasDefaultValue returns a boolean if a field has been set.
func (o *DeleteCustomFieldResponseCustomField) HasDefaultValue() bool {
	if o != nil && !IsNil(o.DefaultValue) {
		return true
	}

	return false
}

// SetDefaultValue gets a reference to the given string and assigns it to the DefaultValue field.
func (o *DeleteCustomFieldResponseCustomField) SetDefaultValue(v string) {
	o.DefaultValue = &v
}

// GetId returns the Id field value
func (o *DeleteCustomFieldResponseCustomField) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DeleteCustomFieldResponseCustomField) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DeleteCustomFieldResponseCustomField) SetId(v string) {
	o.Id = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *DeleteCustomFieldResponseCustomField) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *DeleteCustomFieldResponseCustomField) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *DeleteCustomFieldResponseCustomField) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *DeleteCustomFieldResponseCustomField) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *DeleteCustomFieldResponseCustomField) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *DeleteCustomFieldResponseCustomField) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetDeletedAt returns the DeletedAt field value
func (o *DeleteCustomFieldResponseCustomField) GetDeletedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeletedAt
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value
// and a boolean to check if the value has been set.
func (o *DeleteCustomFieldResponseCustomField) GetDeletedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeletedAt, true
}

// SetDeletedAt sets field value
func (o *DeleteCustomFieldResponseCustomField) SetDeletedAt(v string) {
	o.DeletedAt = v
}

func (o DeleteCustomFieldResponseCustomField) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteCustomFieldResponseCustomField) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["vayuEntity"] = o.VayuEntity
	toSerialize["vayuCustomFieldName"] = o.VayuCustomFieldName
	toSerialize["valueType"] = o.ValueType
	if !IsNil(o.IntegrationSource) {
		toSerialize["integrationSource"] = o.IntegrationSource
	}
	if !IsNil(o.IntegrationEntityType) {
		toSerialize["integrationEntityType"] = o.IntegrationEntityType
	}
	if !IsNil(o.FieldPath) {
		toSerialize["fieldPath"] = o.FieldPath
	}
	if !IsNil(o.AllowedValues) {
		toSerialize["allowedValues"] = o.AllowedValues
	}
	if !IsNil(o.DefaultValue) {
		toSerialize["defaultValue"] = o.DefaultValue
	}
	toSerialize["id"] = o.Id
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	toSerialize["deletedAt"] = o.DeletedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DeleteCustomFieldResponseCustomField) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"vayuEntity",
		"vayuCustomFieldName",
		"valueType",
		"id",
		"createdAt",
		"updatedAt",
		"deletedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteCustomFieldResponseCustomField := _DeleteCustomFieldResponseCustomField{}

	err = json.Unmarshal(data, &varDeleteCustomFieldResponseCustomField)

	if err != nil {
		return err
	}

	*o = DeleteCustomFieldResponseCustomField(varDeleteCustomFieldResponseCustomField)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "vayuEntity")
		delete(additionalProperties, "vayuCustomFieldName")
		delete(additionalProperties, "valueType")
		delete(additionalProperties, "integrationSource")
		delete(additionalProperties, "integrationEntityType")
		delete(additionalProperties, "fieldPath")
		delete(additionalProperties, "allowedValues")
		delete(additionalProperties, "defaultValue")
		delete(additionalProperties, "id")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "updatedAt")
		delete(additionalProperties, "deletedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDeleteCustomFieldResponseCustomField struct {
	value *DeleteCustomFieldResponseCustomField
	isSet bool
}

func (v NullableDeleteCustomFieldResponseCustomField) Get() *DeleteCustomFieldResponseCustomField {
	return v.value
}

func (v *NullableDeleteCustomFieldResponseCustomField) Set(val *DeleteCustomFieldResponseCustomField) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteCustomFieldResponseCustomField) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteCustomFieldResponseCustomField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteCustomFieldResponseCustomField(val *DeleteCustomFieldResponseCustomField) *NullableDeleteCustomFieldResponseCustomField {
	return &NullableDeleteCustomFieldResponseCustomField{value: val, isSet: true}
}

func (v NullableDeleteCustomFieldResponseCustomField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteCustomFieldResponseCustomField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


