/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the GetCustomerByNameResponseCustomer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCustomerByNameResponseCustomer{}

// GetCustomerByNameResponseCustomer The customer matching the provided name
type GetCustomerByNameResponseCustomer struct {
	// The name of the customer
	Name string `json:"name"`
	// The aliases of the customer used to match events to the customer.
	Aliases []string `json:"aliases,omitempty"`
	// The contacts of the customer. Contact marked as primary is the target for invoice sharing.
	Contacts []Contact `json:"contacts,omitempty"`
	Source NullableCustomerSource `json:"source,omitempty"`
	// The legal name of the customer
	LegalName NullableString `json:"legalName,omitempty"`
	// The tax IDs of the customer
	TaxIds []string `json:"taxIds,omitempty"`
	// The tax ID of the customer (deprecated, use taxIds instead)
	// Deprecated
	TaxId NullableString `json:"taxId,omitempty"`
	CloudProviderSettings NullableCustomerCloudProviderSettings `json:"cloudProviderSettings,omitempty"`
	// The external ID of the customer
	ExternalId *string `json:"externalId,omitempty"`
	// The ID of the customer in the ERP system
	CustomerErpId NullableString `json:"customerErpId,omitempty"`
	Address NullableAddress `json:"address,omitempty"`
	// The ID of the customer in the Salesforce system
	SalesForceAccountId NullableString `json:"salesForceAccountId,omitempty"`
	// The due days of the customer
	DueDays NullableString `json:"dueDays,omitempty"`
	Currency NullableCurrency `json:"currency,omitempty"`
	// Custom fields from CRM systems (Salesforce, HubSpot, etc.)
	CustomFields []CustomField `json:"customFields,omitempty"`
	// The name of the subsidiary of the customer
	Subsidiary NullableString `json:"subsidiary,omitempty"`
	Id string `json:"id"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	AdditionalProperties map[string]interface{}
}

type _GetCustomerByNameResponseCustomer GetCustomerByNameResponseCustomer

// NewGetCustomerByNameResponseCustomer instantiates a new GetCustomerByNameResponseCustomer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCustomerByNameResponseCustomer(name string, id string, createdAt time.Time, updatedAt time.Time) *GetCustomerByNameResponseCustomer {
	this := GetCustomerByNameResponseCustomer{}
	this.Name = name
	this.Id = id
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewGetCustomerByNameResponseCustomerWithDefaults instantiates a new GetCustomerByNameResponseCustomer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCustomerByNameResponseCustomerWithDefaults() *GetCustomerByNameResponseCustomer {
	this := GetCustomerByNameResponseCustomer{}
	return &this
}

// GetName returns the Name field value
func (o *GetCustomerByNameResponseCustomer) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GetCustomerByNameResponseCustomer) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GetCustomerByNameResponseCustomer) SetName(v string) {
	o.Name = v
}

// GetAliases returns the Aliases field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetCustomerByNameResponseCustomer) GetAliases() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Aliases
}

// GetAliasesOk returns a tuple with the Aliases field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCustomerByNameResponseCustomer) GetAliasesOk() ([]string, bool) {
	if o == nil || IsNil(o.Aliases) {
		return nil, false
	}
	return o.Aliases, true
}

// HasAliases returns a boolean if a field has been set.
func (o *GetCustomerByNameResponseCustomer) HasAliases() bool {
	if o != nil && !IsNil(o.Aliases) {
		return true
	}

	return false
}

// SetAliases gets a reference to the given []string and assigns it to the Aliases field.
func (o *GetCustomerByNameResponseCustomer) SetAliases(v []string) {
	o.Aliases = v
}

// GetContacts returns the Contacts field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetCustomerByNameResponseCustomer) GetContacts() []Contact {
	if o == nil {
		var ret []Contact
		return ret
	}
	return o.Contacts
}

// GetContactsOk returns a tuple with the Contacts field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCustomerByNameResponseCustomer) GetContactsOk() ([]Contact, bool) {
	if o == nil || IsNil(o.Contacts) {
		return nil, false
	}
	return o.Contacts, true
}

// HasContacts returns a boolean if a field has been set.
func (o *GetCustomerByNameResponseCustomer) HasContacts() bool {
	if o != nil && !IsNil(o.Contacts) {
		return true
	}

	return false
}

// SetContacts gets a reference to the given []Contact and assigns it to the Contacts field.
func (o *GetCustomerByNameResponseCustomer) SetContacts(v []Contact) {
	o.Contacts = v
}

// GetSource returns the Source field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetCustomerByNameResponseCustomer) GetSource() CustomerSource {
	if o == nil || IsNil(o.Source.Get()) {
		var ret CustomerSource
		return ret
	}
	return *o.Source.Get()
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCustomerByNameResponseCustomer) GetSourceOk() (*CustomerSource, bool) {
	if o == nil {
		return nil, false
	}
	return o.Source.Get(), o.Source.IsSet()
}

// HasSource returns a boolean if a field has been set.
func (o *GetCustomerByNameResponseCustomer) HasSource() bool {
	if o != nil && o.Source.IsSet() {
		return true
	}

	return false
}

// SetSource gets a reference to the given NullableCustomerSource and assigns it to the Source field.
func (o *GetCustomerByNameResponseCustomer) SetSource(v CustomerSource) {
	o.Source.Set(&v)
}
// SetSourceNil sets the value for Source to be an explicit nil
func (o *GetCustomerByNameResponseCustomer) SetSourceNil() {
	o.Source.Set(nil)
}

// UnsetSource ensures that no value is present for Source, not even an explicit nil
func (o *GetCustomerByNameResponseCustomer) UnsetSource() {
	o.Source.Unset()
}

// GetLegalName returns the LegalName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetCustomerByNameResponseCustomer) GetLegalName() string {
	if o == nil || IsNil(o.LegalName.Get()) {
		var ret string
		return ret
	}
	return *o.LegalName.Get()
}

// GetLegalNameOk returns a tuple with the LegalName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCustomerByNameResponseCustomer) GetLegalNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LegalName.Get(), o.LegalName.IsSet()
}

// HasLegalName returns a boolean if a field has been set.
func (o *GetCustomerByNameResponseCustomer) HasLegalName() bool {
	if o != nil && o.LegalName.IsSet() {
		return true
	}

	return false
}

// SetLegalName gets a reference to the given NullableString and assigns it to the LegalName field.
func (o *GetCustomerByNameResponseCustomer) SetLegalName(v string) {
	o.LegalName.Set(&v)
}
// SetLegalNameNil sets the value for LegalName to be an explicit nil
func (o *GetCustomerByNameResponseCustomer) SetLegalNameNil() {
	o.LegalName.Set(nil)
}

// UnsetLegalName ensures that no value is present for LegalName, not even an explicit nil
func (o *GetCustomerByNameResponseCustomer) UnsetLegalName() {
	o.LegalName.Unset()
}

// GetTaxIds returns the TaxIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetCustomerByNameResponseCustomer) GetTaxIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.TaxIds
}

// GetTaxIdsOk returns a tuple with the TaxIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCustomerByNameResponseCustomer) GetTaxIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.TaxIds) {
		return nil, false
	}
	return o.TaxIds, true
}

// HasTaxIds returns a boolean if a field has been set.
func (o *GetCustomerByNameResponseCustomer) HasTaxIds() bool {
	if o != nil && !IsNil(o.TaxIds) {
		return true
	}

	return false
}

// SetTaxIds gets a reference to the given []string and assigns it to the TaxIds field.
func (o *GetCustomerByNameResponseCustomer) SetTaxIds(v []string) {
	o.TaxIds = v
}

// GetTaxId returns the TaxId field value if set, zero value otherwise (both if not set or set to explicit null).
// Deprecated
func (o *GetCustomerByNameResponseCustomer) GetTaxId() string {
	if o == nil || IsNil(o.TaxId.Get()) {
		var ret string
		return ret
	}
	return *o.TaxId.Get()
}

// GetTaxIdOk returns a tuple with the TaxId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
// Deprecated
func (o *GetCustomerByNameResponseCustomer) GetTaxIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TaxId.Get(), o.TaxId.IsSet()
}

// HasTaxId returns a boolean if a field has been set.
func (o *GetCustomerByNameResponseCustomer) HasTaxId() bool {
	if o != nil && o.TaxId.IsSet() {
		return true
	}

	return false
}

// SetTaxId gets a reference to the given NullableString and assigns it to the TaxId field.
// Deprecated
func (o *GetCustomerByNameResponseCustomer) SetTaxId(v string) {
	o.TaxId.Set(&v)
}
// SetTaxIdNil sets the value for TaxId to be an explicit nil
func (o *GetCustomerByNameResponseCustomer) SetTaxIdNil() {
	o.TaxId.Set(nil)
}

// UnsetTaxId ensures that no value is present for TaxId, not even an explicit nil
func (o *GetCustomerByNameResponseCustomer) UnsetTaxId() {
	o.TaxId.Unset()
}

// GetCloudProviderSettings returns the CloudProviderSettings field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetCustomerByNameResponseCustomer) GetCloudProviderSettings() CustomerCloudProviderSettings {
	if o == nil || IsNil(o.CloudProviderSettings.Get()) {
		var ret CustomerCloudProviderSettings
		return ret
	}
	return *o.CloudProviderSettings.Get()
}

// GetCloudProviderSettingsOk returns a tuple with the CloudProviderSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCustomerByNameResponseCustomer) GetCloudProviderSettingsOk() (*CustomerCloudProviderSettings, bool) {
	if o == nil {
		return nil, false
	}
	return o.CloudProviderSettings.Get(), o.CloudProviderSettings.IsSet()
}

// HasCloudProviderSettings returns a boolean if a field has been set.
func (o *GetCustomerByNameResponseCustomer) HasCloudProviderSettings() bool {
	if o != nil && o.CloudProviderSettings.IsSet() {
		return true
	}

	return false
}

// SetCloudProviderSettings gets a reference to the given NullableCustomerCloudProviderSettings and assigns it to the CloudProviderSettings field.
func (o *GetCustomerByNameResponseCustomer) SetCloudProviderSettings(v CustomerCloudProviderSettings) {
	o.CloudProviderSettings.Set(&v)
}
// SetCloudProviderSettingsNil sets the value for CloudProviderSettings to be an explicit nil
func (o *GetCustomerByNameResponseCustomer) SetCloudProviderSettingsNil() {
	o.CloudProviderSettings.Set(nil)
}

// UnsetCloudProviderSettings ensures that no value is present for CloudProviderSettings, not even an explicit nil
func (o *GetCustomerByNameResponseCustomer) UnsetCloudProviderSettings() {
	o.CloudProviderSettings.Unset()
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise.
func (o *GetCustomerByNameResponseCustomer) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId) {
		var ret string
		return ret
	}
	return *o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCustomerByNameResponseCustomer) GetExternalIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalId) {
		return nil, false
	}
	return o.ExternalId, true
}

// HasExternalId returns a boolean if a field has been set.
func (o *GetCustomerByNameResponseCustomer) HasExternalId() bool {
	if o != nil && !IsNil(o.ExternalId) {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given string and assigns it to the ExternalId field.
func (o *GetCustomerByNameResponseCustomer) SetExternalId(v string) {
	o.ExternalId = &v
}

// GetCustomerErpId returns the CustomerErpId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetCustomerByNameResponseCustomer) GetCustomerErpId() string {
	if o == nil || IsNil(o.CustomerErpId.Get()) {
		var ret string
		return ret
	}
	return *o.CustomerErpId.Get()
}

// GetCustomerErpIdOk returns a tuple with the CustomerErpId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCustomerByNameResponseCustomer) GetCustomerErpIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CustomerErpId.Get(), o.CustomerErpId.IsSet()
}

// HasCustomerErpId returns a boolean if a field has been set.
func (o *GetCustomerByNameResponseCustomer) HasCustomerErpId() bool {
	if o != nil && o.CustomerErpId.IsSet() {
		return true
	}

	return false
}

// SetCustomerErpId gets a reference to the given NullableString and assigns it to the CustomerErpId field.
func (o *GetCustomerByNameResponseCustomer) SetCustomerErpId(v string) {
	o.CustomerErpId.Set(&v)
}
// SetCustomerErpIdNil sets the value for CustomerErpId to be an explicit nil
func (o *GetCustomerByNameResponseCustomer) SetCustomerErpIdNil() {
	o.CustomerErpId.Set(nil)
}

// UnsetCustomerErpId ensures that no value is present for CustomerErpId, not even an explicit nil
func (o *GetCustomerByNameResponseCustomer) UnsetCustomerErpId() {
	o.CustomerErpId.Unset()
}

// GetAddress returns the Address field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetCustomerByNameResponseCustomer) GetAddress() Address {
	if o == nil || IsNil(o.Address.Get()) {
		var ret Address
		return ret
	}
	return *o.Address.Get()
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCustomerByNameResponseCustomer) GetAddressOk() (*Address, bool) {
	if o == nil {
		return nil, false
	}
	return o.Address.Get(), o.Address.IsSet()
}

// HasAddress returns a boolean if a field has been set.
func (o *GetCustomerByNameResponseCustomer) HasAddress() bool {
	if o != nil && o.Address.IsSet() {
		return true
	}

	return false
}

// SetAddress gets a reference to the given NullableAddress and assigns it to the Address field.
func (o *GetCustomerByNameResponseCustomer) SetAddress(v Address) {
	o.Address.Set(&v)
}
// SetAddressNil sets the value for Address to be an explicit nil
func (o *GetCustomerByNameResponseCustomer) SetAddressNil() {
	o.Address.Set(nil)
}

// UnsetAddress ensures that no value is present for Address, not even an explicit nil
func (o *GetCustomerByNameResponseCustomer) UnsetAddress() {
	o.Address.Unset()
}

// GetSalesForceAccountId returns the SalesForceAccountId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetCustomerByNameResponseCustomer) GetSalesForceAccountId() string {
	if o == nil || IsNil(o.SalesForceAccountId.Get()) {
		var ret string
		return ret
	}
	return *o.SalesForceAccountId.Get()
}

// GetSalesForceAccountIdOk returns a tuple with the SalesForceAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCustomerByNameResponseCustomer) GetSalesForceAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SalesForceAccountId.Get(), o.SalesForceAccountId.IsSet()
}

// HasSalesForceAccountId returns a boolean if a field has been set.
func (o *GetCustomerByNameResponseCustomer) HasSalesForceAccountId() bool {
	if o != nil && o.SalesForceAccountId.IsSet() {
		return true
	}

	return false
}

// SetSalesForceAccountId gets a reference to the given NullableString and assigns it to the SalesForceAccountId field.
func (o *GetCustomerByNameResponseCustomer) SetSalesForceAccountId(v string) {
	o.SalesForceAccountId.Set(&v)
}
// SetSalesForceAccountIdNil sets the value for SalesForceAccountId to be an explicit nil
func (o *GetCustomerByNameResponseCustomer) SetSalesForceAccountIdNil() {
	o.SalesForceAccountId.Set(nil)
}

// UnsetSalesForceAccountId ensures that no value is present for SalesForceAccountId, not even an explicit nil
func (o *GetCustomerByNameResponseCustomer) UnsetSalesForceAccountId() {
	o.SalesForceAccountId.Unset()
}

// GetDueDays returns the DueDays field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetCustomerByNameResponseCustomer) GetDueDays() string {
	if o == nil || IsNil(o.DueDays.Get()) {
		var ret string
		return ret
	}
	return *o.DueDays.Get()
}

// GetDueDaysOk returns a tuple with the DueDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCustomerByNameResponseCustomer) GetDueDaysOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DueDays.Get(), o.DueDays.IsSet()
}

// HasDueDays returns a boolean if a field has been set.
func (o *GetCustomerByNameResponseCustomer) HasDueDays() bool {
	if o != nil && o.DueDays.IsSet() {
		return true
	}

	return false
}

// SetDueDays gets a reference to the given NullableString and assigns it to the DueDays field.
func (o *GetCustomerByNameResponseCustomer) SetDueDays(v string) {
	o.DueDays.Set(&v)
}
// SetDueDaysNil sets the value for DueDays to be an explicit nil
func (o *GetCustomerByNameResponseCustomer) SetDueDaysNil() {
	o.DueDays.Set(nil)
}

// UnsetDueDays ensures that no value is present for DueDays, not even an explicit nil
func (o *GetCustomerByNameResponseCustomer) UnsetDueDays() {
	o.DueDays.Unset()
}

// GetCurrency returns the Currency field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetCustomerByNameResponseCustomer) GetCurrency() Currency {
	if o == nil || IsNil(o.Currency.Get()) {
		var ret Currency
		return ret
	}
	return *o.Currency.Get()
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCustomerByNameResponseCustomer) GetCurrencyOk() (*Currency, bool) {
	if o == nil {
		return nil, false
	}
	return o.Currency.Get(), o.Currency.IsSet()
}

// HasCurrency returns a boolean if a field has been set.
func (o *GetCustomerByNameResponseCustomer) HasCurrency() bool {
	if o != nil && o.Currency.IsSet() {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given NullableCurrency and assigns it to the Currency field.
func (o *GetCustomerByNameResponseCustomer) SetCurrency(v Currency) {
	o.Currency.Set(&v)
}
// SetCurrencyNil sets the value for Currency to be an explicit nil
func (o *GetCustomerByNameResponseCustomer) SetCurrencyNil() {
	o.Currency.Set(nil)
}

// UnsetCurrency ensures that no value is present for Currency, not even an explicit nil
func (o *GetCustomerByNameResponseCustomer) UnsetCurrency() {
	o.Currency.Unset()
}

// GetCustomFields returns the CustomFields field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetCustomerByNameResponseCustomer) GetCustomFields() []CustomField {
	if o == nil {
		var ret []CustomField
		return ret
	}
	return o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCustomerByNameResponseCustomer) GetCustomFieldsOk() ([]CustomField, bool) {
	if o == nil || IsNil(o.CustomFields) {
		return nil, false
	}
	return o.CustomFields, true
}

// HasCustomFields returns a boolean if a field has been set.
func (o *GetCustomerByNameResponseCustomer) HasCustomFields() bool {
	if o != nil && !IsNil(o.CustomFields) {
		return true
	}

	return false
}

// SetCustomFields gets a reference to the given []CustomField and assigns it to the CustomFields field.
func (o *GetCustomerByNameResponseCustomer) SetCustomFields(v []CustomField) {
	o.CustomFields = v
}

// GetSubsidiary returns the Subsidiary field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetCustomerByNameResponseCustomer) GetSubsidiary() string {
	if o == nil || IsNil(o.Subsidiary.Get()) {
		var ret string
		return ret
	}
	return *o.Subsidiary.Get()
}

// GetSubsidiaryOk returns a tuple with the Subsidiary field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCustomerByNameResponseCustomer) GetSubsidiaryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Subsidiary.Get(), o.Subsidiary.IsSet()
}

// HasSubsidiary returns a boolean if a field has been set.
func (o *GetCustomerByNameResponseCustomer) HasSubsidiary() bool {
	if o != nil && o.Subsidiary.IsSet() {
		return true
	}

	return false
}

// SetSubsidiary gets a reference to the given NullableString and assigns it to the Subsidiary field.
func (o *GetCustomerByNameResponseCustomer) SetSubsidiary(v string) {
	o.Subsidiary.Set(&v)
}
// SetSubsidiaryNil sets the value for Subsidiary to be an explicit nil
func (o *GetCustomerByNameResponseCustomer) SetSubsidiaryNil() {
	o.Subsidiary.Set(nil)
}

// UnsetSubsidiary ensures that no value is present for Subsidiary, not even an explicit nil
func (o *GetCustomerByNameResponseCustomer) UnsetSubsidiary() {
	o.Subsidiary.Unset()
}

// GetId returns the Id field value
func (o *GetCustomerByNameResponseCustomer) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetCustomerByNameResponseCustomer) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetCustomerByNameResponseCustomer) SetId(v string) {
	o.Id = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *GetCustomerByNameResponseCustomer) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *GetCustomerByNameResponseCustomer) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *GetCustomerByNameResponseCustomer) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *GetCustomerByNameResponseCustomer) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *GetCustomerByNameResponseCustomer) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *GetCustomerByNameResponseCustomer) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o GetCustomerByNameResponseCustomer) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCustomerByNameResponseCustomer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if o.Aliases != nil {
		toSerialize["aliases"] = o.Aliases
	}
	if o.Contacts != nil {
		toSerialize["contacts"] = o.Contacts
	}
	if o.Source.IsSet() {
		toSerialize["source"] = o.Source.Get()
	}
	if o.LegalName.IsSet() {
		toSerialize["legalName"] = o.LegalName.Get()
	}
	if o.TaxIds != nil {
		toSerialize["taxIds"] = o.TaxIds
	}
	if o.TaxId.IsSet() {
		toSerialize["taxId"] = o.TaxId.Get()
	}
	if o.CloudProviderSettings.IsSet() {
		toSerialize["cloudProviderSettings"] = o.CloudProviderSettings.Get()
	}
	if !IsNil(o.ExternalId) {
		toSerialize["externalId"] = o.ExternalId
	}
	if o.CustomerErpId.IsSet() {
		toSerialize["customerErpId"] = o.CustomerErpId.Get()
	}
	if o.Address.IsSet() {
		toSerialize["address"] = o.Address.Get()
	}
	if o.SalesForceAccountId.IsSet() {
		toSerialize["salesForceAccountId"] = o.SalesForceAccountId.Get()
	}
	if o.DueDays.IsSet() {
		toSerialize["dueDays"] = o.DueDays.Get()
	}
	if o.Currency.IsSet() {
		toSerialize["currency"] = o.Currency.Get()
	}
	if o.CustomFields != nil {
		toSerialize["customFields"] = o.CustomFields
	}
	if o.Subsidiary.IsSet() {
		toSerialize["subsidiary"] = o.Subsidiary.Get()
	}
	toSerialize["id"] = o.Id
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetCustomerByNameResponseCustomer) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"id",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetCustomerByNameResponseCustomer := _GetCustomerByNameResponseCustomer{}

	err = json.Unmarshal(data, &varGetCustomerByNameResponseCustomer)

	if err != nil {
		return err
	}

	*o = GetCustomerByNameResponseCustomer(varGetCustomerByNameResponseCustomer)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "aliases")
		delete(additionalProperties, "contacts")
		delete(additionalProperties, "source")
		delete(additionalProperties, "legalName")
		delete(additionalProperties, "taxIds")
		delete(additionalProperties, "taxId")
		delete(additionalProperties, "cloudProviderSettings")
		delete(additionalProperties, "externalId")
		delete(additionalProperties, "customerErpId")
		delete(additionalProperties, "address")
		delete(additionalProperties, "salesForceAccountId")
		delete(additionalProperties, "dueDays")
		delete(additionalProperties, "currency")
		delete(additionalProperties, "customFields")
		delete(additionalProperties, "subsidiary")
		delete(additionalProperties, "id")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "updatedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetCustomerByNameResponseCustomer struct {
	value *GetCustomerByNameResponseCustomer
	isSet bool
}

func (v NullableGetCustomerByNameResponseCustomer) Get() *GetCustomerByNameResponseCustomer {
	return v.value
}

func (v *NullableGetCustomerByNameResponseCustomer) Set(val *GetCustomerByNameResponseCustomer) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCustomerByNameResponseCustomer) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCustomerByNameResponseCustomer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCustomerByNameResponseCustomer(val *GetCustomerByNameResponseCustomer) *NullableGetCustomerByNameResponseCustomer {
	return &NullableGetCustomerByNameResponseCustomer{value: val, isSet: true}
}

func (v NullableGetCustomerByNameResponseCustomer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCustomerByNameResponseCustomer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


