/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the V2QueryEventsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2QueryEventsResponse{}

// V2QueryEventsResponse struct for V2QueryEventsResponse
type V2QueryEventsResponse struct {
	Events []QueryEventsResponseEventsInner `json:"events"`
	Total float32 `json:"total"`
	HasMore bool `json:"hasMore"`
	NextCursor *string `json:"nextCursor,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _V2QueryEventsResponse V2QueryEventsResponse

// NewV2QueryEventsResponse instantiates a new V2QueryEventsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2QueryEventsResponse(events []QueryEventsResponseEventsInner, total float32, hasMore bool) *V2QueryEventsResponse {
	this := V2QueryEventsResponse{}
	this.Events = events
	this.Total = total
	this.HasMore = hasMore
	return &this
}

// NewV2QueryEventsResponseWithDefaults instantiates a new V2QueryEventsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2QueryEventsResponseWithDefaults() *V2QueryEventsResponse {
	this := V2QueryEventsResponse{}
	return &this
}

// GetEvents returns the Events field value
func (o *V2QueryEventsResponse) GetEvents() []QueryEventsResponseEventsInner {
	if o == nil {
		var ret []QueryEventsResponseEventsInner
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *V2QueryEventsResponse) GetEventsOk() ([]QueryEventsResponseEventsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *V2QueryEventsResponse) SetEvents(v []QueryEventsResponseEventsInner) {
	o.Events = v
}

// GetTotal returns the Total field value
func (o *V2QueryEventsResponse) GetTotal() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *V2QueryEventsResponse) GetTotalOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *V2QueryEventsResponse) SetTotal(v float32) {
	o.Total = v
}

// GetHasMore returns the HasMore field value
func (o *V2QueryEventsResponse) GetHasMore() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value
// and a boolean to check if the value has been set.
func (o *V2QueryEventsResponse) GetHasMoreOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasMore, true
}

// SetHasMore sets field value
func (o *V2QueryEventsResponse) SetHasMore(v bool) {
	o.HasMore = v
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise.
func (o *V2QueryEventsResponse) GetNextCursor() string {
	if o == nil || IsNil(o.NextCursor) {
		var ret string
		return ret
	}
	return *o.NextCursor
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2QueryEventsResponse) GetNextCursorOk() (*string, bool) {
	if o == nil || IsNil(o.NextCursor) {
		return nil, false
	}
	return o.NextCursor, true
}

// HasNextCursor returns a boolean if a field has been set.
func (o *V2QueryEventsResponse) HasNextCursor() bool {
	if o != nil && !IsNil(o.NextCursor) {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given string and assigns it to the NextCursor field.
func (o *V2QueryEventsResponse) SetNextCursor(v string) {
	o.NextCursor = &v
}

func (o V2QueryEventsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2QueryEventsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["events"] = o.Events
	toSerialize["total"] = o.Total
	toSerialize["hasMore"] = o.HasMore
	if !IsNil(o.NextCursor) {
		toSerialize["nextCursor"] = o.NextCursor
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *V2QueryEventsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"events",
		"total",
		"hasMore",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV2QueryEventsResponse := _V2QueryEventsResponse{}

	err = json.Unmarshal(data, &varV2QueryEventsResponse)

	if err != nil {
		return err
	}

	*o = V2QueryEventsResponse(varV2QueryEventsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "events")
		delete(additionalProperties, "total")
		delete(additionalProperties, "hasMore")
		delete(additionalProperties, "nextCursor")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableV2QueryEventsResponse struct {
	value *V2QueryEventsResponse
	isSet bool
}

func (v NullableV2QueryEventsResponse) Get() *V2QueryEventsResponse {
	return v.value
}

func (v *NullableV2QueryEventsResponse) Set(val *V2QueryEventsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV2QueryEventsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV2QueryEventsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2QueryEventsResponse(val *V2QueryEventsResponse) *NullableV2QueryEventsResponse {
	return &NullableV2QueryEventsResponse{value: val, isSet: true}
}

func (v NullableV2QueryEventsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2QueryEventsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


