/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the V2QueryEventsAggregationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2QueryEventsAggregationResponse{}

// V2QueryEventsAggregationResponse struct for V2QueryEventsAggregationResponse
type V2QueryEventsAggregationResponse struct {
	DataPoints []V2QueryEventsAggregationResponseDataPointsInner `json:"dataPoints"`
	Period V2QueryEventsAggregationRequestPeriod `json:"period"`
	GroupBy string `json:"groupBy"`
	AdditionalProperties map[string]interface{}
}

type _V2QueryEventsAggregationResponse V2QueryEventsAggregationResponse

// NewV2QueryEventsAggregationResponse instantiates a new V2QueryEventsAggregationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2QueryEventsAggregationResponse(dataPoints []V2QueryEventsAggregationResponseDataPointsInner, period V2QueryEventsAggregationRequestPeriod, groupBy string) *V2QueryEventsAggregationResponse {
	this := V2QueryEventsAggregationResponse{}
	this.DataPoints = dataPoints
	this.Period = period
	this.GroupBy = groupBy
	return &this
}

// NewV2QueryEventsAggregationResponseWithDefaults instantiates a new V2QueryEventsAggregationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2QueryEventsAggregationResponseWithDefaults() *V2QueryEventsAggregationResponse {
	this := V2QueryEventsAggregationResponse{}
	return &this
}

// GetDataPoints returns the DataPoints field value
func (o *V2QueryEventsAggregationResponse) GetDataPoints() []V2QueryEventsAggregationResponseDataPointsInner {
	if o == nil {
		var ret []V2QueryEventsAggregationResponseDataPointsInner
		return ret
	}

	return o.DataPoints
}

// GetDataPointsOk returns a tuple with the DataPoints field value
// and a boolean to check if the value has been set.
func (o *V2QueryEventsAggregationResponse) GetDataPointsOk() ([]V2QueryEventsAggregationResponseDataPointsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.DataPoints, true
}

// SetDataPoints sets field value
func (o *V2QueryEventsAggregationResponse) SetDataPoints(v []V2QueryEventsAggregationResponseDataPointsInner) {
	o.DataPoints = v
}

// GetPeriod returns the Period field value
func (o *V2QueryEventsAggregationResponse) GetPeriod() V2QueryEventsAggregationRequestPeriod {
	if o == nil {
		var ret V2QueryEventsAggregationRequestPeriod
		return ret
	}

	return o.Period
}

// GetPeriodOk returns a tuple with the Period field value
// and a boolean to check if the value has been set.
func (o *V2QueryEventsAggregationResponse) GetPeriodOk() (*V2QueryEventsAggregationRequestPeriod, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Period, true
}

// SetPeriod sets field value
func (o *V2QueryEventsAggregationResponse) SetPeriod(v V2QueryEventsAggregationRequestPeriod) {
	o.Period = v
}

// GetGroupBy returns the GroupBy field value
func (o *V2QueryEventsAggregationResponse) GetGroupBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GroupBy
}

// GetGroupByOk returns a tuple with the GroupBy field value
// and a boolean to check if the value has been set.
func (o *V2QueryEventsAggregationResponse) GetGroupByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupBy, true
}

// SetGroupBy sets field value
func (o *V2QueryEventsAggregationResponse) SetGroupBy(v string) {
	o.GroupBy = v
}

func (o V2QueryEventsAggregationResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2QueryEventsAggregationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["dataPoints"] = o.DataPoints
	toSerialize["period"] = o.Period
	toSerialize["groupBy"] = o.GroupBy

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *V2QueryEventsAggregationResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"dataPoints",
		"period",
		"groupBy",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV2QueryEventsAggregationResponse := _V2QueryEventsAggregationResponse{}

	err = json.Unmarshal(data, &varV2QueryEventsAggregationResponse)

	if err != nil {
		return err
	}

	*o = V2QueryEventsAggregationResponse(varV2QueryEventsAggregationResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "dataPoints")
		delete(additionalProperties, "period")
		delete(additionalProperties, "groupBy")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableV2QueryEventsAggregationResponse struct {
	value *V2QueryEventsAggregationResponse
	isSet bool
}

func (v NullableV2QueryEventsAggregationResponse) Get() *V2QueryEventsAggregationResponse {
	return v.value
}

func (v *NullableV2QueryEventsAggregationResponse) Set(val *V2QueryEventsAggregationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV2QueryEventsAggregationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV2QueryEventsAggregationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2QueryEventsAggregationResponse(val *V2QueryEventsAggregationResponse) *NullableV2QueryEventsAggregationResponse {
	return &NullableV2QueryEventsAggregationResponse{value: val, isSet: true}
}

func (v NullableV2QueryEventsAggregationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2QueryEventsAggregationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


