/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the RefreshContractCreditsRequestGrantsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RefreshContractCreditsRequestGrantsInner{}

// RefreshContractCreditsRequestGrantsInner struct for RefreshContractCreditsRequestGrantsInner
type RefreshContractCreditsRequestGrantsInner struct {
	// The credit product (credit type) id identifying the grant to refresh. Every grant product on the contract for this credit product is set to non-prorated in the new phase.
	GrantProductId string `json:"grantProductId" validate:"regexp=^[0-9a-fA-F]{24}$"`
	// The grant's new price in the refreshed phase. If omitted, the current price is kept. If this credit product matches more than one grant product on the contract, a price cannot be applied unambiguously and the request is rejected.
	NewPrice *float32 `json:"newPrice,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RefreshContractCreditsRequestGrantsInner RefreshContractCreditsRequestGrantsInner

// NewRefreshContractCreditsRequestGrantsInner instantiates a new RefreshContractCreditsRequestGrantsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRefreshContractCreditsRequestGrantsInner(grantProductId string) *RefreshContractCreditsRequestGrantsInner {
	this := RefreshContractCreditsRequestGrantsInner{}
	this.GrantProductId = grantProductId
	return &this
}

// NewRefreshContractCreditsRequestGrantsInnerWithDefaults instantiates a new RefreshContractCreditsRequestGrantsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRefreshContractCreditsRequestGrantsInnerWithDefaults() *RefreshContractCreditsRequestGrantsInner {
	this := RefreshContractCreditsRequestGrantsInner{}
	return &this
}

// GetGrantProductId returns the GrantProductId field value
func (o *RefreshContractCreditsRequestGrantsInner) GetGrantProductId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GrantProductId
}

// GetGrantProductIdOk returns a tuple with the GrantProductId field value
// and a boolean to check if the value has been set.
func (o *RefreshContractCreditsRequestGrantsInner) GetGrantProductIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GrantProductId, true
}

// SetGrantProductId sets field value
func (o *RefreshContractCreditsRequestGrantsInner) SetGrantProductId(v string) {
	o.GrantProductId = v
}

// GetNewPrice returns the NewPrice field value if set, zero value otherwise.
func (o *RefreshContractCreditsRequestGrantsInner) GetNewPrice() float32 {
	if o == nil || IsNil(o.NewPrice) {
		var ret float32
		return ret
	}
	return *o.NewPrice
}

// GetNewPriceOk returns a tuple with the NewPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RefreshContractCreditsRequestGrantsInner) GetNewPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.NewPrice) {
		return nil, false
	}
	return o.NewPrice, true
}

// HasNewPrice returns a boolean if a field has been set.
func (o *RefreshContractCreditsRequestGrantsInner) HasNewPrice() bool {
	if o != nil && !IsNil(o.NewPrice) {
		return true
	}

	return false
}

// SetNewPrice gets a reference to the given float32 and assigns it to the NewPrice field.
func (o *RefreshContractCreditsRequestGrantsInner) SetNewPrice(v float32) {
	o.NewPrice = &v
}

func (o RefreshContractCreditsRequestGrantsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RefreshContractCreditsRequestGrantsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["grantProductId"] = o.GrantProductId
	if !IsNil(o.NewPrice) {
		toSerialize["newPrice"] = o.NewPrice
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RefreshContractCreditsRequestGrantsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"grantProductId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRefreshContractCreditsRequestGrantsInner := _RefreshContractCreditsRequestGrantsInner{}

	err = json.Unmarshal(data, &varRefreshContractCreditsRequestGrantsInner)

	if err != nil {
		return err
	}

	*o = RefreshContractCreditsRequestGrantsInner(varRefreshContractCreditsRequestGrantsInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "grantProductId")
		delete(additionalProperties, "newPrice")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRefreshContractCreditsRequestGrantsInner struct {
	value *RefreshContractCreditsRequestGrantsInner
	isSet bool
}

func (v NullableRefreshContractCreditsRequestGrantsInner) Get() *RefreshContractCreditsRequestGrantsInner {
	return v.value
}

func (v *NullableRefreshContractCreditsRequestGrantsInner) Set(val *RefreshContractCreditsRequestGrantsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableRefreshContractCreditsRequestGrantsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableRefreshContractCreditsRequestGrantsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRefreshContractCreditsRequestGrantsInner(val *RefreshContractCreditsRequestGrantsInner) *NullableRefreshContractCreditsRequestGrantsInner {
	return &NullableRefreshContractCreditsRequestGrantsInner{value: val, isSet: true}
}

func (v NullableRefreshContractCreditsRequestGrantsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRefreshContractCreditsRequestGrantsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


