/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ProductGroupProductsInnerPricingOneOf3TiersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductGroupProductsInnerPricingOneOf3TiersInner{}

// ProductGroupProductsInnerPricingOneOf3TiersInner struct for ProductGroupProductsInnerPricingOneOf3TiersInner
type ProductGroupProductsInnerPricingOneOf3TiersInner struct {
	FromInclusive float32 `json:"fromInclusive"`
	ToExclusive NullableFloat32 `json:"toExclusive,omitempty"`
	Rate NullableFloat32 `json:"rate,omitempty"`
	FlatFee NullableFloat32 `json:"flatFee,omitempty"`
	PackageSize NullableFloat32 `json:"packageSize,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ProductGroupProductsInnerPricingOneOf3TiersInner ProductGroupProductsInnerPricingOneOf3TiersInner

// NewProductGroupProductsInnerPricingOneOf3TiersInner instantiates a new ProductGroupProductsInnerPricingOneOf3TiersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductGroupProductsInnerPricingOneOf3TiersInner(fromInclusive float32) *ProductGroupProductsInnerPricingOneOf3TiersInner {
	this := ProductGroupProductsInnerPricingOneOf3TiersInner{}
	this.FromInclusive = fromInclusive
	return &this
}

// NewProductGroupProductsInnerPricingOneOf3TiersInnerWithDefaults instantiates a new ProductGroupProductsInnerPricingOneOf3TiersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductGroupProductsInnerPricingOneOf3TiersInnerWithDefaults() *ProductGroupProductsInnerPricingOneOf3TiersInner {
	this := ProductGroupProductsInnerPricingOneOf3TiersInner{}
	return &this
}

// GetFromInclusive returns the FromInclusive field value
func (o *ProductGroupProductsInnerPricingOneOf3TiersInner) GetFromInclusive() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.FromInclusive
}

// GetFromInclusiveOk returns a tuple with the FromInclusive field value
// and a boolean to check if the value has been set.
func (o *ProductGroupProductsInnerPricingOneOf3TiersInner) GetFromInclusiveOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FromInclusive, true
}

// SetFromInclusive sets field value
func (o *ProductGroupProductsInnerPricingOneOf3TiersInner) SetFromInclusive(v float32) {
	o.FromInclusive = v
}

// GetToExclusive returns the ToExclusive field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProductGroupProductsInnerPricingOneOf3TiersInner) GetToExclusive() float32 {
	if o == nil || IsNil(o.ToExclusive.Get()) {
		var ret float32
		return ret
	}
	return *o.ToExclusive.Get()
}

// GetToExclusiveOk returns a tuple with the ToExclusive field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductGroupProductsInnerPricingOneOf3TiersInner) GetToExclusiveOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ToExclusive.Get(), o.ToExclusive.IsSet()
}

// HasToExclusive returns a boolean if a field has been set.
func (o *ProductGroupProductsInnerPricingOneOf3TiersInner) HasToExclusive() bool {
	if o != nil && o.ToExclusive.IsSet() {
		return true
	}

	return false
}

// SetToExclusive gets a reference to the given NullableFloat32 and assigns it to the ToExclusive field.
func (o *ProductGroupProductsInnerPricingOneOf3TiersInner) SetToExclusive(v float32) {
	o.ToExclusive.Set(&v)
}
// SetToExclusiveNil sets the value for ToExclusive to be an explicit nil
func (o *ProductGroupProductsInnerPricingOneOf3TiersInner) SetToExclusiveNil() {
	o.ToExclusive.Set(nil)
}

// UnsetToExclusive ensures that no value is present for ToExclusive, not even an explicit nil
func (o *ProductGroupProductsInnerPricingOneOf3TiersInner) UnsetToExclusive() {
	o.ToExclusive.Unset()
}

// GetRate returns the Rate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProductGroupProductsInnerPricingOneOf3TiersInner) GetRate() float32 {
	if o == nil || IsNil(o.Rate.Get()) {
		var ret float32
		return ret
	}
	return *o.Rate.Get()
}

// GetRateOk returns a tuple with the Rate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductGroupProductsInnerPricingOneOf3TiersInner) GetRateOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Rate.Get(), o.Rate.IsSet()
}

// HasRate returns a boolean if a field has been set.
func (o *ProductGroupProductsInnerPricingOneOf3TiersInner) HasRate() bool {
	if o != nil && o.Rate.IsSet() {
		return true
	}

	return false
}

// SetRate gets a reference to the given NullableFloat32 and assigns it to the Rate field.
func (o *ProductGroupProductsInnerPricingOneOf3TiersInner) SetRate(v float32) {
	o.Rate.Set(&v)
}
// SetRateNil sets the value for Rate to be an explicit nil
func (o *ProductGroupProductsInnerPricingOneOf3TiersInner) SetRateNil() {
	o.Rate.Set(nil)
}

// UnsetRate ensures that no value is present for Rate, not even an explicit nil
func (o *ProductGroupProductsInnerPricingOneOf3TiersInner) UnsetRate() {
	o.Rate.Unset()
}

// GetFlatFee returns the FlatFee field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProductGroupProductsInnerPricingOneOf3TiersInner) GetFlatFee() float32 {
	if o == nil || IsNil(o.FlatFee.Get()) {
		var ret float32
		return ret
	}
	return *o.FlatFee.Get()
}

// GetFlatFeeOk returns a tuple with the FlatFee field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductGroupProductsInnerPricingOneOf3TiersInner) GetFlatFeeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.FlatFee.Get(), o.FlatFee.IsSet()
}

// HasFlatFee returns a boolean if a field has been set.
func (o *ProductGroupProductsInnerPricingOneOf3TiersInner) HasFlatFee() bool {
	if o != nil && o.FlatFee.IsSet() {
		return true
	}

	return false
}

// SetFlatFee gets a reference to the given NullableFloat32 and assigns it to the FlatFee field.
func (o *ProductGroupProductsInnerPricingOneOf3TiersInner) SetFlatFee(v float32) {
	o.FlatFee.Set(&v)
}
// SetFlatFeeNil sets the value for FlatFee to be an explicit nil
func (o *ProductGroupProductsInnerPricingOneOf3TiersInner) SetFlatFeeNil() {
	o.FlatFee.Set(nil)
}

// UnsetFlatFee ensures that no value is present for FlatFee, not even an explicit nil
func (o *ProductGroupProductsInnerPricingOneOf3TiersInner) UnsetFlatFee() {
	o.FlatFee.Unset()
}

// GetPackageSize returns the PackageSize field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProductGroupProductsInnerPricingOneOf3TiersInner) GetPackageSize() float32 {
	if o == nil || IsNil(o.PackageSize.Get()) {
		var ret float32
		return ret
	}
	return *o.PackageSize.Get()
}

// GetPackageSizeOk returns a tuple with the PackageSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductGroupProductsInnerPricingOneOf3TiersInner) GetPackageSizeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.PackageSize.Get(), o.PackageSize.IsSet()
}

// HasPackageSize returns a boolean if a field has been set.
func (o *ProductGroupProductsInnerPricingOneOf3TiersInner) HasPackageSize() bool {
	if o != nil && o.PackageSize.IsSet() {
		return true
	}

	return false
}

// SetPackageSize gets a reference to the given NullableFloat32 and assigns it to the PackageSize field.
func (o *ProductGroupProductsInnerPricingOneOf3TiersInner) SetPackageSize(v float32) {
	o.PackageSize.Set(&v)
}
// SetPackageSizeNil sets the value for PackageSize to be an explicit nil
func (o *ProductGroupProductsInnerPricingOneOf3TiersInner) SetPackageSizeNil() {
	o.PackageSize.Set(nil)
}

// UnsetPackageSize ensures that no value is present for PackageSize, not even an explicit nil
func (o *ProductGroupProductsInnerPricingOneOf3TiersInner) UnsetPackageSize() {
	o.PackageSize.Unset()
}

func (o ProductGroupProductsInnerPricingOneOf3TiersInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductGroupProductsInnerPricingOneOf3TiersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["fromInclusive"] = o.FromInclusive
	if o.ToExclusive.IsSet() {
		toSerialize["toExclusive"] = o.ToExclusive.Get()
	}
	if o.Rate.IsSet() {
		toSerialize["rate"] = o.Rate.Get()
	}
	if o.FlatFee.IsSet() {
		toSerialize["flatFee"] = o.FlatFee.Get()
	}
	if o.PackageSize.IsSet() {
		toSerialize["packageSize"] = o.PackageSize.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProductGroupProductsInnerPricingOneOf3TiersInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"fromInclusive",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProductGroupProductsInnerPricingOneOf3TiersInner := _ProductGroupProductsInnerPricingOneOf3TiersInner{}

	err = json.Unmarshal(data, &varProductGroupProductsInnerPricingOneOf3TiersInner)

	if err != nil {
		return err
	}

	*o = ProductGroupProductsInnerPricingOneOf3TiersInner(varProductGroupProductsInnerPricingOneOf3TiersInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "fromInclusive")
		delete(additionalProperties, "toExclusive")
		delete(additionalProperties, "rate")
		delete(additionalProperties, "flatFee")
		delete(additionalProperties, "packageSize")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableProductGroupProductsInnerPricingOneOf3TiersInner struct {
	value *ProductGroupProductsInnerPricingOneOf3TiersInner
	isSet bool
}

func (v NullableProductGroupProductsInnerPricingOneOf3TiersInner) Get() *ProductGroupProductsInnerPricingOneOf3TiersInner {
	return v.value
}

func (v *NullableProductGroupProductsInnerPricingOneOf3TiersInner) Set(val *ProductGroupProductsInnerPricingOneOf3TiersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableProductGroupProductsInnerPricingOneOf3TiersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableProductGroupProductsInnerPricingOneOf3TiersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductGroupProductsInnerPricingOneOf3TiersInner(val *ProductGroupProductsInnerPricingOneOf3TiersInner) *NullableProductGroupProductsInnerPricingOneOf3TiersInner {
	return &NullableProductGroupProductsInnerPricingOneOf3TiersInner{value: val, isSet: true}
}

func (v NullableProductGroupProductsInnerPricingOneOf3TiersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductGroupProductsInnerPricingOneOf3TiersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


