/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the V2EventsDryRunResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2EventsDryRunResponse{}

// V2EventsDryRunResponse struct for V2EventsDryRunResponse
type V2EventsDryRunResponse struct {
	Events []EventsDryRunResponseObject `json:"events"`
	AdditionalProperties map[string]interface{}
}

type _V2EventsDryRunResponse V2EventsDryRunResponse

// NewV2EventsDryRunResponse instantiates a new V2EventsDryRunResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2EventsDryRunResponse(events []EventsDryRunResponseObject) *V2EventsDryRunResponse {
	this := V2EventsDryRunResponse{}
	this.Events = events
	return &this
}

// NewV2EventsDryRunResponseWithDefaults instantiates a new V2EventsDryRunResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2EventsDryRunResponseWithDefaults() *V2EventsDryRunResponse {
	this := V2EventsDryRunResponse{}
	return &this
}

// GetEvents returns the Events field value
func (o *V2EventsDryRunResponse) GetEvents() []EventsDryRunResponseObject {
	if o == nil {
		var ret []EventsDryRunResponseObject
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *V2EventsDryRunResponse) GetEventsOk() ([]EventsDryRunResponseObject, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *V2EventsDryRunResponse) SetEvents(v []EventsDryRunResponseObject) {
	o.Events = v
}

func (o V2EventsDryRunResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2EventsDryRunResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["events"] = o.Events

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *V2EventsDryRunResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"events",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV2EventsDryRunResponse := _V2EventsDryRunResponse{}

	err = json.Unmarshal(data, &varV2EventsDryRunResponse)

	if err != nil {
		return err
	}

	*o = V2EventsDryRunResponse(varV2EventsDryRunResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "events")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableV2EventsDryRunResponse struct {
	value *V2EventsDryRunResponse
	isSet bool
}

func (v NullableV2EventsDryRunResponse) Get() *V2EventsDryRunResponse {
	return v.value
}

func (v *NullableV2EventsDryRunResponse) Set(val *V2EventsDryRunResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV2EventsDryRunResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV2EventsDryRunResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2EventsDryRunResponse(val *V2EventsDryRunResponse) *NullableV2EventsDryRunResponse {
	return &NullableV2EventsDryRunResponse{value: val, isSet: true}
}

func (v NullableV2EventsDryRunResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2EventsDryRunResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


