/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the PartnerSubmissionDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PartnerSubmissionDetail{}

// PartnerSubmissionDetail struct for PartnerSubmissionDetail
type PartnerSubmissionDetail struct {
	// The timestamp when the submission was received by the partner
	ReceivedAt string `json:"receivedAt"`
	// The status of the partner submission
	Status string `json:"status"`
	// Error details if the submission failed, null otherwise
	Error interface{} `json:"error,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PartnerSubmissionDetail PartnerSubmissionDetail

// NewPartnerSubmissionDetail instantiates a new PartnerSubmissionDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPartnerSubmissionDetail(receivedAt string, status string) *PartnerSubmissionDetail {
	this := PartnerSubmissionDetail{}
	this.ReceivedAt = receivedAt
	this.Status = status
	return &this
}

// NewPartnerSubmissionDetailWithDefaults instantiates a new PartnerSubmissionDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartnerSubmissionDetailWithDefaults() *PartnerSubmissionDetail {
	this := PartnerSubmissionDetail{}
	return &this
}

// GetReceivedAt returns the ReceivedAt field value
func (o *PartnerSubmissionDetail) GetReceivedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReceivedAt
}

// GetReceivedAtOk returns a tuple with the ReceivedAt field value
// and a boolean to check if the value has been set.
func (o *PartnerSubmissionDetail) GetReceivedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReceivedAt, true
}

// SetReceivedAt sets field value
func (o *PartnerSubmissionDetail) SetReceivedAt(v string) {
	o.ReceivedAt = v
}

// GetStatus returns the Status field value
func (o *PartnerSubmissionDetail) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *PartnerSubmissionDetail) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *PartnerSubmissionDetail) SetStatus(v string) {
	o.Status = v
}

// GetError returns the Error field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PartnerSubmissionDetail) GetError() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PartnerSubmissionDetail) GetErrorOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return &o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *PartnerSubmissionDetail) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given interface{} and assigns it to the Error field.
func (o *PartnerSubmissionDetail) SetError(v interface{}) {
	o.Error = v
}

func (o PartnerSubmissionDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PartnerSubmissionDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["receivedAt"] = o.ReceivedAt
	toSerialize["status"] = o.Status
	if o.Error != nil {
		toSerialize["error"] = o.Error
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PartnerSubmissionDetail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"receivedAt",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPartnerSubmissionDetail := _PartnerSubmissionDetail{}

	err = json.Unmarshal(data, &varPartnerSubmissionDetail)

	if err != nil {
		return err
	}

	*o = PartnerSubmissionDetail(varPartnerSubmissionDetail)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "receivedAt")
		delete(additionalProperties, "status")
		delete(additionalProperties, "error")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePartnerSubmissionDetail struct {
	value *PartnerSubmissionDetail
	isSet bool
}

func (v NullablePartnerSubmissionDetail) Get() *PartnerSubmissionDetail {
	return v.value
}

func (v *NullablePartnerSubmissionDetail) Set(val *PartnerSubmissionDetail) {
	v.value = val
	v.isSet = true
}

func (v NullablePartnerSubmissionDetail) IsSet() bool {
	return v.isSet
}

func (v *NullablePartnerSubmissionDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartnerSubmissionDetail(val *PartnerSubmissionDetail) *NullablePartnerSubmissionDetail {
	return &NullablePartnerSubmissionDetail{value: val, isSet: true}
}

func (v NullablePartnerSubmissionDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartnerSubmissionDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


