/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// ExternalOverageStrategy The strategy to apply when the overage occurs
type ExternalOverageStrategy string

// List of ExternalOverageStrategy
const (
	EXTERNALOVERAGESTRATEGY_IGNORE ExternalOverageStrategy = "IGNORE"
	EXTERNALOVERAGESTRATEGY_BLOCK ExternalOverageStrategy = "BLOCK"
	EXTERNALOVERAGESTRATEGY_UPGRADE_PLAN ExternalOverageStrategy = "UPGRADE_PLAN"
	EXTERNALOVERAGESTRATEGY_TOP_UP ExternalOverageStrategy = "TOP_UP"
)

// All allowed values of ExternalOverageStrategy enum
var AllowedExternalOverageStrategyEnumValues = []ExternalOverageStrategy{
	"IGNORE",
	"BLOCK",
	"UPGRADE_PLAN",
	"TOP_UP",
}

func (v *ExternalOverageStrategy) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ExternalOverageStrategy(value)
	for _, existing := range AllowedExternalOverageStrategyEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ExternalOverageStrategy", value)
}

// NewExternalOverageStrategyFromValue returns a pointer to a valid ExternalOverageStrategy
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewExternalOverageStrategyFromValue(v string) (*ExternalOverageStrategy, error) {
	ev := ExternalOverageStrategy(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ExternalOverageStrategy: valid values are %v", v, AllowedExternalOverageStrategyEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ExternalOverageStrategy) IsValid() bool {
	for _, existing := range AllowedExternalOverageStrategyEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ExternalOverageStrategy value
func (v ExternalOverageStrategy) Ptr() *ExternalOverageStrategy {
	return &v
}

type NullableExternalOverageStrategy struct {
	value *ExternalOverageStrategy
	isSet bool
}

func (v NullableExternalOverageStrategy) Get() *ExternalOverageStrategy {
	return v.value
}

func (v *NullableExternalOverageStrategy) Set(val *ExternalOverageStrategy) {
	v.value = val
	v.isSet = true
}

func (v NullableExternalOverageStrategy) IsSet() bool {
	return v.isSet
}

func (v *NullableExternalOverageStrategy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExternalOverageStrategy(val *ExternalOverageStrategy) *NullableExternalOverageStrategy {
	return &NullableExternalOverageStrategy{value: val, isSet: true}
}

func (v NullableExternalOverageStrategy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExternalOverageStrategy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

