/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateCustomerRelationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCustomerRelationResponse{}

// CreateCustomerRelationResponse struct for CreateCustomerRelationResponse
type CreateCustomerRelationResponse struct {
	CustomerRelation CreateCustomerRelationResponseCustomerRelation `json:"customerRelation"`
	AdditionalProperties map[string]interface{}
}

type _CreateCustomerRelationResponse CreateCustomerRelationResponse

// NewCreateCustomerRelationResponse instantiates a new CreateCustomerRelationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCustomerRelationResponse(customerRelation CreateCustomerRelationResponseCustomerRelation) *CreateCustomerRelationResponse {
	this := CreateCustomerRelationResponse{}
	this.CustomerRelation = customerRelation
	return &this
}

// NewCreateCustomerRelationResponseWithDefaults instantiates a new CreateCustomerRelationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCustomerRelationResponseWithDefaults() *CreateCustomerRelationResponse {
	this := CreateCustomerRelationResponse{}
	return &this
}

// GetCustomerRelation returns the CustomerRelation field value
func (o *CreateCustomerRelationResponse) GetCustomerRelation() CreateCustomerRelationResponseCustomerRelation {
	if o == nil {
		var ret CreateCustomerRelationResponseCustomerRelation
		return ret
	}

	return o.CustomerRelation
}

// GetCustomerRelationOk returns a tuple with the CustomerRelation field value
// and a boolean to check if the value has been set.
func (o *CreateCustomerRelationResponse) GetCustomerRelationOk() (*CreateCustomerRelationResponseCustomerRelation, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomerRelation, true
}

// SetCustomerRelation sets field value
func (o *CreateCustomerRelationResponse) SetCustomerRelation(v CreateCustomerRelationResponseCustomerRelation) {
	o.CustomerRelation = v
}

func (o CreateCustomerRelationResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCustomerRelationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["customerRelation"] = o.CustomerRelation

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateCustomerRelationResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"customerRelation",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateCustomerRelationResponse := _CreateCustomerRelationResponse{}

	err = json.Unmarshal(data, &varCreateCustomerRelationResponse)

	if err != nil {
		return err
	}

	*o = CreateCustomerRelationResponse(varCreateCustomerRelationResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "customerRelation")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateCustomerRelationResponse struct {
	value *CreateCustomerRelationResponse
	isSet bool
}

func (v NullableCreateCustomerRelationResponse) Get() *CreateCustomerRelationResponse {
	return v.value
}

func (v *NullableCreateCustomerRelationResponse) Set(val *CreateCustomerRelationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCustomerRelationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCustomerRelationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCustomerRelationResponse(val *CreateCustomerRelationResponse) *NullableCreateCustomerRelationResponse {
	return &NullableCreateCustomerRelationResponse{value: val, isSet: true}
}

func (v NullableCreateCustomerRelationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCustomerRelationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


