/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// CustomerRelationType Relation type between parent and child customer. Defaults to accumulateUsage.
type CustomerRelationType string

// List of CustomerRelationType
const (
	CUSTOMERRELATIONTYPE_ACCUMULATE_USAGE CustomerRelationType = "accumulateUsage"
	CUSTOMERRELATIONTYPE_ACCUMULATE_CHARGES CustomerRelationType = "accumulateCharges"
	CUSTOMERRELATIONTYPE_ERP_INVOICE_SYNC_ON_BEHALF_PARENT CustomerRelationType = "erpInvoiceSyncOnBehalfParent"
)

// All allowed values of CustomerRelationType enum
var AllowedCustomerRelationTypeEnumValues = []CustomerRelationType{
	"accumulateUsage",
	"accumulateCharges",
	"erpInvoiceSyncOnBehalfParent",
}

func (v *CustomerRelationType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CustomerRelationType(value)
	for _, existing := range AllowedCustomerRelationTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CustomerRelationType", value)
}

// NewCustomerRelationTypeFromValue returns a pointer to a valid CustomerRelationType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCustomerRelationTypeFromValue(v string) (*CustomerRelationType, error) {
	ev := CustomerRelationType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CustomerRelationType: valid values are %v", v, AllowedCustomerRelationTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CustomerRelationType) IsValid() bool {
	for _, existing := range AllowedCustomerRelationTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CustomerRelationType value
func (v CustomerRelationType) Ptr() *CustomerRelationType {
	return &v
}

type NullableCustomerRelationType struct {
	value *CustomerRelationType
	isSet bool
}

func (v NullableCustomerRelationType) Get() *CustomerRelationType {
	return v.value
}

func (v *NullableCustomerRelationType) Set(val *CustomerRelationType) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerRelationType) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerRelationType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerRelationType(val *CustomerRelationType) *NullableCustomerRelationType {
	return &NullableCustomerRelationType{value: val, isSet: true}
}

func (v NullableCustomerRelationType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerRelationType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

