/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateMeasurementRequestUsageDate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateMeasurementRequestUsageDate{}

// CreateMeasurementRequestUsageDate The day the usage took place
type CreateMeasurementRequestUsageDate struct {
	Year int32 `json:"year"`
	Month int32 `json:"month"`
	Day int32 `json:"day"`
	AdditionalProperties map[string]interface{}
}

type _CreateMeasurementRequestUsageDate CreateMeasurementRequestUsageDate

// NewCreateMeasurementRequestUsageDate instantiates a new CreateMeasurementRequestUsageDate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateMeasurementRequestUsageDate(year int32, month int32, day int32) *CreateMeasurementRequestUsageDate {
	this := CreateMeasurementRequestUsageDate{}
	this.Year = year
	this.Month = month
	this.Day = day
	return &this
}

// NewCreateMeasurementRequestUsageDateWithDefaults instantiates a new CreateMeasurementRequestUsageDate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateMeasurementRequestUsageDateWithDefaults() *CreateMeasurementRequestUsageDate {
	this := CreateMeasurementRequestUsageDate{}
	return &this
}

// GetYear returns the Year field value
func (o *CreateMeasurementRequestUsageDate) GetYear() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Year
}

// GetYearOk returns a tuple with the Year field value
// and a boolean to check if the value has been set.
func (o *CreateMeasurementRequestUsageDate) GetYearOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Year, true
}

// SetYear sets field value
func (o *CreateMeasurementRequestUsageDate) SetYear(v int32) {
	o.Year = v
}

// GetMonth returns the Month field value
func (o *CreateMeasurementRequestUsageDate) GetMonth() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Month
}

// GetMonthOk returns a tuple with the Month field value
// and a boolean to check if the value has been set.
func (o *CreateMeasurementRequestUsageDate) GetMonthOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Month, true
}

// SetMonth sets field value
func (o *CreateMeasurementRequestUsageDate) SetMonth(v int32) {
	o.Month = v
}

// GetDay returns the Day field value
func (o *CreateMeasurementRequestUsageDate) GetDay() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Day
}

// GetDayOk returns a tuple with the Day field value
// and a boolean to check if the value has been set.
func (o *CreateMeasurementRequestUsageDate) GetDayOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Day, true
}

// SetDay sets field value
func (o *CreateMeasurementRequestUsageDate) SetDay(v int32) {
	o.Day = v
}

func (o CreateMeasurementRequestUsageDate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateMeasurementRequestUsageDate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["year"] = o.Year
	toSerialize["month"] = o.Month
	toSerialize["day"] = o.Day

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateMeasurementRequestUsageDate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"year",
		"month",
		"day",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateMeasurementRequestUsageDate := _CreateMeasurementRequestUsageDate{}

	err = json.Unmarshal(data, &varCreateMeasurementRequestUsageDate)

	if err != nil {
		return err
	}

	*o = CreateMeasurementRequestUsageDate(varCreateMeasurementRequestUsageDate)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "year")
		delete(additionalProperties, "month")
		delete(additionalProperties, "day")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateMeasurementRequestUsageDate struct {
	value *CreateMeasurementRequestUsageDate
	isSet bool
}

func (v NullableCreateMeasurementRequestUsageDate) Get() *CreateMeasurementRequestUsageDate {
	return v.value
}

func (v *NullableCreateMeasurementRequestUsageDate) Set(val *CreateMeasurementRequestUsageDate) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateMeasurementRequestUsageDate) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateMeasurementRequestUsageDate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateMeasurementRequestUsageDate(val *CreateMeasurementRequestUsageDate) *NullableCreateMeasurementRequestUsageDate {
	return &NullableCreateMeasurementRequestUsageDate{value: val, isSet: true}
}

func (v NullableCreateMeasurementRequestUsageDate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateMeasurementRequestUsageDate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


