/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the PlanBillingData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlanBillingData{}

// PlanBillingData The billing data of the plan. The billing data contains the billing interval, the plan duration the payment terms and auto renewal, and the billing method.
type PlanBillingData struct {
	BillingInterval BillingInterval `json:"billingInterval"`
	Duration PlanDuration `json:"duration"`
	PaymentTerm PaymentTerm `json:"paymentTerm"`
	AutoRenewal bool `json:"autoRenewal"`
	ProRated NullableBool `json:"proRated,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PlanBillingData PlanBillingData

// NewPlanBillingData instantiates a new PlanBillingData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlanBillingData(billingInterval BillingInterval, duration PlanDuration, paymentTerm PaymentTerm, autoRenewal bool) *PlanBillingData {
	this := PlanBillingData{}
	this.BillingInterval = billingInterval
	this.Duration = duration
	this.PaymentTerm = paymentTerm
	this.AutoRenewal = autoRenewal
	return &this
}

// NewPlanBillingDataWithDefaults instantiates a new PlanBillingData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlanBillingDataWithDefaults() *PlanBillingData {
	this := PlanBillingData{}
	var autoRenewal bool = false
	this.AutoRenewal = autoRenewal
	return &this
}

// GetBillingInterval returns the BillingInterval field value
func (o *PlanBillingData) GetBillingInterval() BillingInterval {
	if o == nil {
		var ret BillingInterval
		return ret
	}

	return o.BillingInterval
}

// GetBillingIntervalOk returns a tuple with the BillingInterval field value
// and a boolean to check if the value has been set.
func (o *PlanBillingData) GetBillingIntervalOk() (*BillingInterval, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BillingInterval, true
}

// SetBillingInterval sets field value
func (o *PlanBillingData) SetBillingInterval(v BillingInterval) {
	o.BillingInterval = v
}

// GetDuration returns the Duration field value
func (o *PlanBillingData) GetDuration() PlanDuration {
	if o == nil {
		var ret PlanDuration
		return ret
	}

	return o.Duration
}

// GetDurationOk returns a tuple with the Duration field value
// and a boolean to check if the value has been set.
func (o *PlanBillingData) GetDurationOk() (*PlanDuration, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Duration, true
}

// SetDuration sets field value
func (o *PlanBillingData) SetDuration(v PlanDuration) {
	o.Duration = v
}

// GetPaymentTerm returns the PaymentTerm field value
func (o *PlanBillingData) GetPaymentTerm() PaymentTerm {
	if o == nil {
		var ret PaymentTerm
		return ret
	}

	return o.PaymentTerm
}

// GetPaymentTermOk returns a tuple with the PaymentTerm field value
// and a boolean to check if the value has been set.
func (o *PlanBillingData) GetPaymentTermOk() (*PaymentTerm, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaymentTerm, true
}

// SetPaymentTerm sets field value
func (o *PlanBillingData) SetPaymentTerm(v PaymentTerm) {
	o.PaymentTerm = v
}

// GetAutoRenewal returns the AutoRenewal field value
func (o *PlanBillingData) GetAutoRenewal() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AutoRenewal
}

// GetAutoRenewalOk returns a tuple with the AutoRenewal field value
// and a boolean to check if the value has been set.
func (o *PlanBillingData) GetAutoRenewalOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AutoRenewal, true
}

// SetAutoRenewal sets field value
func (o *PlanBillingData) SetAutoRenewal(v bool) {
	o.AutoRenewal = v
}

// GetProRated returns the ProRated field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PlanBillingData) GetProRated() bool {
	if o == nil || IsNil(o.ProRated.Get()) {
		var ret bool
		return ret
	}
	return *o.ProRated.Get()
}

// GetProRatedOk returns a tuple with the ProRated field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PlanBillingData) GetProRatedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProRated.Get(), o.ProRated.IsSet()
}

// HasProRated returns a boolean if a field has been set.
func (o *PlanBillingData) HasProRated() bool {
	if o != nil && o.ProRated.IsSet() {
		return true
	}

	return false
}

// SetProRated gets a reference to the given NullableBool and assigns it to the ProRated field.
func (o *PlanBillingData) SetProRated(v bool) {
	o.ProRated.Set(&v)
}
// SetProRatedNil sets the value for ProRated to be an explicit nil
func (o *PlanBillingData) SetProRatedNil() {
	o.ProRated.Set(nil)
}

// UnsetProRated ensures that no value is present for ProRated, not even an explicit nil
func (o *PlanBillingData) UnsetProRated() {
	o.ProRated.Unset()
}

func (o PlanBillingData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlanBillingData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["billingInterval"] = o.BillingInterval
	toSerialize["duration"] = o.Duration
	toSerialize["paymentTerm"] = o.PaymentTerm
	toSerialize["autoRenewal"] = o.AutoRenewal
	if o.ProRated.IsSet() {
		toSerialize["proRated"] = o.ProRated.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PlanBillingData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"billingInterval",
		"duration",
		"paymentTerm",
		"autoRenewal",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPlanBillingData := _PlanBillingData{}

	err = json.Unmarshal(data, &varPlanBillingData)

	if err != nil {
		return err
	}

	*o = PlanBillingData(varPlanBillingData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "billingInterval")
		delete(additionalProperties, "duration")
		delete(additionalProperties, "paymentTerm")
		delete(additionalProperties, "autoRenewal")
		delete(additionalProperties, "proRated")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePlanBillingData struct {
	value *PlanBillingData
	isSet bool
}

func (v NullablePlanBillingData) Get() *PlanBillingData {
	return v.value
}

func (v *NullablePlanBillingData) Set(val *PlanBillingData) {
	v.value = val
	v.isSet = true
}

func (v NullablePlanBillingData) IsSet() bool {
	return v.isSet
}

func (v *NullablePlanBillingData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlanBillingData(val *PlanBillingData) *NullablePlanBillingData {
	return &NullablePlanBillingData{value: val, isSet: true}
}

func (v NullablePlanBillingData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlanBillingData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


