/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the V2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic{}

// V2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic struct for V2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic
type V2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic struct {
	Operator string `json:"operator"`
	Field string `json:"field"`
	AdditionalProperties map[string]interface{}
}

type _V2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic V2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic

// NewV2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic instantiates a new V2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic(operator string, field string) *V2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic {
	this := V2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic{}
	this.Operator = operator
	this.Field = field
	return &this
}

// NewV2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmeticWithDefaults instantiates a new V2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmeticWithDefaults() *V2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic {
	this := V2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic{}
	return &this
}

// GetOperator returns the Operator field value
func (o *V2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic) GetOperator() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Operator
}

// GetOperatorOk returns a tuple with the Operator field value
// and a boolean to check if the value has been set.
func (o *V2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic) GetOperatorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Operator, true
}

// SetOperator sets field value
func (o *V2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic) SetOperator(v string) {
	o.Operator = v
}

// GetField returns the Field field value
func (o *V2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic) GetField() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Field
}

// GetFieldOk returns a tuple with the Field field value
// and a boolean to check if the value has been set.
func (o *V2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic) GetFieldOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Field, true
}

// SetField sets field value
func (o *V2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic) SetField(v string) {
	o.Field = v
}

func (o V2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["operator"] = o.Operator
	toSerialize["field"] = o.Field

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *V2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"operator",
		"field",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic := _V2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic{}

	err = json.Unmarshal(data, &varV2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic)

	if err != nil {
		return err
	}

	*o = V2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic(varV2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "operator")
		delete(additionalProperties, "field")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableV2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic struct {
	value *V2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic
	isSet bool
}

func (v NullableV2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic) Get() *V2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic {
	return v.value
}

func (v *NullableV2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic) Set(val *V2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic) {
	v.value = val
	v.isSet = true
}

func (v NullableV2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic) IsSet() bool {
	return v.isSet
}

func (v *NullableV2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic(val *V2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic) *NullableV2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic {
	return &NullableV2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic{value: val, isSet: true}
}

func (v NullableV2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2QueryEventsAggregationRequestMetersInnerAggregationFieldArithmetic) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


